BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "Lo que un entrenador necesita…\p"
	.string "Conocimiento…\n"
	.string "Estrategia…\l"
	.string "Suerte…\l"
	.string "Agallas…\l"
	.string "Espíritu…\l"
	.string "Valentía…\l"
	.string "Y habilidad…\p"
	.string "¡Bueno, estoy preparado en todos los\n"
	.string "sentidos!\p"
	.string "¡Seré imparable en todos los\n"
	.string "edificios!\p"
	.string "¿Eh? ¿Pokémon?\n"
	.string "¿Qué es eso?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "¿Sabes de los Ases del Frente?\p"
	.string "Así es como Treto llama a los siete\n"
	.string "entrenadores especiales que dirigen las\l"
	.string "siete instalaciones del Frente Batalla.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "En la Torre Batalla, una chica mayor me\n"
	.string "dijo que tengo mucho talento para los\l"
	.string "combates.\p"
	.string "¡Pero me gustan más los Concursos\n"
	.string "Pokémon!\p"
	.string "¡Pero no se me dan bien los Concursos!\p"
	.string "Supongo que tener talento y gustarte\n"
	.string "algo no es lo mismo.$"

