SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Parece que hay alguna conexión entre\n"
	.string "ARRECÍPOLIS y el MONTE PÍRICO.\p"
	.string "Mis amigos y yo investigamos un poco\n"
	.string "sobre ello en el laboratorio donde\l"
	.string "solía trabajar.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mi hermano mayor solía estudiar el mar.$"

