RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "La ESCUELA DE ENTRENADORES es\n"
	.string "excelente.\p"
	.string "Si estudias allí, incluso podrías\n"
	.string "llegar a ser LÍDER DE GIMNASIO.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "PETRA, la LÍDER DE GIMNASIO, sabe\n"
	.string "muchísimo sobre los POKéMON.\p"
	.string "¡También es muy fuerte!$"

