gText_ApprenticeChallenge0::
	.string "Ejem, soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}.\l"
	.string "Sollozo… Esta tensión me está afectando…$"

gText_ApprenticeChallenge1::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}!\l"
	.string "¡Allá vamos!$"

gText_ApprenticeChallenge2::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}!\l"
	.string "¡Acepta mi reto!$"

gText_ApprenticeChallenge3::
	.string "Ejem… Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}…\l"
	.string "¿Crees que alguien como yo puede ganar?$"

gText_ApprenticeChallenge4::
	.string "¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}!\l"
	.string "¡Te dejaré que me retes!$"

gText_ApprenticeChallenge5::
	.string "Estoy terriblemente ocupado, pero\n"
	.string "también resulta que soy el aprendiz\l"
	.string "n.º {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge6::
	.string "Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}.\l"
	.string "¡Encantado de conocerte!$"

gText_ApprenticeChallenge7::
	.string "Sirvo como aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}.\l"
	.string "¿Puedo empezar?$"

gText_ApprenticeChallenge8::
	.string "¡Eek! ¡Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}!\l"
	.string "¡Haré lo que pueda!$"

gText_ApprenticeChallenge9::
	.string "¡Yeehaw! ¡Soy el aprendiz n.º {STR_VAR_2}\n"
	.string "de {STR_VAR_1}!\l"
	.string "¡Arriba las manos!$"

gText_ApprenticeChallenge10::
	.string "¡Soy el aprendiz n.º 1.000 de\n"
	.string "{STR_VAR_1}!\l"
	.string "Bueno, en realidad soy el n.º {STR_VAR_2}.\l"
	.string "¡Allá vamos!$"

gText_ApprenticeChallenge11::
	.string "¡Sí, soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}!\l"
	.string "¡Vamos a darlo todo!$"

gText_ApprenticeChallenge12::
	.string "¡Yippee-yahoo! Soy lo que se dice el\n"
	.string "aprendiz n.º {STR_VAR_2} de {STR_VAR_1}.$"

gText_ApprenticeChallenge13::
	.string "¡Cof! Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}.\l"
	.string "¡Encantado de conocerte! ¡Cof!$"

gText_ApprenticeChallenge14::
	.string "Esto es estresante…\n"
	.string "Soy el aprendiz n.º {STR_VAR_2} de\l"
	.string "{STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Soy el aprendiz n.º {STR_VAR_2} de\n"
	.string "{STR_VAR_1}, y no es mentira.$"

gText_ApprenticePleaseTeach0::
	.string "¿Eres… {PLAYER}?\n"
	.string "¡Oh! Snif… sollozo…\p"
	.string "¡Oh! P-perdona…\n"
	.string "Estoy tan nervioso que no puedo evitar\l"
	.string "llorar…\p"
	.string "Soy {STR_VAR_1}, y te admiro mucho,\n"
	.string "{PLAYER}.\p"
	.string "Tuve este sueño de conocerte algún día\n"
	.string "y preguntarte sobre los POKéMON.\p"
	.string "¡Por favor, por favor, {PLAYER}!\n"
	.string "¡Enséñame sobre los POKéMON!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… P-pero…\n"
	.string "Snif… ¡Waaaaaaah!\p"
	.string "¡Por favor!\n"
	.string "¡Te lo suplico, por favor!$"

gText_ApprenticeWhichLevelMode0::
	.string "¿Oh, de verdad? ¿Sí?\n"
	.string "¡Genial! ¡Increíble! ¡Awoooh!\p"
	.string "Oh… Perdona…\n"
	.string "Estoy tan feliz que estoy llorando…\p"
	.string "Ejem… Entonces, ¡dime!\n"
	.string "Es sobre la TORRE BATALLA.\p"
	.string "¿Qué sería mejor para mí: Nivel 50\n"
	.string "o Nivel Libre?$"

gText_ApprenticeLevelModeThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Waaaaah!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "Me has hecho tan feliz eligiendo el\l"
	.string "nivel para mí que he empezado a llorar…\p"
	.string "Snif…\n"
	.string "¡Muchísimas gracias!\l"
	.string "¡Hablemos otra vez!$"

gText_ApprenticePleaseTeach1::
	.string "¡Vaya! ¡Eres {PLAYER}, verdad?\n"
	.string "¡Eres increíblemente fuerte, ¿no?\p"
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Acabo de convertirme en ENTRENADOR!\p"
	.string "¡Por favor, {PLAYER}!\n"
	.string "¿Puedes ser mi maestro y contarme\l"
	.string "muchas cosas sobre ser ENTRENADOR?$"

gText_ApprenticeRejectTeaching1::
	.string "Vaya, ¿por qué?\n"
	.string "Oh, ¿por favor? ¿Por favor, por favor?\l"
	.string "¡Sé mi maestro, por favor!$"

gText_ApprenticeWhichLevelMode1::
	.string "¡Yupi! ¡Genial!\p"
	.string "Lo primero que quería preguntarte es\n"
	.string "sobre la TORRE BATALLA.\p"
	.string "Las salas de Nivel 50 y Nivel Libre…\n"
	.string "¿Cuál sería perfecta para mí?$"

gText_ApprenticeLevelModeThanks1::
	.string "¿{STR_VAR_1}, eh? ¡Es verdad!\n"
	.string "¡Haré lo mejor que pueda allí!\p"
	.string "Si nos encontramos aquí otra vez, por\n"
	.string "favor, enséñame algo más, maestro.$"

gText_ApprenticePleaseTeach2::
	.string "Ejem… ¿Eres {PLAYER}?\n"
	.string "Me llamo {STR_VAR_1}.\p"
	.string "Quiero convertirme en ENTRENADOR\n"
	.string "POKéMON, pero no sé qué hacer…\p"
	.string "Así que pensé que podría pedirte\n"
	.string "consejo porque eres tan famoso.\p"
	.string "{PLAYER}, ¿podrías darme consejos?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, pero…\p"
	.string "¡Sinceramente quiero convertirme en\n"
	.string "ENTRENADOR POKéMON!\p"
	.string "Por favor, ¿puedes responder mis\n"
	.string "preguntas?$"

gText_ApprenticeWhichLevelMode2::
	.string "¡Gracias!\n"
	.string "¡Aquí va mi primera pregunta!\p"
	.string "La TORRE BATALLA tiene dos niveles,\n"
	.string "Nivel 50 y Nivel Libre, ¿verdad?\p"
	.string "¿Qué nivel crees que es más adecuado\n"
	.string "para mí?$"

gText_ApprenticeLevelModeThanks2::
	.string "¿Oh, el reto de {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "Si tengo otra pregunta, volveré aquí\n"
	.string "a pedirte consejo.$"

gText_ApprenticePleaseTeach3::
	.string "¿Oh? ¿Eh? Eres…\n"
	.string "No, eso no puede ser cierto.\p"
	.string "No hay manera de que alguien como yo\n"
	.string "pueda conocer a {PLAYER}.\p"
	.string "…¿De verdad eres {PLAYER}?\n"
	.string "¡No puedo creer que esté hablando\l"
	.string "contigo!\p"
	.string "Cuando algo tan bueno me pasa, solo\n"
	.string "me pasarán cosas terribles ahora,\l"
	.string "lo sé…\p"
	.string "…Perdona…\n"
	.string "Soy… {STR_VAR_1}…\p"
	.string "No hay nada especial en mí de lo que\n"
	.string "pueda estar orgulloso…\p"
	.string "Ni siquiera debería hablar de mí\n"
	.string "mismo porque lo olvidarás…\p"
	.string "Tuve este sueño de que si alguna vez\n"
	.string "te conocía, {PLAYER}, podría pedirte\l"
	.string "consejo como ENTRENADOR.\p"
	.string "Pero no creo que aceptes.\p"
	.string "…¿O serás tan amable de darme\n"
	.string "consejo?$"

gText_ApprenticeRejectTeaching3::
	.string "Lo sabía…\p"
	.string "Tenía que pasar porque soy un\n"
	.string "aburrido don nadie…\p"
	.string "Pero pensé que quizá…\n"
	.string "¿No lo reconsiderarás?\p"
	.string "Pero no puedo rendirme así como así.\n"
	.string "¡Te preguntaré mientras aún tenga\l"
	.string "suerte!\p"
	.string "Por favor, ¿serás tan amable de darme\n"
	.string "consejo?$"

gText_ApprenticeWhichLevelMode3::
	.string "¿De verdad? ¡No puedo creerlo!\n"
	.string "¡No puedo creer que me aconsejes!\l"
	.string "Estoy… Estoy tan feliz…\p"
	.string "Lo que quiero preguntarte es realmente\n"
	.string "trivial, pero no puedo decidir…\p"
	.string "En la TORRE BATALLA te dejan elegir\n"
	.string "entre Nivel 50 y Nivel Libre.\p"
	.string "¿Qué curso crees que incluso yo podría\n"
	.string "tener una oportunidad?$"

gText_ApprenticeLevelModeThanks3::
	.string "¿{STR_VAR_1}? Vale.\n"
	.string "Pero ¿de verdad crees que alguien\l"
	.string "como yo tendría una oportunidad?\p"
	.string "Haré lo mejor que pueda, aunque no\n"
	.string "creo que funcione.\p"
	.string "Muchísimas gracias por dedicar tu\n"
	.string "tiempo a alguien como yo.$"

gText_ApprenticePleaseTeach4::
	.string "¡Oh! ¡Eres {PLAYER}{KUN}, verdad?\p"
	.string "¡He oído que eres muy duro en los\n"
	.string "POKéMON!\p"
	.string "¡Soy {STR_VAR_1}!\n"
	.string "¡Seré tu amigo!\p"
	.string "¿Lo sabías?\p"
	.string "No puedes ganar en el FRENTE BATALLA\n"
	.string "si solo sabes lo que enseñan en la\l"
	.string "ESCUELA DE ENTRENADORES.\p"
	.string "Estoy dispuesto a escuchar tus\n"
	.string "consejos.\l"
	.string "Aceptarás, por supuesto, ¿verdad?$"

gText_ApprenticeRejectTeaching4::
	.string "¿Eh? ¿Por qué me rechazas?\n"
	.string "¡Soy yo quien te lo pide!\l"
	.string "¡Tienes que reconsiderar!$"

gText_ApprenticeWhichLevelMode4::
	.string "Vale, hay algo que quiero que decidas.\n"
	.string "Quiero que decidas por mí.\p"
	.string "¿Sabes que la TORRE BATALLA tiene\n"
	.string "salas de Nivel 50 y Nivel Libre?\p"
	.string "¿Cuál crees que sería bueno\n"
	.string "para mí, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Vale, ¿{STR_VAR_1} es adecuado para mí?\n"
	.string "¡Gracias!\p"
	.string "Sabiendo que tú has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticePleaseTeach5::
	.string "¡Oh, hola! ¡{PLAYER}{KUN}!\n"
	.string "¡Te conozco porque eres famoso!\l"
	.string "¡Llámame {STR_VAR_1}!\l"
	.string "¡Encantado de conocerte!\p"
	.string "Soy TRIATLETA, así que me mantengo en\n"
	.string "forma incluso mientras crío POKéMON.\p"
	.string "También estoy involucrado en otras\n"
	.string "cosas como el trabajo, las siestas,\l"
	.string "el baile de salón…\p"
	.string "Estando tan ocupado, no es fácil para\n"
	.string "mí convertirme en un buen ENTRENADOR.\p"
	.string "Así que, ¡tengo una propuesta!\p"
	.string "Debe haber una razón por la que nos\n"
	.string "hemos conocido.\l"
	.string "Así que, {PLAYER}{KUN}, ¿qué tal si\l"
	.string "compartes tu sabiduría conmigo de vez\l"
	.string "en cuando?$"

gText_ApprenticeRejectTeaching5::
	.string "Oh, pero, ¿por favor?\n"
	.string "¡Un tipo como yo necesita a alguien\l"
	.string "como tú, {PLAYER}{KUN}!\p"
	.string "¡Honestamente, necesito tu consejo!$"

gText_ApprenticeWhichLevelMode5::
	.string "¡Gracias! ¡Así me gusta!\n"
	.string "Así que empecemos con algo fácil.\p"
	.string "¿Sabes los dos cursos de la TORRE\n"
	.string "BATALLA, verdad?\l"
	.string "Ya sabes, Nivel 50 y Nivel Libre.\p"
	.string "Siendo un tipo ocupado como yo, ¿para\n"
	.string "cuál debería prepararme?$"

gText_ApprenticeLevelModeThanks5::
	.string "¿{STR_VAR_1}, eh? Vale, entendido.\n"
	.string "Encontraré tiempo de alguna forma y\l"
	.string "lo intentaré.\p"
	.string "…Vaya, ¡tengo que ir a trabajar!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticePleaseTeach6::
	.string "¡No puede ser! ¡Uh-uh!\n"
	.string "¿Eres quizá el verdadero {PLAYER}?\p"
	.string "¡A-hah! ¡Increíble! Soy {STR_VAR_1},\n"
	.string "¡encantado de conocerte!\p"
	.string "{PLAYER}, eres muy fuerte,\n"
	.string "¿verdad?\p"
	.string "¡Todo el mundo habla de ti!\p"
	.string "¡Oh! ¡Acabo de tener esta gran idea!\n"
	.string "¡Te pediré consejo, {PLAYER}!\l"
	.string "¡Seguro que me hará más fuerte!\p"
	.string "¿No es una gran idea?\n"
	.string "¡Por favor, quiero tu consejo!$"

gText_ApprenticeRejectTeaching6::
	.string "Ajajaja, puedes fingir ser malo,\n"
	.string "pero no puedes engañarme.\l"
	.string "En realidad quieres decir que sí,\l"
	.string "¿verdad?$"

gText_ApprenticeWhichLevelMode6::
	.string "¡Yay! ¡Sabía que tendrías un gran\n"
	.string "corazón, {PLAYER}!\p"
	.string "¿Qué debería preguntarte primero?\n"
	.string "…Oh, ¡se me ha ocurrido algo!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La pregunta que tengo es…\p"
	.string "Si fuera a hacer un reto de la TORRE\n"
	.string "BATALLA, ¿qué camino debería tomar?\p"
	.string "¿Nivel 50 o Nivel Libre?\n"
	.string "¿Cuál me conviene más?$"

gText_ApprenticeLevelModeThanks6::
	.string "¡Oh-oh-oh!\n"
	.string "¿{STR_VAR_1}, dices?\l"
	.string "¡Gracias por una respuesta tan genial!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticePleaseTeach7::
	.string "Disculpe, pero…\n"
	.string "¿Es usted {PLAYER}?\p"
	.string "Soy {STR_VAR_1}, y estoy encantado de\n"
	.string "hacer su conocimiento.\p"
	.string "He sido su admirador durante mucho\n"
	.string "tiempo…\p"
	.string "… … … … … …\p"
	.string "Ejem… Espero que no encuentre esta\n"
	.string "petición demasiado pesada, pero…\p"
	.string "¿Puedo convertirme en su aprendiz,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "¡Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Debo haberme desmayado del shock.\n"
	.string "Lo siento, debí haberlo oído mal.\p"
	.string "¡Por favor! ¡Por favor diga que me\n"
	.string "aceptará como aprendiz!$"

gText_ApprenticeWhichLevelMode7::
	.string "¡Oh… Estoy encantado!\p"
	.string "No quiero hacerle perder el tiempo,\n"
	.string "así que por favor, aconsejeme sobre esto.\p"
	.string "Planeo hacer un reto de la TORRE\n"
	.string "BATALLA pronto.\p"
	.string "Sin embargo, hay dos niveles…\p"
	.string "¿Cuál sería el más adecuado para mí?\n"
	.string "¿Nivel 50 o Nivel Libre?$"

gText_ApprenticeLevelModeThanks7::
	.string "¡{STR_VAR_1} es su elección!\n"
	.string "Ya veo. ¡Haré lo mejor que pueda!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar con usted otra\l"
	.string "vez. ¡Cuídese!$"

gText_ApprenticePleaseTeach8::
	.string "¡Eek! ¡Eek! ¡{PLAYER}!\n"
	.string "¡Me has hablado!\l"
	.string "¡Estoy… Estoy eufórico!\p"
	.string "¡Yo! ¡Me llamo {STR_VAR_1}!\n"
	.string "¡Acabo de convertirme en ENTRENADOR!\p"
	.string "¡Estoy encantado de haberte conocido,\n"
	.string "{PLAYER}, la gran figura de los\l"
	.string "círculos POKéMON!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¡Puedo pedirte un gran favor, {PLAYER}?\p"
	.string "¡Por favor, tómame como aprendiz!\n"
	.string "¡Quiero aprender de ti!$"

gText_ApprenticeRejectTeaching8::
	.string "¡Waaaah!\n"
	.string "{PLAYER} me ha rechazado…\l"
	.string "Es… Es una experiencia invaluable.\p"
	.string "{PLAYER}, ¡por favor! Quiero escuchar\n"
	.string "una respuesta afirmativa esta vez.\p"
	.string "¡Te suplico tu guía!$"

gText_ApprenticeWhichLevelMode8::
	.string "¡Hieeeeh! ¡{PLAYER} ha dicho que sí!\n"
	.string "¡{PLAYER} ha dicho que sí!\p"
	.string "No podré dormir esta noche…\n"
	.string "¡Muchísimas gracias!\p"
	.string "Entonces, ¡aquí va mi pregunta!\p"
	.string "En la TORRE BATALLA, ¿qué es adecuado\n"
	.string "para mí, Nivel 50 o Nivel Libre?$"

gText_ApprenticeLevelModeThanks8::
	.string "¡{STR_VAR_1}! ¡Perfectamente entendido!\n"
	.string "¡Lo entiendo perfectamente!\l"
	.string "¡Estoy delirantemente encantado!\p"
	.string "Espero que estés dispuesto a enseñarme\n"
	.string "algo más en otra ocasión.$"

gText_ApprenticePleaseTeach9::
	.string "¡Vaya! ¿Podrías ser…\n"
	.string "Podrías ser… {PLAYER}{KUN}?!\l"
	.string "¡Ese ENTRENADOR fuerte y famoso?\l"
	.string "¡Bueno, hola, no soy el más afortunado!\p"
	.string "¡Hola, me llamo {STR_VAR_1}!\p"
	.string "He estado buscando un maestro de\n"
	.string "POKéMON.\p"
	.string "Y con un timing impecable,\n"
	.string "¡apareciste tú, {PLAYER}{KUN}!\p"
	.string "Así que, ahí lo tienes, {PLAYER}{KUN}.\n"
	.string "¡Déjame ser tu aprendiz!$"

gText_ApprenticeRejectTeaching9::
	.string "¡Gwaaaah!\n"
	.string "Eres bastante duro y genial…\p"
	.string "No seas así, por favor.\n"
	.string "¡Te lo estoy pidiendo!$"

gText_ApprenticeWhichLevelMode9::
	.string "¡Oh, sí! ¡Esa es una respuesta sólida!\n"
	.string "¡Excelente, debo añadir!\p"
	.string "Así que, ¿qué tal un primer consejo\n"
	.string "sobre la TORRE BATALLA?\p"
	.string "Si fuera a ir, ¿qué sería mejor?\n"
	.string "¿Nivel 50 o Nivel Libre?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, ¡{STR_VAR_1}!\n"
	.string "OK, A-OK.\l"
	.string "¡Iré a demostrar mi valía, como, jam!\p"
	.string "Muy bien, ¡te seguiré como mi mentor!\n"
	.string "¡Adiós!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hola, {PLAYER}{KUN}, ¿verdad?\n"
	.string "¡La policía te estaba buscando!\p"
	.string "… … …\n"
	.string "¡Por supuesto que estoy mintiendo!\p"
	.string "Yo, soy {STR_VAR_1}. A pesar de mi\n"
	.string "apariencia, soy el CAMPEÓN POKéMON.\l"
	.string "…¡Eso también es mentira!\p"
	.string "Esto no es mentira, sin embargo.\n"
	.string "No soy muy bueno combatiendo.\p"
	.string "Así que, ¿qué tal si te conviertes en\n"
	.string "mi maestro sobre todo lo relacionado\l"
	.string "con los POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "Si vas a actuar frío así,\n"
	.string "¡te mostraré lo que haré!\p"
	.string "¡Waaah! ¡Waaah! ¡Waaah!\n"
	.string "¡Hipo!\p"
	.string "¡Jajaja, eso fue mi FINTA!\p"
	.string "Vamos, ¿quieres ser\n"
	.string "mi maestro POKéMON?$"

gText_ApprenticeWhichLevelMode10::
	.string "¡Yippee!\n"
	.string "¡Te compraré un barco por eso!\p"
	.string "¡Por supuesto que estoy mintiendo otra\n"
	.string "vez! Pero… ¡Gracias, maestro!\p"
	.string "¿Sabes que hay Nivel 50 y Nivel Libre\n"
	.string "en la TORRE BATALLA?\p"
	.string "Tengo problemas para decidir qué nivel\n"
	.string "debería retar…\p"
	.string "¿Puedes decidir por mí, maestro?$"

gText_ApprenticeLevelModeThanks10::
	.string "Vale, así que {STR_VAR_1} es mejor.\n"
	.string "¡Iré al otro nivel, entonces!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticePleaseTeach11::
	.string "¡A-H-O-Y!\n"
	.string "¡Eso deletrea ahoy, y significa hola!\p"
	.string "¡Soy {STR_VAR_1}, el MARINERO rapero!\n"
	.string "¡Soy yo!\p"
	.string "Ahora te toca a ti, cuéntame un poco\n"
	.string "sobre ti, ¡inténtalo!\p"
	.string "¡Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} es tu nombre,\l"
	.string "¡y los POKéMON son tu juego!\p"
	.string "Y estás en una edad delicada\n"
	.string "¡en la que todo el mundo es tu escenario!\p"
	.string "De todos modos, solo quiero decir que\n"
	.string "eres el décimo ENTRENADOR con el que\l"
	.string "hablo hoy.\p"
	.string "¡Hagámoslo una celebración!\n"
	.string "¡Conviértete en mi mentor para\l"
	.string "conmemorarlo!$"

gText_ApprenticeRejectTeaching11::
	.string "¡Pero!\n"
	.string "¡Tienes que trabajar conmigo!\p"
	.string "¡No seas tan bromista!\n"
	.string "¡Conviértete en mi mentor, por favor!$"

gText_ApprenticeWhichLevelMode11::
	.string "¡Eso es!\n"
	.string "¡{PLAYER}, tienes el espíritu!\p"
	.string "Así que aquí va mi primera pregunta\n"
	.string "que suplica tu sugerencia.\p"
	.string "Es sobre la TORRE BATALLA,\n"
	.string "¡y depende de mi poder!\p"
	.string "Nivel 50 y Nivel Libre hay,\n"
	.string "¿cuál es el que es bueno para mí?$"

gText_ApprenticeLevelModeThanks11::
	.string "Vale, {STR_VAR_1} es, dices.\n"
	.string "¡Iré y lo intentaré en mi camino!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu palabra!$"

gText_ApprenticePleaseTeach12::
	.string "Oye, hola, ¿no eres {PLAYER}?\n"
	.string "¿Qué debería hacer? ¿Hablar contigo?\l"
	.string "¿Por qué no? ¡Ya estoy hablando\l"
	.string "contigo!\p"
	.string "{PLAYER}, ¿estás sorprendido de mí?\n"
	.string "Será mejor que te diga quién soy.\p"
	.string "¡{STR_VAR_1} es como puedes llamarme.\n"
	.string "La estrella más brillante del\l"
	.string "reino de la guitarra, ¡ese soy yo!\p"
	.string "¿Me recibes?\n"
	.string "¡Me recibes!\p"
	.string "Mi suerte está en su mejor momento,\n"
	.string "¡te golpearé con una petición!\p"
	.string "¡{PLAYER}, déjame ser tu subordinado!\n"
	.string "¡Quiero que me enseñes todo!$"

gText_ApprenticeRejectTeaching12::
	.string "¿Me estás rechazando, entonces?\n"
	.string "¡Tendré que preguntarte otra vez!\p"
	.string "{PLAYER}, te suplico ser tu subordinado.\n"
	.string "¡Necesito que me enseñes todo!$"

gText_ApprenticeWhichLevelMode12::
	.string "¡Suerte, sí, woohoo!\n"
	.string "¿Debería hacerte una pregunta?\p"
	.string "Ya que estamos cerca de la TORRE\n"
	.string "BATALLA, ¿qué tal una pregunta\l"
	.string "sobre su poder?\p"
	.string "De las opciones que ves,\n"
	.string "¿cuál es la correcta para mí?$"

gText_ApprenticeLevelModeThanks12::
	.string "Si {STR_VAR_1} es lo que sugieres,\n"
	.string "¡debe ser lo mejor!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos otra vez, mi amigo listo!$"

gText_ApprenticePleaseTeach13::
	.string "¡Oh, hola! ¡Tú!\n"
	.string "¿Puedes darme un masaje en el hombro?\p"
	.string "…¡Sí, ahí! ¡Eso es!\n"
	.string "¡Ay, ay! ¡Ooh, eso se siente genial!\p"
	.string "Me llamo {STR_VAR_1}.\n"
	.string "Entreno karate, pero mi cuerpo no\l"
	.string "está hecho para soportar el abuso…\p"
	.string "Decidí que combatiré con POKéMON y\n"
	.string "me endureceré.\p"
	.string "¿Eres {PLAYER}{KUN}, verdad?\n"
	.string "¿El CAMPEÓN de la LIGA POKéMON?\p"
	.string "Escucha, ¿puedes darme\n"
	.string "consejos?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, ¿por qué?\p"
	.string "¡No seré una gran molestia, lo prometo!\n"
	.string "¿Por favor?$"

gText_ApprenticeWhichLevelMode13::
	.string "Gracias. ¡Muy amable de tu parte!\n"
	.string "…¡Cof! ¡Cof!\p"
	.string "Oogh, tengo que endurecerme rápido…\p"
	.string "Me dirigiré a la TORRE BATALLA en\n"
	.string "seguida, pero ¿qué sería mejor para\l"
	.string "mí? ¿Nivel 50 o Nivel Libre?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, vale. Eso es {STR_VAR_1}.\n"
	.string "Iré allí enseguida.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedir ayuda, ¡después de todo,\l"
	.string "eres mi mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me estás poniendo muy nervioso.\p"
	.string "Soy… Soy {STR_VAR_1}.\p"
	.string "Me da mucha vergüenza decir esto,\n"
	.string "pero exploro ruinas antiguas y cosas\l"
	.string "así.\p"
	.string "Me da aún más vergüenza admitir que\n"
	.string "estoy interesado en el FRENTE BATALLA.\p"
	.string "{PLAYER}{KUN}, tienes fama de ser un\n"
	.string "ENTRENADOR duro…\p"
	.string "Me cuesta decir esto, pero quiero\n"
	.string "preguntar algo.\p"
	.string "¿Podrías convertirte en mi maestro y\n"
	.string "darme consejos?$"

gText_ApprenticeRejectTeaching14::
	.string "¡Por favor, no me despidas así!\n"
	.string "No puedo vivir con la humillación.\p"
	.string "¡Por favor, conviértete en mi maestro!\n"
	.string "¡Necesito tu consejo!$"

gText_ApprenticeWhichLevelMode14::
	.string "G-gracias…\p"
	.string "Pero por favor no me mires así.\n"
	.string "Me pone muy nervioso.\p"
	.string "Por favor, respóndeme sin mirarme\n"
	.string "a los ojos.\p"
	.string "En la TORRE BATALLA…\n"
	.string "¿Qué nivel debería intentar?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Lo intentaré.\p"
	.string "Espero poder hacer un reto valiente\n"
	.string "sin ponerme nervioso…\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos encontramos otra vez, espero\l"
	.string "que seas igual de útil.$"

gText_ApprenticePleaseTeach15::
	.string "¿Hm? Pareces ser {PLAYER}{KUN}…\n"
	.string "Pero ¿eres realmente real?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "He estado jugando con la idea de\l"
	.string "aprender bajo un ENTRENADOR fuerte.\p"
	.string "Así que debo decir que tengo suerte\n"
	.string "de que hayas aparecido.\l"
	.string "…¿De verdad eres {PLAYER}{KUN}, sí?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "Solo quiero que me reconozcas como\l"
	.string "tu aprendiz.$"

gText_ApprenticeRejectTeaching15::
	.string "¿Oh?\n"
	.string "Pero ¿qué te impulsaría a rechazar?\p"
	.string "Me disculpo por ser escéptico sobre\n"
	.string "tu identidad.\p"
	.string "Por favor, acepta mi disculpa y\n"
	.string "aceptame como tu aprendiz.$"

gText_ApprenticeWhichLevelMode15::
	.string "¿De verdad me estás aceptando?\n"
	.string "No deseo celebrar prematuramente.\p"
	.string "Si es cierto, lo siento.\n"
	.string "Pero ahora, necesito tu consejo.\p"
	.string "Si fuera a entrar en la TORRE BATALLA,\n"
	.string "¿qué sería digno de mí?\l"
	.string "¿Nivel 50 o Nivel Libre?$"

gText_ApprenticeLevelModeThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Me doy cuenta de que puedo ser\n"
	.string "molesto, pero me encanta que me\l"
	.string "hayas aceptado.\p"
	.string "¡Nos vemos otra vez!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sigh… Snif…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Estoy todo enredado en un dilema\n"
	.string "que no puedo decidir.\p"
	.string "No puedo decidir qué debería hacer\n"
	.string "que mi {STR_VAR_1} lleve.\p"
	.string "Por favor, dime, {PLAYER}.\n"
	.string "¿Qué objeto debería hacer que lleve?$"

gText_ApprenticeHoldNothing0::
	.string "¿Oh, de verdad? ¿No debería hacer\n"
	.string "que mi {STR_VAR_1} lleve nada?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "¡Oh, vale! ¡Estoy encantado de que\n"
	.string "se haya resuelto!\l"
	.string "¡Increíble! ¡Genial! ¡Awoooh!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, estoy tan contento…\n"
	.string "Creo que también tengo ese {STR_VAR_1}.\p"
	.string "¡Estoy encantado de que se haya\n"
	.string "resuelto!\l"
	.string "¡Increíble! ¡Genial! ¡Awoooh!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "¡Waaaah! ¡Por favor, no seas malo!\p"
	.string "Ese objeto {STR_VAR_1} ya me lo\n"
	.string "habían recomendado antes, sollozo…\p"
	.string "¿O quieres decir que no debería hacer\n"
	.string "que mi {STR_VAR_2} lleve nada?$"

gText_ApprenticeWhatHeldItem1::
	.string "¡Yay! ¡Es {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "¿Haces que tus POKéMON lleven objetos?\n"
	.string "Yo quiero que los míos lleven, pero…\p"
	.string "¿Qué objeto sería bueno para que\n"
	.string "{STR_VAR_1} lo lleve?\p"
	.string "¿Qué piensas?$"

gText_ApprenticeHoldNothing1::
	.string "¿Eh? ¿Quieres decir que mi {STR_VAR_1}\n"
	.string "no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "¡Oh, ya entiendo! ¡Lo haré!\n"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeThanksHeldItem1::
	.string "¡Oh, vaya! Un {STR_VAR_1}, ¿eh?\n"
	.string "Vale, ¡lo haré!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, uh, no, eso no es lo que quería\n"
	.string "decir. Quiero saber sobre un objeto\l"
	.string "diferente de los que ya conozco.\p"
	.string "¿O quieres decir que mi POKéMON no\n"
	.string "tiene que llevar nada esta vez?$"

gText_ApprenticeWhatHeldItem2::
	.string "¡{PLAYER}, hola!\n"
	.string "Es sobre mi {STR_VAR_1}…\p"
	.string "Quiero hacer que lleve un buen objeto.\n"
	.string "¿Qué sería bueno para él?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, entonces mi {STR_VAR_1} no tiene\n"
	.string "que llevar nada?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "¡Vale, lo tengo!\n"
	.string "¡Nos vemos otra vez!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, ¿el objeto {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "¡Haré todo lo posible por encontrar uno!\n"
	.string "¡Nos vemos otra vez!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Alguien ya me habló sobre\n"
	.string "el {STR_VAR_1}.\p"
	.string "Quiero que mi POKéMON lleve un objeto\n"
	.string "diferente.\p"
	.string "¿O crees que {STR_VAR_2} no tiene que\n"
	.string "llevar nada?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hola, {PLAYER}…\n"
	.string "Perdona que te moleste otra vez, pero\l"
	.string "tengo algo más que quería preguntarte.\p"
	.string "No creo que sea lo suficientemente\n"
	.string "bueno para ganar combates por mi cuenta,\l"
	.string "así que estoy pensando en hacer que mi\l"
	.string "{STR_VAR_1} lleve un objeto.\p"
	.string "Pero no sé qué sería bueno.\p"
	.string "{PLAYER}, por favor, ¿podrías decidir\n"
	.string "por mí?$"

gText_ApprenticeHoldNothing3::
	.string "¿Un POKéMON que pertenece a alguien\n"
	.string "como yo estaría mejor sin un objeto?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Entiendo…\n"
	.string "Dices que no debería depender de\l"
	.string "objetos.\l"
	.string "¡Haré lo mejor que pueda para no hacerlo!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeThanksHeldItem3::
	.string "El objeto {STR_VAR_1}, vale.\n"
	.string "No estoy seguro de si puedo conseguir\l"
	.string "uno…\l"
	.string "¡No! Haré lo mejor que pueda para\l"
	.string "conseguirlo.\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, pero…\n"
	.string "Creo que ya he oído hablar de eso…\p"
	.string "¿Será porque no he manejado bien\n"
	.string "el objeto {STR_VAR_1}?\p"
	.string "¿O quieres decir que no debería hacer\n"
	.string "que mi {STR_VAR_2} lleve nada?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que quería preguntarte.\p"
	.string "¿Sabes cómo decidiste qué POKéMON\n"
	.string "debería tener para mí?\p"
	.string "Pero nunca te pregunté qué objeto\n"
	.string "debería llevar.\p"
	.string "Ya que me diste consejos,\n"
	.string "¿qué tal si lo llevas hasta el final?\p"
	.string "¿Qué sería bueno? Quiero hacer que\n"
	.string "mi {STR_VAR_1} lleve algo.$"

gText_ApprenticeHoldNothing4::
	.string "¡Oh! ¿Así que mi {STR_VAR_1} debería\n"
	.string "hacer lo mejor que pueda con las manos\l"
	.string "vacías?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Si crees que es lo mejor, lo haré.\p"
	.string "Sabiendo que tú has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem4::
	.string "¿El objeto {STR_VAR_1}, eh?\n"
	.string "No está mal. ¡Lo usaré!\p"
	.string "Sabiendo que tú has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "¿Eh? ¿Qué dices?\n"
	.string "Ya me hablaste del {STR_VAR_1}\l"
	.string "antes.\p"
	.string "¿O quieres decir que mi {STR_VAR_2}\n"
	.string "debería hacer lo mejor que pueda con\l"
	.string "las manos vacías?$"

gText_ApprenticeWhatHeldItem5::
	.string "¡Eh, {PLAYER}{KUN}!\p"
	.string "Los dos estamos ocupados, pero parece\n"
	.string "que nos encontramos a menudo de todos\l"
	.string "modos.\p"
	.string "Hoy tengo que caminar, limpiar y\n"
	.string "cepillarme.\p"
	.string "Ni siquiera he tenido tiempo de comprar\n"
	.string "nada para mi querido {STR_VAR_1}.\p"
	.string "No tengo tiempo, así que ¿qué tal si\n"
	.string "me das consejos sobre qué debería hacer\l"
	.string "que mi {STR_VAR_1} lleve?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, así que siendo un tipo ocupado,\n"
	.string "¿dices que mi {STR_VAR_1} no necesita\l"
	.string "nada?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Vale, entendido.\n"
	.string "No necesitaré tiempo para eso.\p"
	.string "¡Gracias hoy!\n"
	.string "¡Nos vemos!$"

gText_ApprenticeThanksHeldItem5::
	.string "Vale, entendido.\n"
	.string "Encontraré tiempo de alguna forma y\l"
	.string "encontraré ese {STR_VAR_1} que\l"
	.string "recomendaste.\p"
	.string "Me alegro de haber encontrado un buen\n"
	.string "mentor en ti.\l"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "¿Eh? Ya sé sobre\n"
	.string "ese {STR_VAR_1}.\p"
	.string "Oh, claro, ya entiendo.\n"
	.string "Así que siendo un tipo ocupado, dices\l"
	.string "que mi {STR_VAR_2} no necesita nada?$"

gText_ApprenticeWhatHeldItem6::
	.string "¡Hiya, {PLAYER}! ¡Soy yo!\n"
	.string "Necesito consultar tu mente otra vez\l"
	.string "hoy. ¡Por favor, necesito tu consejo!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La pregunta que tengo es…\p"
	.string "Si quiero hacer que mi {STR_VAR_1} lleve\n"
	.string "un objeto, ¿qué debería ser?$"

gText_ApprenticeHoldNothing6::
	.string "¿Es verdad? ¿Mi {STR_VAR_1} no necesita\n"
	.string "llevar un objeto, dices?$"

gText_ApprenticeThanksNoHeldItem6::
	.string "¡Vale, eso es lo que haré!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeThanksHeldItem6::
	.string "¡Uh-huh! Un {STR_VAR_1}.\n"
	.string "¡Qué elección tan genial!\l"
	.string "¡Definitivamente lo intentaré!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Nos vemos aquí otra vez, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "¡Ajajaja! ¡Qué tonto!\n"
	.string "¡Ya me hablaste de ese {STR_VAR_1}\l"
	.string "antes!\p"
	.string "¿Te sientes bien, {PLAYER}?\p"
	.string "Oh, ¡espera! ¿Mi {STR_VAR_2} no necesita\n"
	.string "llevar un objeto, dices?$"

gText_ApprenticeWhatHeldItem7::
	.string "Hola, {PLAYER}. Espero que hayas\n"
	.string "estado bien.\p"
	.string "¿Puedo acudir a ti para pedirte\n"
	.string "consejo?\p"
	.string "En un combate reciente, mi oponente\n"
	.string "parecía haberle dado a su POKéMON un\l"
	.string "objeto para que lo llevara.\p"
	.string "Como resultado, fui derrotado…\p"
	.string "No quiero quedarme atrás.\n"
	.string "Me gustaría hacer que mi {STR_VAR_1}\l"
	.string "también lleve un objeto.\p"
	.string "Me complacería que pudieras decidir\n"
	.string "qué sería adecuado para mi POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "En otras palabras… ¿Mi POKéMON no\n"
	.string "tiene necesidad de llevar un objeto?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "¡Entiendo claramente ahora!\n"
	.string "Seguiré intentándolo así.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "¡Cuídate!$"

gText_ApprenticeThanksHeldItem7::
	.string "¡Un {STR_VAR_1}!\n"
	.string "Lo pediré enseguida.\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo otra vez.\l"
	.string "¡Cuídate!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Ya me hablaste de eso,\n"
	.string "y ya lo tengo.\p"
	.string "¿O estás diciendo… que mi POKéMON no\n"
	.string "tiene necesidad de llevar un objeto?$"

gText_ApprenticeWhatHeldItem8::
	.string "¡Eek! ¡{PLAYER}!\n"
	.string "¡Estoy… Estoy eufórico de verte otra\l"
	.string "vez!\p"
	.string "¡Oh-oh-oh! Hay algo que simplemente\n"
	.string "tenía que preguntarte, {PLAYER}!\p"
	.string "¡Por favor, decide qué debería llevar\n"
	.string "mi {STR_VAR_1}!$"

gText_ApprenticeHoldNothing8::
	.string "¡Oh, vaya! ¡No esperaba esa respuesta!\n"
	.string "¿Así que un objeto para llevar no es\l"
	.string "necesario?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "¡Perfectamente entendido!\n"
	.string "¡Seguiré adelante sin un objeto!\p"
	.string "Espero que estés dispuesto a enseñarme\n"
	.string "algo más en otra ocasión.$"

gText_ApprenticeThanksHeldItem8::
	.string "¡{STR_VAR_1}! ¡Usaré eso!\p"
	.string "Ejem… ¿Podría ser, {PLAYER}, que tú\n"
	.string "también hagas que tus POKéMON lleven\l"
	.string "ese objeto?\p"
	.string "¡Me aseguraré de conseguirlo!\n"
	.string "Espero que estés dispuesto a enseñarme\l"
	.string "algo más en otra ocasión.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "¿Oh? También recomendaste ese\n"
	.string "{STR_VAR_1} antes.\p"
	.string "¿O es lo mejor para llevar?\n"
	.string "¿O quieres decir que mi {STR_VAR_2}\l"
	.string "no necesita nada para llevar?$"

gText_ApprenticeWhatHeldItem9::
	.string "¡Hola!\n"
	.string "¡Mi maestro, {PLAYER}{KUN}!\p"
	.string "Quiero pedirte consejo sobre\n"
	.string "herramientas POKéMON.\p"
	.string "¿Qué crees que sería bueno para que\n"
	.string "mi {STR_VAR_1} lo lleve?\p"
	.string "No seas tímido ahora.\n"
	.string "¡Vamos, suéltalo!$"

gText_ApprenticeHoldNothing9::
	.string "¿Oh? ¿Así que dices que mi {STR_VAR_1}\n"
	.string "puede ganar sin llevar ningún objeto?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "¡Sí, bueno!\n"
	.string "¡Lo daré todo, como, slam!\p"
	.string "Muy bien, ¡gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, ¿eso es un {STR_VAR_1}?\n"
	.string "¡Sí, bueno!\l"
	.string "¡Iré a buscar uno, como, bam!\p"
	.string "Muy bien, ¡gracias, como siempre!\n"
	.string "¡Adiós!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no. Ya me hablaste de esa cosa\n"
	.string "del {STR_VAR_1} antes.\p"
	.string "Oh, espera un minuto…\n"
	.string "¿Así que dices que mi {STR_VAR_2} puede\l"
	.string "ganar sin llevar ningún objeto?$"

gText_ApprenticeWhatHeldItem10::
	.string "¡{PLAYER}{KUN}, ha pasado algo increíble!\p"
	.string "¡Me desperté esta mañana, y mi POKéMON\n"
	.string "tenía 10 PEPITAS!\p"
	.string "¡Por supuesto que estoy mintiendo!\n"
	.string "¡Wahahaha!\p"
	.string "Esto no es mentira, sin embargo.\n"
	.string "No soy muy bueno pensando en qué\l"
	.string "objetos deberían llevar los POKéMON.\p"
	.string "Así que, ¿qué tal si decides por mí qué\n"
	.string "debería hacer que mi {STR_VAR_1} lleve,\l"
	.string "maestro?$"

gText_ApprenticeHoldNothing10::
	.string "¿Qué significa eso?\n"
	.string "¿Que no lleve nada?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Vale, así que no debe llevar nada.\n"
	.string "Entonces, ¡mejor consigo algo para él!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeThanksHeldItem10::
	.string "Vale, así que es un {STR_VAR_1}.\n"
	.string "¡Haré que lleve cualquier cosa menos\l"
	.string "eso!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Ejem, ya me hablaste de eso antes,\n"
	.string "¿verdad?\p"
	.string "¿No hay algo más?\p"
	.string "¿O quieres decir que no haga que\n"
	.string "mi {STR_VAR_2} lleve nada?$"

gText_ApprenticeWhatHeldItem11::
	.string "¡A-H-O-Y!\n"
	.string "¡Eso deletrea ahoy!\p"
	.string "¡El MARINERO rapero soy yo!\n"
	.string "¡Te presento una pregunta\l"
	.string "que es bastante genial!\p"
	.string "¡Es una pregunta de objetos\n"
	.string "que suplica tu sugerencia!\p"
	.string "Mi {STR_VAR_1} necesita un objeto que\n"
	.string "llevar, ¿qué debería ser, si me lo\l"
	.string "preguntas?$"

gText_ApprenticeHoldNothing11::
	.string "¿Es verdad?\n"
	.string "¿Mi {STR_VAR_1} no necesita llevar\l"
	.string "nada apretado?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "¡Vale, te escucho, seguro que sí!\n"
	.string "¡Mi POKéMON irá con las manos vacías,\l"
	.string "eso haré yo!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu palabra!$"

gText_ApprenticeThanksHeldItem11::
	.string "Vale, un {STR_VAR_1},\n"
	.string "eso es lo que usaré.\l"
	.string "¡Tenía razón al hacerte elegir!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu palabra!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Vale, un {STR_VAR_1}, dices.\n"
	.string "Ya me dijiste eso el otro día.\l"
	.string "Necesito una idea nueva, una forma\l"
	.string "completamente nueva.\p"
	.string "¿O qué, es verdad?\n"
	.string "¿Mi POKéMON no necesita llevar nada\l"
	.string "apretado?$"

gText_ApprenticeWhatHeldItem12::
	.string "¡Oye, hola, {PLAYER}!\n"
	.string "¡Te he encontrado otra vez hoy!\p"
	.string "¿Qué debería hacer? ¿Pedirte consejo?\n"
	.string "¿Por qué no? ¡Ya estoy hablando contigo!\p"
	.string "{PLAYER}, ¿estás harto de mí?\n"
	.string "Nah, de ninguna manera, eso no puede ser.\p"
	.string "¿Me escucharás?\n"
	.string "Busco consejo, eso es lo que\l"
	.string "estoy diciendo.\p"
	.string "Es sobre un objeto para llevar para\n"
	.string "mi {STR_VAR_1} que sería bueno.\l"
	.string "Mi indecisión me está haciendo\l"
	.string "deprimirme.$"

gText_ApprenticeHoldNothing12::
	.string "¿Mi {STR_VAR_1} no necesita nada?\n"
	.string "¿No necesita llevar nada?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Si no llevar nada es lo mejor,\n"
	.string "¡haré lo que sugieres!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos otra vez, mi amigo listo!$"

gText_ApprenticeThanksHeldItem12::
	.string "Si llevar ese {STR_VAR_1} es\n"
	.string "lo mejor, ¡haré lo que sugieres!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos otra vez, mi amigo listo!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "¿No he oído hablar de ese\n"
	.string "{STR_VAR_1} antes?\l"
	.string "Estoy seguro de que sí, ¡eso es seguro!\p"
	.string "¡Necesito algo nuevo!\n"
	.string "¿O mi {STR_VAR_2} no necesita nada?\l"
	.string "¿No necesita llevar nada?$"

gText_ApprenticeWhatHeldItem13::
	.string "¡Gwah! ¡Ay! {PLAYER}{KUN}, ¡se me ha\n"
	.string "roto el brazo!\n"
	.string "¡No lo toques, por favor!\p"
	.string "Debe habérmelo roto mientras probaba\n"
	.string "diferentes objetos para llevar con mi\l"
	.string "grupo de POKéMON.\p"
	.string "Así que, dadas las circunstancias,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, ¿qué crees que sería bueno\n"
	.string "para que mi {STR_VAR_1} lo lleve?$"

gText_ApprenticeHoldNothing13::
	.string "Ay…\p"
	.string "¿Así que tu sugerencia es que mi\n"
	.string "{STR_VAR_1} no tiene que llevar nada?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, vale. Eso sería más fácil\n"
	.string "para mí, dadas las circunstancias.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedir ayuda así.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, vale. Eso es un {STR_VAR_1}.\n"
	.string "El brazo de mi POKéMON está bien, así\l"
	.string "que le haré llevar ese objeto enseguida.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedir ayuda así.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, ya me hablaste de ese\n"
	.string "{STR_VAR_1} antes, ¿recuerdas?\p"
	.string "¿Qué tal si me dices algo\n"
	.string "aún mejor?\p"
	.string "Oh, espera un segundo.\n"
	.string "¿Así que tu sugerencia es que mi\l"
	.string "{STR_VAR_2} no tiene que llevar nada?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Por favor, no me mires así.\n"
	.string "Mis POKéMON no tienen nada.\p"
	.string "Me… Me da mucha vergüenza decir esto,\n"
	.string "pero realmente necesito tu consejo.\p"
	.string "No puedo decidir qué objeto para llevar\n"
	.string "haría fuerte a mi {STR_VAR_1}.\p"
	.string "{PLAYER}{KUN}, ¿qué crees que sería\n"
	.string "bueno?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Entonces, ¿crees que sería mejor\n"
	.string "si mi {STR_VAR_1} no tuviera un objeto?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… ¡Vale!\n"
	.string "Iré sin un objeto.\p"
	.string "Esto es estresante, sin embargo.\n"
	.string "¿No sería demasiado genial?\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos encontramos otra vez, espero\l"
	.string "que seas igual de útil.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… ¡Vale!\n"
	.string "Iré con ese {STR_VAR_1}.\p"
	.string "Esto es estresante, sin embargo.\n"
	.string "¿No sería demasiado genial?\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos encontramos otra vez, espero\l"
	.string "que seas igual de útil.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "P-pero ya escuché sobre eso.\p"
	.string "¡Por favor, no me despidas así!\n"
	.string "No puedo vivir con la humillación.\p"
	.string "Oh… ¿Estoy sacando conclusiones\n"
	.string "precipitadas?\l"
	.string "¿Crees que sería mejor si mi\l"
	.string "{STR_VAR_2} no tuviera un objeto?$"
	
gText_ApprenticeWhatHeldItem15::
	.string "¿Mmm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero de verdad eres tú?\l"
	.string "¿Quizás eres un gemelo?\p"
	.string "¡Oh, no, no, no, no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor\l"
	.string "olvida mi descortesía.\p"
	.string "Lo que me gustaría es un poco más de\n"
	.string "tu excelente consejo.\p"
	.string "Tengo aquí a mi {STR_VAR_1} al que deseo\n"
	.string "hacer llevar un objeto conveniente.\p"
	.string "¿Qué sería digno de él?$"

gText_ApprenticeHoldNothing15::
	.string "¿Es mejor que no lleve nada?\n"
	.string "¿Estás seguro?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "¡Nos vemos de nuevo!$"

gText_ApprenticeThanksHeldItem15::
	.string "¿Un {STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que mi POKéMON sea capaz de\n"
	.string "sacarle buen provecho.\p"
	.string "¡Nos vemos de nuevo!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, espera un momento.\n"
	.string "Creo que ya me enseñaste eso antes.\p"
	.string "Me gustaría que me recomendaras\n"
	.string "algo diferente esta vez.\p"
	.string "¿Quizás estás sugiriendo que\n"
	.string "mi {STR_VAR_2} no debería llevar nada?\l"
	.string "¿Estás seguro?$"

gText_ApprenticeWhichMonFirst0::
	.string "¡Buaaa, {PLAYER}!\n"
	.string "Tengo un dilema, sniff…\p"
	.string "Quiero empezar a luchar contra otra\n"
	.string "gente, pero no sé qué hacer.\p"
	.string "¿Cómo debería alinear mis POKéMON\n"
	.string "para que estén en su mejor forma?\p"
	.string "Por favor, dime, {PLAYER}.\n"
	.string "Si fueras yo, ¿cuál de estos POKéMON\l"
	.string "enviarías primero?$"

gText_ApprenticeMonFirstThanks0::
	.string "¿¿Mi {STR_VAR_1} debería ir primero?\n"
	.string "¡Buaaaaah!\p"
	.string "¡Oh! ¡Lo siento mucho!\n"
	.string "Me has hecho tan feliz al elegir\l"
	.string "mi primer POKéMON, que me he puesto\l"
	.string "a llorar…\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeWhichMonFirst1::
	.string "¡Yupi! ¡Es {PLAYER}!\n"
	.string "¡Genial! ¡Quería preguntarte algo!\p"
	.string "Um, de mis POKéMON, ¿cuál crees\n"
	.string "que debería salir primero?$"

gText_ApprenticeMonFirstThanks1::
	.string "¿Mi {STR_VAR_1}? Es verdad.\n"
	.string "Vale, ¡lo haré!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMonFirst2::
	.string "¡Hola, {PLAYER}!\p"
	.string "Creo que, en un combate, es muy\n"
	.string "importante qué POKéMON salga primero.\p"
	.string "De los POKéMON que tengo,\n"
	.string "¿cuál sería bueno enviar primero?$"

gText_ApprenticeMonFirstThanks2::
	.string "¿Mi {STR_VAR_1} va primero?\n"
	.string "¡Vale, lo tengo!\p"
	.string "¡Hasta otra!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte de nuevo con\l"
	.string "otra pregunta.\p"
	.string "Tengo tan poca confianza, que no\n"
	.string "sé qué haría sin ti, {PLAYER}.\p"
	.string "Puede que sea una pérdida de tiempo\n"
	.string "que incluso me preocupe por ello, pero\l"
	.string "no puedo decidir algo…\p"
	.string "¿Cuál de mis POKéMON debería enviar\n"
	.string "primero en un combate?$"

gText_ApprenticeMonFirstThanks3::
	.string "¿Mi {STR_VAR_1}?\n"
	.string "¡Entendido!\p"
	.string "No puedo creer que te molestes en\n"
	.string "responder mis preguntas tan a menudo.\p"
	.string "Estoy tan agradecido de que incluso\n"
	.string "hables conmigo… ¡Gracias!$"

gText_ApprenticeWhichMonFirst4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Soy yo!\n"
	.string "Me alegro tanto de verte porque tengo\l"
	.string "este pequeño problema.\p"
	.string "No puedo decidir cómo deberían\n"
	.string "alinearse mis POKéMON. ¿Podrías\l"
	.string "decidir por mí?\p"
	.string "Oh, no necesitas decidir todo el\n"
	.string "equipo ahora mismo.\p"
	.string "¿Qué tal si decides solo el primer\n"
	.string "POKéMON por mí?$"

gText_ApprenticeMonFirstThanks4::
	.string "¿Mi {STR_VAR_1}? ¡Eso es genial!\p"
	.string "Sabiendo que has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst5::
	.string "¡Hola, mi maestro {PLAYER}{KUN}!\n"
	.string "¡Estoy ocupado otra vez hoy!\p"
	.string "Tengo que hacer ciclismo, ir de compras\n"
	.string "y tararear.\p"
	.string "Ni siquiera he tenido tiempo de decidir\n"
	.string "cómo alinear mi equipo POKéMON.\p"
	.string "Así que, ¿qué tal si revisas mi equipo?\n"
	.string "¿Cuál debería ir primero?$"

gText_ApprenticeMonFirstThanks5::
	.string "Vale, entendido.\n"
	.string "Tengo tiempo suficiente al menos para\l"
	.string "poner a mi {STR_VAR_1} al frente.\p"
	.string "¡Ups, mi novia me está esperando!\n"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMonFirst6::
	.string "¡Yoohoo! ¡Hola, {PLAYER}!\n"
	.string "¡Siempre andas por ahí con pinta de\l"
	.string "ser duro!\p"
	.string "Escucha, necesito algo de ti\n"
	.string "otra vez. ¡Es lo de siempre!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La pregunta que tengo es sobre mi\l"
	.string "equipo.\p"
	.string "¿Cuál de mis POKéMON debería salir\n"
	.string "primero en un combate?$"

gText_ApprenticeMonFirstThanks6::
	.string "¡Hmhm!\n"
	.string "¿Mi {STR_VAR_1}, dices?\l"
	.string "¡Gracias por una respuesta tan guay!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Encontremos aquí de nuevo, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMonFirst7::
	.string "Muchas gracias por detenerte a\n"
	.string "charlar conmigo, {PLAYER}.\p"
	.string "Sé que estoy abusando de tu\n"
	.string "amabilidad, pero ¿puedo pedirte un\l"
	.string "consejo?\p"
	.string "Me gustaría que decidieras el orden\n"
	.string "de mi equipo POKéMON.\p"
	.string "Me complacería que pudieras decidir\n"
	.string "qué POKéMON debería salir primero.$"

gText_ApprenticeMonFirstThanks7::
	.string "¡Mi {STR_VAR_1} es!\n"
	.string "¡Lo pondré primero enseguida!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo de nuevo.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMonFirst8::
	.string "¡Eek! ¡{PLAYER}!\n"
	.string "¡Estoy… estoy encantado de verte\l"
	.string "de nuevo!\p"
	.string "¡Mis POKéMON se han vuelto mucho\n"
	.string "más fuertes!\p"
	.string "Pero no siempre gano. Parece que\n"
	.string "depende de qué POKéMON salga primero.\p"
	.string "¡{PLAYER}, por favor, necesito tu ayuda!\p"
	.string "¡Por favor, decide cuál de mis POKéMON\n"
	.string "debería salir primero!$"

gText_ApprenticeMonFirstThanks8::
	.string "Suspiro… Estoy abrumado de felicidad…\p"
	.string "Es como un sueño que decidas\n"
	.string "por mí, {PLAYER}.\p"
	.string "¡Pero perfectamente entendido!\n"
	.string "¡Iré con mi {STR_VAR_1} primero!\p"
	.string "Espero que estés dispuesto a enseñarme\n"
	.string "algo más en otro momento.$"

gText_ApprenticeWhichMonFirst9::
	.string "¡Hola, hola!\n"
	.string "¡Mi mentor, {PLAYER}{KUN}!\l"
	.string "¡Dame tu sabio consejo hoy!\p"
	.string "Verás, he reunido un equipo de\n"
	.string "tres POKéMON. Hasta ahí bien.\p"
	.string "Pero el orden de combate del equipo\n"
	.string "aún no está decidido.\p"
	.string "¡Aquí es donde entras tú, {PLAYER}{KUN}!\n"
	.string "¡Tú decides qué POKéMON lidera!\p"
	.string "No seas tímido ahora.\n"
	.string "¡Suéltalo!$"

gText_ApprenticeMonFirstThanks9::
	.string "Ajá, ¡mi {STR_VAR_1} lidera!\n"
	.string "¡OK, A-OK!\l"
	.string "Reordenaré la alineación, ¡como, pam!\p"
	.string "Muy bien, gracias, como siempre.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMonFirst10::
	.string "¡{PLAYER}{KUN}, escucha!\n"
	.string "¡Es una crisis!\p"
	.string "¡Mis POKéMON, los tres, entran en\n"
	.string "combate a la vez!\p"
	.string "¡Por supuesto que eso es imposible!\n"
	.string "¡Wahahaha!\p"
	.string "Eso no es mentira, sin embargo.\n"
	.string "No soy muy bueno pensando en\l"
	.string "cómo debería alinear mis POKéMON.\p"
	.string "Así que, ¿qué tal si decides por mí\n"
	.string "cuál POKéMON debería ir primero,\l"
	.string "maestro?$"

gText_ApprenticeMonFirstThanks10::
	.string "¿Vale, así que elegiste mi {STR_VAR_1}?\n"
	.string "¡Dejaré que cualquier otro vaya primero!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMonFirst11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso deletrea ahoy!\p"
	.string "¡El MARINERO rapero soy yo!\n"
	.string "Te presento una pregunta\l"
	.string "¡que es bastante guay!\p"
	.string "¡Es una pregunta de alineación\n"
	.string "que pide tu sugerencia!\p"
	.string "¿De este grupo, cuál debería salir\n"
	.string "primero como el primero en el lugar?$"

gText_ApprenticeMonFirstThanks11::
	.string "¡Vale, te escucho, seguro que sí!\n"
	.string "¡Los cambiaré, eso haré!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu voz!$"

gText_ApprenticeWhichMonFirst12::
	.string "¡Yahoo, {PLAYER}!\n"
	.string "¿Cómo estás?\p"
	.string "¿Qué debería hacer? ¿Preguntar?\n"
	.string "¡Uh-huh, tengo algo que preguntar!\l"
	.string "¿Me recibes?\l"
	.string "¡Me recibes!\p"
	.string "Tienes que decidir, ¿cuál de mis\n"
	.string "POKéMON es el primero en montar.\l"
	.string "En combate, quiero decir.$"

gText_ApprenticeMonFirstThanks12::
	.string "¿Mi {STR_VAR_1}? ¡Sí!\n"
	.string "¡Eso servirá, no hay problema!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos de nuevo, mi amigo listo!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Uf… ay… {PLAYER}{KUN}…\n"
	.string "Me duele la barriga de repente…\p"
	.string "…Está mejorando ahora…\p"
	.string "Debe haberme preocupado enfermar\n"
	.string "devanándome los sesos sobre cómo\l"
	.string "debería alinear mi pandilla de POKéMON.\p"
	.string "Así que, dadas las circunstancias,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, ¿cuál de mis POKéMON debería\n"
	.string "salir primero? Para ganar, quiero decir.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, muy bien.\n"
	.string "Mi {STR_VAR_1} va primero.\p"
	.string "Arreglaré la alineación así después\n"
	.string "de cenar.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedirte ayuda así.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "¿{PLAYER}{KUN}?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me estás poniendo nervioso.\p"
	.string "Um…\n"
	.string "Realmente necesito tu consejo.\p"
	.string "Me da vergüenza decir esto,\n"
	.string "pero elegí mi equipo de 3 POKéMON.\l"
	.string "Sin embargo, no puedo decidir el orden.\p"
	.string "¿Qué POKéMON debería enviar primero\n"
	.string "para que al menos parezca capaz?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Lideraré con mi {STR_VAR_1}.\p"
	.string "Espero poder hacerlo lo mejor posible\n"
	.string "sin ponerme nervioso.\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos volvemos a ver, espero que seas\l"
	.string "tan útil.$"

gText_ApprenticeWhichMonFirst15::
	.string "¿Mmm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero de verdad eres tú?\l"
	.string "¿Quizás eres un imitador listo?\p"
	.string "Oh, no, no, no, ¡no te preocupes!\n"
	.string "Si de verdad eres {PLAYER}, por favor\l"
	.string "olvida mi descortesía.\p"
	.string "Lo que me gustaría es tu excelente\n"
	.string "consejo.\p"
	.string "Tengo aquí mi equipo POKéMON.\n"
	.string "Me gustaría que me dijeras cuál\l"
	.string "debería salir primero en un combate.$"

gText_ApprenticeMonFirstThanks15::
	.string "¿Mi {STR_VAR_1}…\n"
	.string "No me estarás tomando el pelo?\p"
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Soy como me ves, pero haré\n"
	.string "lo mejor que pueda.\p"
	.string "¡Nos vemos de nuevo!$"

gText_ApprenticeWhichMon0::
	.string "Sniff…\n"
	.string "Oh, ¡{PLAYER}!\p"
	.string "¡Qué momento más oportuno!\n"
	.string "Hay algo que simplemente no puedo\l"
	.string "decidir…\p"
	.string "No puedo decidir qué POKéMON debería\n"
	.string "usar.\p"
	.string "No puedo decidirme entre el POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}…\p"
	.string "{PLAYER}, ¿cuál crees que me daría\n"
	.string "incluso a mí una oportunidad de ganar?$"

gText_ApprenticeMonThanks0::
	.string "Sniff… Yo… ¡yo entiendo!\n"
	.string "¡Oh! ¡Lo siento mucho!\l"
	.string "Me has hecho tan feliz que estoy\l"
	.string "llorando…\p"
	.string "¡Haré todo lo posible para atrapar\n"
	.string "un {STR_VAR_1}!\p"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeWhichMon1::
	.string "¡Yupi! ¡Es {PLAYER}!\n"
	.string "¡Yupi, has venido en el momento\l"
	.string "justo, también!\l"
	.string "¡Necesito tu consejo otra vez!\p"
	.string "Um, estoy hecho un lío--¿debería usar\n"
	.string "mi {STR_VAR_1} o mi {STR_VAR_2}…\p"
	.string "¿Cuál crees que debería entrenar,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, ¡así que mi {STR_VAR_1} es mejor!\n"
	.string "Vale, ¡lo haré!\p"
	.string "¡Gracias por enseñarme!$"

gText_ApprenticeWhichMon2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Tengo una pregunta que quería hacerte.\p"
	.string "Estoy en un dilema sobre si debería\n"
	.string "entrenar un {STR_VAR_1} o un {STR_VAR_2}.\p"
	.string "¿Qué POKéMON crees que será\n"
	.string "más fuerte?$"

gText_ApprenticeMonThanks2::
	.string "¿{STR_VAR_1} es tu elección?\n"
	.string "¡Vale, lo tengo!\p"
	.string "Iré a atrapar un {STR_VAR_1} fuerte\n"
	.string "¡enseguida!\p"
	.string "¡Hasta otra!$"

gText_ApprenticeWhichMon3::
	.string "Hola, {PLAYER}…\p"
	.string "Um, probablemente ya te has olvidado\n"
	.string "de alguien como yo…\p"
	.string "…Pero eso no importa si pudieras\n"
	.string "darme un consejo…\p"
	.string "No puedo decidir qué tipo de\n"
	.string "POKéMON debería entrenar…\p"
	.string "He reducido el campo al POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}, pero ahí\l"
	.string "es donde me he quedado atascado…\p"
	.string "{PLAYER}, probablemente no quieras\n"
	.string "molestarte, pero por favor decide\l"
	.string "por mí.$"

gText_ApprenticeMonThanks3::
	.string "¿Pero un {STR_VAR_1} salvaje siquiera\n"
	.string "me hará caso?\p"
	.string "¡Lo intentaré!\p"
	.string "¿Pero podré atrapar uno siquiera…\n"
	.string "¡No! ¡Haré lo mejor que pueda!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon4::
	.string "¡Oh, {PLAYER}{KUN}! ¡Me alegro tanto de verte!\n"
	.string "¡Estaba a punto de ir a buscarte!\p"
	.string "¿Puedes decidir qué tipo de POKéMON\n"
	.string "debería usar?\p"
	.string "Por ejemplo…\n"
	.string "¿Qué tal el POKéMON {STR_VAR_1}\l"
	.string "y {STR_VAR_2}?\p"
	.string "¿Cuál crees que sería\n"
	.string "mejor?$"

gText_ApprenticeMonThanks4::
	.string "¿{STR_VAR_1}? ¡Eso es genial!\p"
	.string "Sabiendo que has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon5::
	.string "¡Si es {PLAYER}{KUN}! ¿Cómo te va?\n"
	.string "¡Estoy ocupado otra vez como siempre!\p"
	.string "Quiero hacerlo bien con los POKéMON,\n"
	.string "también, pero no he podido decidir\l"
	.string "qué POKéMON debería usar.\p"
	.string "¿Sabes cómo los {STR_VAR_1} parecen\n"
	.string "fuertes? Pero los {STR_VAR_2} son\l"
	.string "difíciles de ignorar.\p"
	.string "¡{PLAYER}{KUN}, dame parte de tu buen\n"
	.string "consejo! ¿Cuál sería bueno para mí?$"

gText_ApprenticeMonThanks5::
	.string "Vale, entendido.\n"
	.string "Encontraré tiempo de alguna manera y\l"
	.string "atraparé ese {STR_VAR_1} que me\l"
	.string "recomendaste.\p"
	.string "Me alegro de haber encontrado un buen\n"
	.string "mentor en ti.\l"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMon6::
	.string "¡Oh!\n"
	.string "¡Yay, es {PLAYER}!\p"
	.string "No perdí tiempo presumiendo ante\n"
	.string "mis amigos de haberte conocido!\p"
	.string "Necesito consultar tu mente otra vez\n"
	.string "hoy. ¡Es fácil para ti!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La pregunta que tengo es…\p"
	.string "Si fuera a entrenar un POKéMON,\n"
	.string "y las opciones fueran un {STR_VAR_1}\l"
	.string "o un {STR_VAR_2}, ¿cuál debería ser?$"

gText_ApprenticeMonThanks6::
	.string "¡Ahhh!\n"
	.string "¿{STR_VAR_1}, dices?\l"
	.string "¡Gracias por una respuesta tan guay!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Encontremos aquí de nuevo, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMon7::
	.string "Oh, ¿eres tú, {PLAYER}?\n"
	.string "¡Estoy encantado de verte de nuevo!\p"
	.string "Desde que me convertí en tu aprendiz,\n"
	.string "mi confianza ha estado floreciendo.\p"
	.string "¡Creo que estoy listo para entrenar\n"
	.string "un POKéMON por mi cuenta!\p"
	.string "{PLAYER}, ¿puedo imponerte que elijas\n"
	.string "qué POKéMON debería entrenar?\p"
	.string "Las opciones son el POKéMON\n"
	.string "{STR_VAR_1} o {STR_VAR_2}…\l"
	.string "¿Qué POKéMON es adecuado para mí?$"

gText_ApprenticeMonThanks7::
	.string "¡Un {STR_VAR_1} es!\n"
	.string "¡Encontraré uno enseguida!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo de nuevo.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMon8::
	.string "¡Eek! ¡{PLAYER}! ¡Te encontré otra vez!\n"
	.string "¡Estoy… estoy encantado!\p"
	.string "¡Oh-oh-oh, ya sé!\n"
	.string "¡No debería dejar pasar esta\l"
	.string "oportunidad!\p"
	.string "¿Puedo pedirte un gran favor, {PLAYER}?\n"
	.string "¡Por favor, elige un POKéMON para mí!\p"
	.string "Por favor, decide cuál sería mejor,\n"
	.string "¿{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks8::
	.string "¡Guau! ¡Has decidido por mí!\n"
	.string "¡Un {STR_VAR_1} es lo que entrenaré\l"
	.string "lo mejor que pueda!\p"
	.string "Espero que estés dispuesto a enseñarme\n"
	.string "algo más en otro momento.$"

gText_ApprenticeWhichMon9::
	.string "¡Oye, oye!\n"
	.string "¡Mi mentor, {PLAYER}{KUN}!\p"
	.string "Hola, te he estado buscando\n"
	.string "para pedirte más de tu sabio consejo.\p"
	.string "¿Qué tipo de POKéMON sería adecuado\n"
	.string "para mí, un {STR_VAR_1} o un {STR_VAR_2}?\p"
	.string "No seas tímido ahora.\n"
	.string "¡Suéltalo!$"

gText_ApprenticeMonThanks9::
	.string "Ajá, ¡un {STR_VAR_1} es!\n"
	.string "¡OK, A-OK!\l"
	.string "Conseguiré uno en una POKé BALL,\l"
	.string "¡como, pam!\p"
	.string "Muy bien, gracias, como siempre.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMon10::
	.string "¡{PLAYER}{KUN}, escucha! ¡Grandes noticias!\n"
	.string "¡Atrapé un POKéMON espejismo!\p"
	.string "¡Por supuesto que miento!\n"
	.string "¡Wahahaha!\p"
	.string "Eso no es mentira, sin embargo.\n"
	.string "No soy muy bueno atrapando\l"
	.string "POKéMON.\p"
	.string "Así que, ¿qué tal si decides por mí\n"
	.string "qué tipo de POKéMON debería atrapar,\l"
	.string "maestro?\p"
	.string "¿Cuál sería mejor?\n"
	.string "¿{STR_VAR_1} o {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "¿Vale, así que elegiste {STR_VAR_1}?\n"
	.string "¡Atraparé el otro tipo, entonces!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMon11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso deletrea ahoy!\p"
	.string "¡El MARINERO rapero soy yo!\n"
	.string "¿Seguro que recuerdas quién soy yo?\p"
	.string "Hoy, tengo una pregunta POKéMON\n"
	.string "que pide tu sugerencia.\p"
	.string "Tengo la elección entre este\n"
	.string "{STR_VAR_1} y {STR_VAR_2}, ¿ves?\l"
	.string "¿Cuál es el que debo atrapar para mí?$"

gText_ApprenticeMonThanks11::
	.string "¿{STR_VAR_1}, dices, oye, oye!\n"
	.string "¡Iré a atrapar uno enseguida!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu voz!$"

gText_ApprenticeWhichMon12::
	.string "Oh, guau, ¡si es {PLAYER}!\p"
	.string "¿Qué debería hacer? ¿Pedir tu consejo?\n"
	.string "¿Por qué no? ¡Ya estoy hablando contigo!\p"
	.string "Ha pasado mucho tiempo. Déjame romper\n"
	.string "el hielo. ¡También estoy buscando\l"
	.string "consejo!\l"
	.string "¿Me recibes?\l"
	.string "¡Me recibes!\p"
	.string "Mis POKéMON--¿cuál debería usar?\n"
	.string "Es o {STR_VAR_1} o {STR_VAR_2}.\l"
	.string "¿Cuál eliges?$"

gText_ApprenticeMonThanks12::
	.string "Si ese {STR_VAR_1} es el mejor,\n"
	.string "¡haré lo que sugieras!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos de nuevo, mi amigo listo!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hola, {PLAYER}{KUN}…\n"
	.string "Tengo este horrible dolor de cabeza…\p"
	.string "Debe haberme preocupado demasiado\n"
	.string "el tipo de POKéMON que debería entrenar.\p"
	.string "Así que, dadas las circunstancias,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, si tuviera que elegir entre\n"
	.string "el POKéMON {STR_VAR_1} y\l"
	.string "{STR_VAR_2}, ¿cuál debería ser?$"

gText_ApprenticeMonThanks13::
	.string "Hm, un {STR_VAR_1}, muy bien.\n"
	.string "Iré a buscar uno cuando me recupere.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedirte ayuda así.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me estoy poniendo nervioso…\l"
	.string "Yo… necesito tu consejo.\p"
	.string "Yo… estoy muy avergonzado, pero no\n"
	.string "puedo decidir qué POKéMON usar.\p"
	.string "Si las opciones fueran {STR_VAR_1} o\n"
	.string "{STR_VAR_2}, ¿cuál sería mejor?$"

gText_ApprenticeMonThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Haré lo mejor posible con un {STR_VAR_1}.\p"
	.string "Espero poder hacerlo lo mejor posible\n"
	.string "sin ponerme nervioso.\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos volvemos a ver, espero que seas\l"
	.string "tan útil.$"

gText_ApprenticeWhichMon15::
	.string "¿Mmm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero de verdad eres real?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "De paso, me gustaría obtener\l"
	.string "tu consejo.\p"
	.string "Es sobre el POKéMON que voy a usar.\p"
	.string "Si las opciones son el POKéMON\n"
	.string "{STR_VAR_1} y {STR_VAR_2}, ¿cuál es\l"
	.string "más digno de mí?$"

gText_ApprenticeMonThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿Estás seguro?\p"
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso yo pueda\n"
	.string "manejar con aplomo.\p"
	.string "¡Nos vemos de nuevo!$"

gText_ApprenticeWhichMove0::
	.string "¡Waaah! Oh, {PLAYER}!\n"
	.string "Sniff… Hic…\p"
	.string "¡Tengo un dilema!\n"
	.string "No puedo decidir un movimiento para\l"
	.string "mi {STR_VAR_1}…\p"
	.string "Por favor, por favor, {PLAYER}.\n"
	.string "¿Puedes decidir por mí?\p"
	.string "Para mi {STR_VAR_1}, ¿qué movimiento\n"
	.string "sería la mejor elección: {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "¿{STR_VAR_1}?\n"
	.string "¡Buaaaaah!\p"
	.string "¡Oh! ¡Lo siento mucho, {PLAYER}!\n"
	.string "Me has hecho tan feliz al decidir\l"
	.string "el movimiento, que estoy llorando…\p"
	.string "Sniff…\n"
	.string "¡Muchísimas gracias!$"

gText_ApprenticeWhichMove1::
	.string "¡Yupi! ¡Hola, {PLAYER}!\n"
	.string "¡Necesito tu consejo otra vez!\p"
	.string "Quiero enseñar a mi {STR_VAR_1}\n"
	.string "un movimiento guay.\p"
	.string "Me gustan tanto el movimiento\n"
	.string "{STR_VAR_2} como {STR_VAR_3}.\l"
	.string "¿Cuál es tu recomendación?$"

gText_ApprenticeMoveThanks1::
	.string "¿{STR_VAR_1} es mejor? ¡Supongo que sí!\n"
	.string "¡Vale, me quedo con ese!\p"
	.string "Si nos encontramos aquí de nuevo,\n"
	.string "por favor enséñame algo más, ¡maestro!$"

gText_ApprenticeWhichMove2::
	.string "¡Hola, {PLAYER}!\n"
	.string "Es sobre mi {STR_VAR_1}, pero estoy\l"
	.string "preocupado por sus movimientos.\p"
	.string "Verás, son los movimientos {STR_VAR_2}\n"
	.string "y {STR_VAR_3}.\p"
	.string "¿Cuál es más fuerte y mejor para\n"
	.string "mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "¿{STR_VAR_1} es tu elección?\n"
	.string "¡Vale, lo tengo!\p"
	.string "Iré a enseñar {STR_VAR_1} a\n"
	.string "mi POKéMON enseguida!\p"
	.string "¡Hasta otra!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "No tengo remedio, no, ¡de verdad!\p"
	.string "He decidido entrenar un POKéMON,\n"
	.string "pero ahora ni siquiera puedo decidir\l"
	.string "qué movimiento debería dejar que\l"
	.string "aprenda…\p"
	.string "Sé que no significa nada\n"
	.string "para ti, {PLAYER}.\p"
	.string "Pero significa mucho para mí…\p"
	.string "Por favor, {PLAYER}, ¿podrías elegir\n"
	.string "un movimiento para mi {STR_VAR_1}?\p"
	.string "Si pudieras incluso elegir entre\n"
	.string "{STR_VAR_2} y {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "¡Entiendo!\p"
	.string "¿Pero siquiera estará dispuesto a\n"
	.string "aprender {STR_VAR_1} para mí…\l"
	.string "¡No! ¡Haré lo mejor que pueda!\p"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove4::
	.string "¡Oh, {PLAYER}{KUN}!\n"
	.string "¡Justo esperaba verte, también!\p"
	.string "Me preguntaba qué movimiento sería\n"
	.string "adecuado para mi {STR_VAR_1}.\p"
	.string "No puedo decidir, así que ¿puedes\n"
	.string "decidir por mí?\p"
	.string "Por ejemplo… ¿Qué tal los movimientos\n"
	.string "{STR_VAR_2} y {STR_VAR_3}?\l"
	.string "¿Cuál sería mejor?$"

gText_ApprenticeMoveThanks4::
	.string "¿{STR_VAR_1}? ¡Eso es genial!\p"
	.string "Sabiendo que has tomado la decisión,\n"
	.string "{PLAYER}{KUN}, no me sentiré tan mal si\l"
	.string "pierdo.\p"
	.string "Vale, volveré a pedirte consejo.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove5::
	.string "¿Cómo pueden las cosas estar tan\n"
	.string "ocupadas? ¡Oye, si es {PLAYER}{KUN}!\l"
	.string "¿Cómo te va?\p"
	.string "Desde que me levanté esta mañana, he\n"
	.string "hecho mi jogging, natación y cocina.\p"
	.string "¡No te imaginas lo ocupado que estoy!\p"
	.string "¡Ni siquiera puedo decidir qué movimiento\n"
	.string "debería aprender mi {STR_VAR_1}!\p"
	.string "¿{STR_VAR_2} parece bueno, eh?\n"
	.string "Pero {STR_VAR_3} también es decente.\p"
	.string "¡{PLAYER}{KUN}, dame parte de tu buen\n"
	.string "consejo! ¿Qué movimiento sería bueno\l"
	.string "para mí?$"

gText_ApprenticeMoveThanks5::
	.string "Vale, entendido.\n"
	.string "Encontraré tiempo en mi agenda y\l"
	.string "enseñaré ese movimiento.\p"
	.string "Me alegro de haber encontrado un buen\n"
	.string "mentor en ti.\l"
	.string "¡Gracias! ¡Nos vemos!$"

gText_ApprenticeWhichMove6::
	.string "¡Oh! ¡Qué suerte!\n"
	.string "¡Te encontré otra vez, {PLAYER}!\l"
	.string "Necesito consultar tu mente otra vez\l"
	.string "hoy.\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La pregunta que tengo es…\p"
	.string "Para mi {STR_VAR_1}, ¿cuál es el\n"
	.string "movimiento más adecuado, {STR_VAR_2}\l"
	.string "o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "¡Ahhh!\n"
	.string "¿{STR_VAR_1}, dices?\l"
	.string "¡Gracias por una respuesta tan guay!\p"
	.string "Supongo que eso es todo lo que quería\n"
	.string "preguntarte hoy.\p"
	.string "Encontremos aquí de nuevo, ¿vale?\n"
	.string "¡Gracias!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hola, {PLAYER}.\n"
	.string "Confío en que estés bien.\p"
	.string "Tengo que buscar tu consejo otra vez.\n"
	.string "Es sobre mi queridísimo {STR_VAR_1}.\p"
	.string "¿Cuál sería el movimiento ideal para\n"
	.string "mi adorable {STR_VAR_1}?\l"
	.string "¿{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "¡{STR_VAR_1} es!\n"
	.string "¡Lo enseñaré enseguida!\p"
	.string "Gracias, {PLAYER}.\n"
	.string "Espero poder contar contigo de nuevo.\l"
	.string "¡Cuídate mucho!$"

gText_ApprenticeWhichMove8::
	.string "¡Eek! ¡{PLAYER}! ¡Te encontré otra vez!\n"
	.string "¡Estoy… estoy encantado!\p"
	.string "¡Siempre que lo necesito, estás ahí\n"
	.string "para mí, {PLAYER}!\p"
	.string "Hoy, quiero que me recomiendes\n"
	.string "¡un movimiento para mí!\p"
	.string "¡Por favor, elige un movimiento para\n"
	.string "mi {STR_VAR_1}!\p"
	.string "¿Qué movimiento sería mejor,\n"
	.string "{STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "¡Oh-oh-oh! ¡Gracias!\n"
	.string "¡{STR_VAR_1} es!\l"
	.string "¡Perfectamente entendido!\p"
	.string "Espero que estés dispuesto a enseñarme\n"
	.string "algo más en otro momento.$"

gText_ApprenticeWhichMove9::
	.string "¡Hola, {PLAYER}{KUN}, bueno!\n"
	.string "Espero recibir más de\l"
	.string "tu sabio consejo hoy.\p"
	.string "¿Qué sería el mejor movimiento para\n"
	.string "mi {STR_VAR_1}?\p"
	.string "Debería ser algo que me\n"
	.string "haga ganar así como así.\p"
	.string "¿Sería {STR_VAR_2}?\n"
	.string "¿O {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Ajá, ¡{STR_VAR_1} es!\n"
	.string "¡Sí, bueno!\l"
	.string "Lo enseñaré, ¡como, ka-blam!\p"
	.string "Muy bien, gracias, como siempre.\n"
	.string "¡Adiós!$"

gText_ApprenticeWhichMove10::
	.string "¡{PLAYER}{KUN}, es completamente salvaje!\p"
	.string "¡Mi POKéMON!\n"
	.string "¡Aprendió seis movimientos!\p"
	.string "¡Por supuesto que miento!\n"
	.string "¡Wahahaha!\p"
	.string "Eso no es mentira, sin embargo.\n"
	.string "No soy muy bueno eligiendo movimientos\l"
	.string "para mis POKéMON.\p"
	.string "Así que, ¿qué tal si decides por mí\n"
	.string "qué tipo de movimiento debería enseñar?\p"
	.string "¿{STR_VAR_2} o {STR_VAR_3}--cuál\n"
	.string "iría mejor con mi {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "¿Vale, así que elegiste {STR_VAR_1}?\n"
	.string "¡Elegiré otro movimiento, entonces!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias, maestro!\n"
	.string "¡Espero que sigas enseñándome!$"

gText_ApprenticeWhichMove11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso deletrea ahoy!\p"
	.string "¡El MARINERO rapero soy yo!\n"
	.string "Siempre estoy al tanto, no me preguntes\l"
	.string "por qué.\p"
	.string "Hoy, tengo una pregunta de movimiento\n"
	.string "que pide tu sugerencia.\p"
	.string "{STR_VAR_2} y {STR_VAR_3} son\n"
	.string "los movimientos. ¿Cuál sería el mejor\l"
	.string "para mi {STR_VAR_1} para que bailé?$"

gText_ApprenticeMoveThanks11::
	.string "¿{STR_VAR_1}, dices, oye, oye!\n"
	.string "¡Iré a enseñarlo enseguida!\p"
	.string "Si alguna vez necesito consejo,\n"
	.string "¡{PLAYER}, siempre seguiré tu voz!$"

gText_ApprenticeWhichMove12::
	.string "¡Oh, yeahah, si es {PLAYER}!\p"
	.string "¿Qué debería hacer? ¿Pedir tu consejo?\n"
	.string "¿Por qué no? ¡Ya estoy hablando contigo!\p"
	.string "{PLAYER}, ¿te sorprendo?\n"
	.string "Quiero tu consejo, ¿no lo ves?\p"
	.string "¿Me recibes?\n"
	.string "¡Me recibes!\p"
	.string "Mi {STR_VAR_1}--¿qué debería usar?\n"
	.string "Es {STR_VAR_2} o {STR_VAR_3},\l"
	.string "¿qué eliges?$"

gText_ApprenticeMoveThanks12::
	.string "Si ese {STR_VAR_1} es el mejor,\n"
	.string "¡haré lo que sugieras!\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Nos vemos de nuevo, mi amigo listo!$"

gText_ApprenticeWhichMove13::
	.string "¡Gahack! ¡Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "Tengo este maldito resfriado, sí…\p"
	.string "Quiero elegir un movimiento para mi\n"
	.string "POKéMON, pero no estoy para ello…\p"
	.string "Así que, dadas las circunstancias,\n"
	.string "necesito que decidas por mí.\p"
	.string "{PLAYER}{KUN}, si tuviera que elegir entre\n"
	.string "{STR_VAR_2} y {STR_VAR_3} para\l"
	.string "mi {STR_VAR_1}, ¿cuál sería?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, muy bien. ¡Tos!\n"
	.string "Iré a enseñarlo cuando me recupere.\p"
	.string "Espero poder seguir acudiendo a ti\n"
	.string "para pedirte ayuda así.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "¿{PLAYER}{KUN}…?\p"
	.string "Por favor, no me mires así.\n"
	.string "Me estoy poniendo nervioso…\l"
	.string "Yo… necesito tu consejo.\p"
	.string "Yo… estoy muy avergonzado, pero no\n"
	.string "puedo decidir qué movimiento debería\l"
	.string "enseñar a mi POKéMON.\p"
	.string "Es para mi {STR_VAR_1}.\n"
	.string "Si las opciones fueran {STR_VAR_2} o\l"
	.string "{STR_VAR_3}, ¿cuál sería mejor?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… ¡Vale!\n"
	.string "Probaré ese {STR_VAR_1}.\p"
	.string "Espero poder enseñar ese movimiento…\n"
	.string "Esto es tan estresante…\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Si nos volvemos a ver, espero que seas\l"
	.string "tan útil.$"

gText_ApprenticeWhichMove15::
	.string "¿Mmm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero de verdad eres real?\p"
	.string "¿Quizás eres uno de esos mimos\n"
	.string "populares?\p"
	.string "No, no, si eres real, está bien.\n"
	.string "¡No hay necesidad de enfadarse, te lo\l"
	.string "aseguro!\p"
	.string "De paso, me gustaría obtener\n"
	.string "tu consejo.\p"
	.string "Es sobre mi {STR_VAR_1}.\p"
	.string "¿Qué movimiento sería mejor para que\n"
	.string "use, {STR_VAR_2} o {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "¿{STR_VAR_1}?\n"
	.string "¿No hay duda sobre eso?\p"
	.string "Ya veo. Si ese es el caso, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que sea algo que incluso\n"
	.string "mi POKéMON pueda aprender.\p"
	.string "¡Nos vemos de nuevo!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… ¿{PLAYER}?\n"
	.string "¡Es {PLAYER}!\l"
	.string "¡Oh! Sniff… sob… ¡Por favor, escucha!\p"
	.string "Yo… Cuando combato, me pongo tan\n"
	.string "nervioso, que no puedo evitar llorar\l"
	.string "incluso si gano…\p"
	.string "Ojalá pudiera decir algo guay\n"
	.string "cuando gano…\p"
	.string "¡Por favor, por favor, {PLAYER}!\n"
	.string "¿Podrías enseñarme algo guay que\l"
	.string "decir cuando gane para no llorar?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "¡Impresionante! ¡Genial! ¡Awoooh!\n"
	.string "¡Es realmente guay!\p"
	.string "Oh… lo siento…\n"
	.string "Estoy tan feliz, que estoy llorando…\p"
	.string "Sniff… ¡{PLAYER}!\n"
	.string "¡Muchísimas gracias por todo!\p"
	.string "¡Lucharé lo mejor que pueda por\n"
	.string "ti, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "¡La próxima vez… deberíamos combatir!$"

gText_ApprenticePickWinSpeech1::
	.string "¡Yupi! ¡Es {PLAYER}! ¡Hola!\n"
	.string "¡Quería preguntarte algo!\p"
	.string "Quiero decir algo guay cuando\n"
	.string "gane un combate.\p"
	.string "¿Tienes algún dicho guay que\n"
	.string "podrías recomendar?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, ¡guau! ¡Eso es tan guay!\n"
	.string "¡Vale, diré eso!\p"
	.string "¡Gracias por enseñarme todo este tiempo!\n"
	.string "Voy a hacer lo mejor que pueda\l"
	.string "dondequiera que vaya de ahora en\l"
	.string "adelante.\p"
	.string "¡Cuando nos encontremos de nuevo, será\n"
	.string "para un combate!$"

gText_ApprenticePickWinSpeech2::
	.string "¡Hola, {PLAYER}!\p"
	.string "Mis POKéMON y yo estamos preparados\n"
	.string "para cualquier cosa, excepto una.\p"
	.string "Creo que sería bueno tener algo\n"
	.string "que gritar cuando gane.\p"
	.string "¿Podrías pensar en algo bueno\n"
	.string "que decir?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…¡Guay!\n"
	.string "¡Lo usaré!\p"
	.string "Voy a salir a combatir por todas\n"
	.string "partes.\p"
	.string "Quién sabe, incluso podría llegar a\n"
	.string "combatir contra ti algún día, {PLAYER}.\p"
	.string "La próxima vez, ¡encontremos en un\n"
	.string "lugar de combate!$"

gText_ApprenticePickWinSpeech3::
	.string "Hola, {PLAYER}…\n"
	.string "Siento molestarte, pero estoy\l"
	.string "desesperado…\p"
	.string "Incluso cuando…\n"
	.string "Incluso cuando gano, no tengo nada\l"
	.string "especial que decir…\p"
	.string "Sé que no significa nada\n"
	.string "para ti, {PLAYER}.\p"
	.string "Pero significa mucho para mí…\p"
	.string "Por favor, {PLAYER}, ¿qué debería decir\n"
	.string "si gano un combate?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Eso es inspirador…\p"
	.string "Uh… ¿Está bien que alguien como yo\n"
	.string "incluso diga eso?\p"
	.string "¡No! ¡Haré lo mejor que pueda!\p"
	.string "{PLAYER}, muchísimas gracias por\n"
	.string "aguantarme durante tanto tiempo…\p"
	.string "Prometo hacer lo mejor posible\n"
	.string "de ahora en adelante.\p"
	.string "Seguro que olvidarás rápidamente\n"
	.string "a alguien como yo, pero encontremos\l"
	.string "en algún lugar de nuevo.$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hay algo que quiero que escuches.\p"
	.string "Sé que no siempre sueno\n"
	.string "agradable o educado…\p"
	.string "Cuando gano un combate, creo que\n"
	.string "doy la impresión de ser arrogante.\p"
	.string "No quiero caerle mal a la gente,\n"
	.string "así que quiero decir algo agradable\l"
	.string "a alguien a quien derrote.\p"
	.string "¡Pero no se me ocurre nada bueno!\n"
	.string "¿Podrías pensar en algo para mí?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "¡No está mal!\n"
	.string "¡Síp, eso es lo que haré!\p"
	.string "Voy a salir a la carretera y haré lo\n"
	.string "que pueda con lo que me enseñaste en\l"
	.string "mi cabeza y corazón.\p"
	.string "¡Siento haber sido tan insistente\n"
	.string "contigo!\p"
	.string "La próxima vez, combatimos, ¿vale?\n"
	.string "¡Nos vemos!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, no puedo superar lo ocupado que estoy!\n"
	.string "Oh, oye, te estaba buscando, {PLAYER}{KUN}.\p"
	.string "¿Estás bien como siempre?\n"
	.string "Las cosas no han cambiado para mí.\p"
	.string "Tengo que correr, luchar y mapear.\n"
	.string "¿Por qué estoy tan ocupado?\p"
	.string "Pero aunque estoy ocupado, sería de mala\n"
	.string "educación simplemente darme la vuelta y\l"
	.string "irme de una victoria sin decir una palabra.\p"
	.string "Así que, ¿qué sería un dicho guay para\n"
	.string "resaltar mi estilo cuando termine y me\l"
	.string "vaya? ¡{PLAYER}{KUN}, ayúdame!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Vale, entendido.\n"
	.string "¡Puedo encontrar tiempo para decir eso!\p"
	.string "Honestamente, me alegro de haber\n"
	.string "encontrado un buen mentor como tú.\p"
	.string "Voy a sacar tiempo de alguna manera\n"
	.string "para meterme en combates.\p"
	.string "¡Gracias por todo, {PLAYER}{KUN}!\n"
	.string "¡Tenemos que combatir, tú y yo, algún\l"
	.string "día!$"

gText_ApprenticePickWinSpeech6::
	.string "¡He tenido suerte otra vez!\n"
	.string "¡{PLAYER}! ¡Me alegro de verte!\l"
	.string "¡Como siempre, necesito tu consejo!\p"
	.string "¡Redoble de tambores, por favor!\n"
	.string "La última pregunta que tengo es…\p"
	.string "Si gano un combate y quiero terminar\n"
	.string "con un toque guay, ¿qué debería decir?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Eso… ¡Eso es fabuloso!\n"
	.string "¡Es digno y guay! ¡Lo reclamo!\p"
	.string "…Escucha, creo que me estoy volviendo\n"
	.string "decente en esto, ¿eh?\p"
	.string "Así que, estoy pensando en desafiar a\n"
	.string "otros ENTRENADORES de ahora en adelante.\p"
	.string "{PLAYER}, tu consejo realmente me ayudó.\p"
	.string "Quizás algún día, llegue el momento en\n"
	.string "que combatamos.\p"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "¡Me alegro tanto de haberte conocido!\p"
	.string "Ya no tengo ninguna preocupación con\n"
	.string "respecto a mis POKéMON.\p"
	.string "Soy yo mismo quien me preocupa…\p"
	.string "¿Sabes cómo un ENTRENADOR dice\n"
	.string "algunas cosas al ganar un combate?\p"
	.string "Definitivamente, ¡ojalá pudiera hacer\n"
	.string "eso, también!\p"
	.string "Por favor, ¿qué debería decir cuando\n"
	.string "gane un combate?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "¡Ah! ¡Ese dicho! Me refresca\n"
	.string "y me hace sentir renacido.\p"
	.string "¡Debo usarlo enseguida!\p"
	.string "Y ahora, debo despedirme,\n"
	.string "{PLAYER}…\p"
	.string "Voy a salir a combatir contra muchos\n"
	.string "otros, pero nunca olvidaré tus\l"
	.string "enseñanzas.\p"
	.string "Quizás algún día…\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech8::
	.string "¡Eek! ¡He avistado a {PLAYER}!\n"
	.string "¡Estoy… estoy encantado de verte!\p"
	.string "¡Oh-oh-oh! Hay algo que simplemente\n"
	.string "tenía que preguntarte.\p"
	.string "Hace un rato, gané un combate.\n"
	.string "¡Esa parte fue emocionante!\p"
	.string "Pero me puso tan contento que\n"
	.string "me ahogué y no pude decir nada.\p"
	.string "Así que ahora, {PLAYER}, por favor, quiero\n"
	.string "que pienses en una frase de despedida\l"
	.string "para cuando gane.$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "¡Buaaaaah!\n"
	.string "¿¡Voy a decir eso?!\l"
	.string "¡Estoy… estoy delirante de alegría!\p"
	.string "¡G-g-gracias!\n"
	.string "¡No me queda nada por lamentar ahora!\p"
	.string "Voy a viajar ahora y combatir contra\n"
	.string "todo tipo de gente.\p"
	.string "Todo, se lo debo a ti, {PLAYER}.\n"
	.string "De verdad, de verdad, ¡gracias!\p"
	.string "Tengo que irme ahora, pero encontremos\n"
	.string "en combate algún día.$"

gText_ApprenticePickWinSpeech9::
	.string "¡Hola, bueno!\n"
	.string "¡{PLAYER}{KUN}!\p"
	.string "¿Sabes? Me está dando comezón vagar\n"
	.string "y combatir donde sea.\p"
	.string "Pero antes de hacerlo, quiero tu consejo\n"
	.string "una vez más, ¡por favor!\p"
	.string "Si ganara un combate, ¿qué sería una\n"
	.string "buena fanfarronada que podría decir a mi\l"
	.string "caído oponente ENTRENADOR?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Ajá, ¡eso es dulce!\n"
	.string "¡Sí, bueno!\l"
	.string "Lo probaré diciendo, ¡como, zam!\p"
	.string "Y ahora, ¡es hora de despedirse!\n"
	.string "¡Gracias por todo tipo de cosas!\p"
	.string "¡Dame un combate algún día, ¿vale?\n"
	.string "¡Adiós!$"

gText_ApprenticePickWinSpeech10::
	.string "¡{PLAYER}{KUN}, hay un gran problema!\p"
	.string "¡Cuando gano un combate, me jacto de ello\n"
	.string "durante al menos una hora!\p"
	.string "¡Por supuesto que miento!\n"
	.string "¡Wahahaha!\p"
	.string "Eso no es mentira, sin embargo.\n"
	.string "No soy muy bueno charlando.\p"
	.string "Así que, ¿qué tal si decides por mí qué\n"
	.string "debería decir después de ganar un\l"
	.string "combate, maestro?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "¿Eso es lo que debería decir, eh?\n"
	.string "Entonces, ¡me mantendré alejado de eso!\p"
	.string "¡Broma!\n"
	.string "¡Obedeceré tu enseñanza, maestro!\p"
	.string "¡Gracias por enseñarme todo este tiempo,\n"
	.string "maestro!\p"
	.string "Finalmente estoy entendiendo de qué se\n"
	.string "trata ser un ENTRENADOR.\p"
	.string "Voy a salir y ganar combates contra\n"
	.string "cualquier ENTRENADOR.\p"
	.string "¡Quizás seas tú algún día, maestro!\p"
	.string "¡Eso es todo!\n"
	.string "¡Adiós, mi maestro!$"

gText_ApprenticePickWinSpeech11::
	.string "¡A-H-O-Y!\n"
	.string "¡Y eso deletrea ahoy!\p"
	.string "¡El MARINERO rapero soy yo!\n"
	.string "Esta será mi última pregunta,\l"
	.string "¡no llores!\p"
	.string "¡Es una pregunta de dichos\n"
	.string "que pide tu sugerencia!\p"
	.string "Si gano un combate, ¿qué puedo decir\n"
	.string "de una manera realmente guay?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "¡Perfecto! Eso es lo que usaré.\n"
	.string "¡Tenía razón al hacerte elegir!\p"
	.string "Y ahora, creo que sería lo mejor,\n"
	.string "¡si volara del nido!\p"
	.string "Gracias por todo lo que me enseñaste.\n"
	.string "¡Me iré en una juerga de combates!\p"
	.string "¡B-O-N-V-O-Y-A-G-E!\n"
	.string "Y eso deletrea bon voyage,\l"
	.string "¡a ti esto es mi homenaje!$"

gText_ApprenticePickWinSpeech12::
	.string "¡Oh, sí, {PLAYER}!\n"
	.string "¡Te encontré otra vez hoy!\p"
	.string "¿Qué debería hacer? ¿Preguntarte otra\n"
	.string "vez? ¿Por qué no? ¡Ya te estoy\l"
	.string "preguntando!\p"
	.string "De todos modos, {PLAYER}…\n"
	.string "¿Me recibes?\l"
	.string "¡Me recibes!\l"
	.string "¡Necesito más consejos para mí!\p"
	.string "Es sobre lo que debería gritar.\n"
	.string "Algo guay que gritar cuando\l"
	.string "un combate termine bien.\p"
	.string "Vamos, ¡quiero oírte decirlo!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "¡Muy bien, muy bien!\n"
	.string "¡Lo usaré porque es tan chulo!\p"
	.string "Me he quedado sin cosas que preguntarte.\n"
	.string "Solo queda despedirse.\p"
	.string "Pero quizás algún día nos encontremos,\n"
	.string "con uno destinado a caer derrotado.\p"
	.string "Pero, realmente es hora de despedirse.\p"
	.string "Bueno, {PLAYER}, tengo que vagar libre,\n"
	.string "pero no te olvides de mí.\p"
	.string "¡Cuídate, {PLAYER}!\n"
	.string "¡Te quiero!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, he terminado…\n"
	.string "Mi nariz no para de gotear…\p"
	.string "Estaba intentando pensar en algo\n"
	.string "guay que decir cuando gane un combate.\p"
	.string "Me inspiró tanto, que me hizo llorar,\n"
	.string "y ahora mi nariz no para de moquear…\p"
	.string "Así que, dadas las circunstancias,\n"
	.string "necesito que decidas por mí, {PLAYER}{KUN}.\p"
	.string "Cuando gane un combate,\n"
	.string "¿qué debería decir?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Eso es bueno.\n"
	.string "No, ¡es inspirador!\l"
	.string "¡Está trayendo lágrimas frescas a mis\l"
	.string "ojos!\p"
	.string "Pero a pesar de mis lágrimas y nariz\n"
	.string "que moquea, ¡usaré ese dicho!\p"
	.string "Me he quedado sin cosas que preguntarte,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "¡De ahora en adelante, somos rivales!\n"
	.string "¡Gracias por todo!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Por favor, no me mires así.\n"
	.string "Me estás poniendo nervioso.\p"
	.string "Yo… necesito tu consejo otra vez.\n"
	.string "Será la última, sin embargo…\p"
	.string "Es realmente vergonzoso preguntar,\n"
	.string "pero ¿qué pasa si gano un combate?\l"
	.string "¿Qué debería decir?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… ¡Vale!\n"
	.string "¡Intentaré decir eso!\l"
	.string "Puede que esté demasiado nervioso\l"
	.string "para decirlo…\p"
	.string "Gracias, {PLAYER}{KUN}.\n"
	.string "Tengo que despedirme ahora.\p"
	.string "Obedeceré todo lo que me has enseñado,\n"
	.string "{PLAYER}{KUN}, y haré lo mejor que pueda.$"

gText_ApprenticePickWinSpeech15::
	.string "¿Mmm? Pareces ser {PLAYER}{KUN}…\n"
	.string "¿Pero de verdad eres tú?\l"
	.string "¿Quizás un MUÑECO {PLAYER} listo?\p"
	.string "Oh, no, no, no, ¡no te preocupes!\n"
	.string "Si de verdad eres real, por favor\l"
	.string "olvida mi descortesía.\p"
	.string "No hay necesidad de enfadarse tanto. Solo\n"
	.string "deseo más de tu excelente consejo.\p"
	.string "Se trata de un dicho.\p"
	.string "Más precisamente, ¿qué debería decir\n"
	.string "si gano un combate?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Cuando gane un combate…\p"
	.string "{STR_VAR_1}\p"
	.string "…¿Hablas en serio?\p"
	.string "Ya veo. Si hablas en serio, está bien.\n"
	.string "Te agradezco tu tiempo.\p"
	.string "Espero que incluso yo sea capaz de\n"
	.string "sacarle buen provecho a ese dicho.\p"
	.string "Parece que me he quedado sin consejos\n"
	.string "que necesitar.\p"
	.string "Creo que es hora de que me despida de ti\n"
	.string "y salga por mi cuenta.\p"
	.string "¡Gracias, mi mentor!\n"
	.string "¡Te pido disculpas por mi escepticismo!$"
