BattleDome_Text_Potential1::
	.string "¡El mejor candidato a campeón!$"

BattleDome_Text_Potential2::
	.string "Un equipo seguro de llegar a la final.$"

BattleDome_Text_Potential3::
	.string "Un probable finalista entre los tres primeros.$"

BattleDome_Text_Potential4::
	.string "Un candidato a terminar primero.$"

BattleDome_Text_Potential5::
	.string "Un equipo con potencial de primera.$"

BattleDome_Text_Potential6::
	.string "El equipo sorpresa de este torneo.$"

BattleDome_Text_Potential7::
	.string "Un equipo mejor que la media.$"

BattleDome_Text_Potential8::
	.string "El equipo medio de este torneo.$"

BattleDome_Text_Potential9::
	.string "Un equipo con potencial medio.$"

BattleDome_Text_Potential10::
	.string "Un equipo peor que la media.$"

BattleDome_Text_Potential11::
	.string "Un equipo buscando su primera victoria.$"

BattleDome_Text_Potential12::
	.string "Una victoria haría que este equipo se sintiera orgulloso.$"

BattleDome_Text_Potential13::
	.string "En general, un equipo débil.$"

BattleDome_Text_Potential14::
	.string "Un equipo con muy bajo potencial.$"

BattleDome_Text_Potential15::
	.string "Un equipo con pocas posibilidades de ganar el torneo.$"

BattleDome_Text_Potential16::
	.string "El equipo con menos posibilidades de ganar.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "¡La superestrella perfecta e invencible!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Dispuesto a arriesgar el desastre total a veces.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Hábil soportando combates largos.$"

BattleDome_Text_StyleVariesTactics::
	.string "Varía la táctica según el oponente.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Tiene un patrón de victoria sólido.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Usa ocasionalmente un movimiento muy raro.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Usa movimientos sorprendentes y perturbadores.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Vigila constantemente los PS en combate.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Bueno almacenando y luego liberando poder.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Hábil debilitando a los rivales.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Prefiere tácticas que dependen de la suerte.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Ataca con un aire majestuoso.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Ataca con movimientos potentes de pocos PP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Hábil debilitando y luego atacando.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Combate mientras soporta todos los ataques.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Hábil alterando emocionalmente a los rivales.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Usa movimientos fuertes y directos.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Usa agresivamente movimientos fuertes.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Combate esquivando hábilmente los ataques.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Hábil usando ataques perturbadores.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Usa muchos movimientos populares.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Tiene movimientos para combinaciones poderosas.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Usa ataques de alta probabilidad.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Usa agresivamente movimientos espectaculares.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Prioriza el ataque sobre la defensa.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Prioriza la defensa sobre el ataque.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Ataca rápidamente con movimientos fuertes.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Usa a menudo movimientos con efectos añadidos.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Usa una mezcla bien equilibrada de movimientos.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Este es el mensaje de ejemplo 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Este es el mensaje de ejemplo 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Este es el mensaje de ejemplo 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Este es el mensaje de ejemplo 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Prioriza PS y ATAQUE.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Prioriza PS y DEFENSA.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Prioriza PS y VELOCIDAD.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Prioriza PS y ATAQUE ESPECIAL.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Prioriza PS y DEFENSA ESPECIAL.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Prioriza ATAQUE y DEFENSA.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Prioriza ATAQUE y VELOCIDAD.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Prioriza ATAQUE y ATAQUE ESPECIAL.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Prioriza ATAQUE y DEFENSA ESPECIAL.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Prioriza DEFENSA y VELOCIDAD.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Prioriza DEFENSA y ATAQUE ESPECIAL.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Prioriza DEFENSA y DEFENSA ESPECIAL.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Prioriza VELOCIDAD y ATAQUE ESPECIAL.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Prioriza VELOCIDAD y DEFENSA ESPECIAL.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Prioriza ATAQUE ESPECIAL y DEFENSA ESPECIAL.$"

BattleDome_Text_EmphasizesHP::
	.string "Prioriza PS.$"

BattleDome_Text_EmphasizesAtk::
	.string "Prioriza ATAQUE.$"

BattleDome_Text_EmphasizesDef::
	.string "Prioriza DEFENSA.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Prioriza VELOCIDAD.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Prioriza ATAQUE ESPECIAL.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Prioriza DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Descuida PS y ATAQUE.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Descuida PS y DEFENSA.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Descuida PS y VELOCIDAD.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Descuida PS y ATAQUE ESPECIAL.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Descuida PS y DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Descuida ATAQUE y DEFENSA.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Descuida ATAQUE y VELOCIDAD.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Descuida ATAQUE y ATAQUE ESPECIAL.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Descuida ATAQUE y DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Descuida DEFENSA y VELOCIDAD.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Descuida DEFENSA y ATAQUE ESPECIAL.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Descuida DEFENSA y DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Descuida VELOCIDAD y ATAQUE ESPECIAL.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Descuida VELOCIDAD y DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Descuida ATAQUE ESPECIAL y DEFENSA ESPECIAL.$"

BattleDome_Text_NeglectsHP::
	.string "Descuida PS.$"

BattleDome_Text_NeglectsAtk::
	.string "Descuida ATAQUE.$"

BattleDome_Text_NeglectsDef::
	.string "Descuida DEFENSA.$"

BattleDome_Text_NeglectsSpeed::
	.string "Descuida VELOCIDAD.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Descuida ATAQUE ESPECIAL.$"

BattleDome_Text_NeglectsSpDef::
	.string "Descuida DEFENSA ESPECIAL.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Cría POKéMON de forma equilibrada.$"

BattleDome_Text_LetTheBattleBegin::
	.string "¡Que empiece el combate!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "¡{STR_VAR_1} ganó usando {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "¡{STR_VAR_1} se ha proclamado campeón!$"

BattleDome_Text_TrainerWonByDefault::
	.string "¡{STR_VAR_1} ganó por incomparecencia!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "¡{STR_VAR_1} ganó claramente por incomparecencia!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "¡{STR_VAR_1} ganó sin usar un movimiento!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "¡{STR_VAR_1} ganó claramente sin movimientos!$"

BattleDome_Text_Round1Match1::
	.string "Ronda 1, Combate 1$"

BattleDome_Text_Round1Match2::
	.string "Ronda 1, Combate 2$"

BattleDome_Text_Round1Match3::
	.string "Ronda 1, Combate 3$"

BattleDome_Text_Round1Match4::
	.string "Ronda 1, Combate 4$"

BattleDome_Text_Round1Match5::
	.string "Ronda 1, Combate 5$"

BattleDome_Text_Round1Match6::
	.string "Ronda 1, Combate 6$"

BattleDome_Text_Round1Match7::
	.string "Ronda 1, Combate 7$"

BattleDome_Text_Round1Match8::
	.string "Ronda 1, Combate 8$"

BattleDome_Text_Round2Match1::
	.string "Ronda 2, Combate 1$"

BattleDome_Text_Round2Match2::
	.string "Ronda 2, Combate 2$"

BattleDome_Text_Round2Match3::
	.string "Ronda 2, Combate 3$"

BattleDome_Text_Round2Match4::
	.string "Ronda 2, Combate 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal, Combate 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal, Combate 2$"

BattleDome_Text_FinalMatch::
	.string "¡Final del torneo!$"
