FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Bienvenido a la TIENDA DE BATALLA\n"
	.string "de PUEBLO PARDAL!\p"
	.string "Soy tu guía del Torneo KO a la Carta.$"

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.string "¿Deseas aceptar el reto del\n"
	.string "Torneo KO a la Carta?$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.string "¡Te esperamos en otra ocasión!$"

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.string "En la TIENDA DE BATALLA de PUEBLO\n"
	.string "PARDAL celebramos el Torneo KO a la\l"
	.string "Carta.\p"
	.string "Todos los participantes entran con un\n"
	.string "equipo de tres POKéMON.\p"
	.string "Los tres POKéMON deben colocarse en el\n"
	.string "orden en que van a aparecer.\p"
	.string "Durante el combate, los POKéMON\n"
	.string "aparecerán uno a uno en el orden\l"
	.string "predeterminado.\p"
	.string "Una vez que un POKéMON entra en\n"
	.string "combate, debe permanecer fuera hasta\l"
	.string "que se decida el combate.\p"
	.string "Si un combate permanece indeciso en\n"
	.string "tres turnos, se somete a evaluación.\p"
	.string "Si deseas interrumpir tu reto,\n"
	.string "guarda la partida.\p"
	.string "Si no guardas, no podrás continuar\n"
	.string "con tu reto.\p"
	.string "Si logras la hazaña de vencer a tres\n"
	.string "ENTRENADORES seguidos, te\l"
	.string "entregaremos un magnífico premio.$"

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de llevarte a la TIENDA DE\n"
	.string "BATALLA, debo guardar. ¿Está bien?$"

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Ofrecemos dos niveles de reto:\n"
	.string "Nivel 50 y Nivel Libre.\l"
	.string "¿Cuál eliges?$"

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Muy bien, ahora selecciona tus\n"
	.string "tres POKéMON, por favor.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "¡Mi querido retador!\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para participar.\p"
	.string "Además, no deben llevar objetos\n"
	.string "del mismo tipo.\p"
	.string "Los HUEVOS{STR_VAR_1} no son elegibles.\p"
	.string "Cuando hayas hecho los preparativos,\n"
	.string "por favor, vuelve.$"

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "¡Mi querido retador!\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para participar.\p"
	.string "Para calificar, debes traer tres\n"
	.string "tipos de POKéMON distintos.\p"
	.string "Además, no deben llevar objetos\n"
	.string "del mismo tipo.\p"
	.string "Los HUEVOS{STR_VAR_1} no son elegibles.\p"
	.string "Cuando hayas hecho los preparativos,\n"
	.string "por favor, vuelve.$"

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.string "Te acompañaré a la TIENDA DE BATALLA.$"

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "¡Mi querido retador!\p"
	.string "No guardaste la partida antes de\n"
	.string "apagar, ¿verdad?\p"
	.string "Es lamentable, pero eso ha dado lugar\n"
	.string "a tu descalificación del reto.\p"
	.string "Por supuesto, puedes empezar un\n"
	.string "reto nuevo.$"

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.string "¡Qué espléndido! ¡Has vencido a tres\n"
	.string "ENTRENADORES seguidos!$"

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.string "Espera un momento mientras guardo la\n"
	.string "partida.$"

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "En conmemoración de tus tres victorias\n"
	.string "seguidas, te entregamos este premio.$"

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.string "¿Oh?\n"
	.string "Tu MOCHILA parece estar llena.\p"
	.string "Te ruego que hagas espacio y vuelvas\n"
	.string "a por tu premio.$"

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.string "¡Muchas gracias por participar!\p"
	.string "Espera un momento mientras guardo la\n"
	.string "partida.$"

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.string "¡Te esperamos en otra ocasión!$"

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.string "Hemos estado esperando tu llegada.\p"
	.string "Antes de llevarte a la TIENDA DE\n"
	.string "BATALLA, debo guardar la partida.\l"
	.string "Por favor, espera.$"

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Bienvenido a la TIENDA DE BATALLA\n"
	.string "de PUEBLO VERDEGAL!\p"
	.string "Aquí se pone a prueba la confianza del\n"
	.string "ENTRENADOR hacia sus POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.string "¿Deseas aceptar el reto de la TIENDA\n"
	.string "DE BATALLA de PUEBLO VERDEGAL?$"

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.string "En la TIENDA DE BATALLA de PUEBLO\n"
	.string "VERDEGAL hay una regla fundamental\l"
	.string "que debe cumplirse.\p"
	.string "Los ENTRENADORES solo pueden\n"
	.string "cambiar sus POKéMON de entrada y salida.\p"
	.string "Por lo demás, los ENTRENADORES no\n"
	.string "pueden dar órdenes a sus POKéMON.\p"
	.string "Los POKéMON deben comportarse según\n"
	.string "su naturaleza y combatir por su cuenta.\p"
	.string "Debes confiar en tus POKéMON y\n"
	.string "vigilarlos.\p"
	.string "Si logras el honor de vencer a tres\n"
	.string "ENTRENADORES seguidos, te\l"
	.string "entregaremos un premio.\p"
	.string "Si quieres interrumpir tu reto,\n"
	.string "guarda la partida.\p"
	.string "Si no guardas antes de interrumpir,\n"
	.string "serás descalificado.$"

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.string "Cuando hayas fortalecido tu corazón\n"
	.string "y tus POKéMON, debes volver.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.string "Hay dos niveles de dificultad:\n"
	.string "Nivel 50 y Nivel Libre.\l"
	.string "¿Cuál eliges?$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.string "Vaya…\p"
	.string "No tienes los tres POKéMON\n"
	.string "necesarios para el reto.\p"
	.string "Para participar, debes presentar tres\n"
	.string "tipos de POKéMON distintos.\p"
	.string "Además, no deben llevar objetos\n"
	.string "del mismo tipo.\p"
	.string "Los HUEVOS{STR_VAR_1} no son elegibles.\p"
	.string "Vuelve cuando hayas hecho los\n"
	.string "preparativos.$"

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.string "Vaya…\p"
	.string "No tienes los three POKéMON\n"
	.string "necesarios para el reto.\p"
	.string "Para participar, debes presentar tres\n"
	.string "tipos de POKéMON distintos.\p"
	.string "Además, no deben llevar objetos\n"
	.string "del mismo tipo.\p"
	.string "Los HUEVOS{STR_VAR_1} no son elegibles.\p"
	.string "Vuelve cuando hayas hecho los\n"
	.string "preparativos.$"

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.string "Bien. Ahora debes seleccionar tus\n"
	.string "tres POKéMON.$"

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Debo guardar antes de llevarte a la\n"
	.string "TIENDA DE BATALLA. ¿Está bien?$"

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.string "Bien.\n"
	.string "Ahora, sígueme.$"

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.string "Me siento privilegiado por haber\n"
	.string "presenciado las hazañas de tus POKéMON.\p"
	.string "Se registrarán los resultados.\n"
	.string "Debo pedirte que esperes un momento.$"

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.string "Lograr tres victorias seguidas…\p"
	.string "Los lazos que unen tu corazón con tus\n"
	.string "POKéMON parecen firmes y verdaderos.$"

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.string "Se registrará tu hazaña.\n"
	.string "Debo pedirte que esperes un momento.$"

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.string "Por la hazaña de tus tres victorias\n"
	.string "seguidas, te entregamos este premio.$"

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.string "¡Bienvenido a la TIENDA DE BATALLA\n"
	.string "de CIUDAD PORTUAL!\p"
	.string "Soy tu guía del Torneo de\n"
	.string "Intercambio de Combate.$"

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.string "¿Deseas aceptar el reto del Torneo\n"
	.string "de Intercambio de Combate?$"

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.string "Aquí, en la TIENDA DE BATALLA de\n"
	.string "CIUDAD PORTUAL, celebramos eventos\l"
	.string "de Intercambio de Combate usando\l"
	.string "POKéMON de alquiler.\p"
	.string "Primero, te prestarán tres POKéMON\n"
	.string "específicamente para este evento.\p"
	.string "Usando los POKéMON de alquiler\n"
	.string "proporcionados, debes realizar un\l"
	.string "COMBATE INDIVIDUAL.\p"
	.string "Si ganas, se te permitirá intercambiar\n"
	.string "uno de tus POKéMON de alquiler.\p"
	.string "Repite este ciclo de combatir e\n"
	.string "intercambiar: si ganas tres veces\l"
	.string "seguidas, ganarás un magnífico premio.\p"
	.string "Si quieres interrumpir tu reto,\n"
	.string "guarda la partida.\p"
	.string "Si no guardas antes de interrumpir,\n"
	.string "serás descalificado.$"

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.string "Esperamos tu próxima visita.$"

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.string "¿Qué nivel deseas retar?\n"
	.string "¿Nivel 50 o Nivel 100?$"

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.string "Antes de empezar tu reto, debo\n"
	.string "guardar los datos. ¿Está bien?$"

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.string "Vale, guardaré tus POKéMON de forma\n"
	.string "segura mientras compites.$"

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.string "Por aquí, por favor.$"

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.string "¡Gracias por participar!\p"
	.string "Te devolveré tus POKéMON a cambio de\n"
	.string "nuestros POKéMON de alquiler.\p"
	.string "También debo guardar los resultados\n"
	.string "del evento. Por favor, espera.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.string "Te devolveré tus POKéMON a cambio de\n"
	.string "nuestros POKéMON de alquiler.$"

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.string "¡Enhorabuena!\n"
	.string "¡Has ganado tres combates seguidos!\p"
	.string "Te devolveré tus POKéMON a cambio de\n"
	.string "nuestros POKéMON de alquiler.\p"
	.string "También debo guardar los resultados\n"
	.string "del evento. Por favor, espera.$"

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.string "En reconocimiento de tus tres\n"
	.string "victorias seguidas, te concedemos\l"
	.string "este premio.$"

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.string "¿Oh?\n"
	.string "Parece que no tienes espacio para esto.\p"
	.string "Haz espacio en tu MOCHILA y\n"
	.string "avísame.$"

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.string "¡Te estábamos esperando!\p"
	.string "Antes de reanudar tu reto, debo\n"
	.string "guardar la partida.$"

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.string "Siento decirte esto, pero no guardaste\n"
	.string "antes de dejar de jugar la última vez.\p"
	.string "Como resultado, has sido descalificado\n"
	.string "de tu reto.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.string "Te devolveremos tus POKéMON personales.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.string "{PLAYER} recibió el premio\n"
	.string "{STR_VAR_1}.$"

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.string "Se muestran las reglas del Intercambio\n"
	.string "de Combate.$"

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué apartado quieres leer?$"

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.string "En un evento de Intercambio de Combate,\n"
	.string "puedes usar solo tres POKéMON.\p"
	.string "Tanto si alquilas como si intercambias,\n"
	.string "tu equipo no puede tener dos o más\l"
	.string "POKéMON del mismo tipo.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.string "Solo puedes intercambiar POKéMON con\n"
	.string "el ENTRENADOR que acabas de vencer.\p"
	.string "Solo puedes intercambiar por aquellos\n"
	.string "POKéMON que usó el ENTRENADOR vencido.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.string "Después de cada combate que ganes,\n"
	.string "puedes intercambiar por uno de los\l"
	.string "POKéMON de tu oponente vencido.\p"
	.string "No podrás intercambiar POKéMON con\n"
	.string "el tercer ENTRENADOR del evento.$"

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.string "Hay dos puntos clave que debes tener\n"
	.string "en cuenta al intercambiar POKéMON.\p"
	.string "Primero, al intercambiar, no puedes\n"
	.string "comprobar las estadísticas del\l"
	.string "POKéMON que vas a recibir.\p"
	.string "Segundo, los POKéMON de tu equipo\n"
	.string "se colocan en secuencia, según el\l"
	.string "orden en que los alquilaste.\p"
	.string "Esta secuencia no cambia incluso\n"
	.string "cuando se realizan intercambios.$"

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.string "Los POKéMON de la TIENDA DE BATALLA\n"
	.string "de CIUDAD PORTUAL son todos de alquiler.\p"
	.string "Todos los POKéMON de alquiler se\n"
	.string "mantienen al Nivel 30.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.string "Se muestran las reglas de la TIENDA\n"
	.string "DE BATALLA de PUEBLO VERDEGAL.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.string "¿Qué apartado quieres leer?$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.string "Aquí, en la TIENDA DE BATALLA de PUEBLO\n"
	.string "VERDEGAL, los POKéMON deben pensar y\l"
	.string "combatir por sí mismos.\p"
	.string "A diferencia de los salvajes, los\n"
	.string "POKéMON que viven con las personas se\l"
	.string "comportan de forma distinta según su\l"
	.string "naturaleza.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.string "Según su naturaleza, un POKéMON puede\n"
	.string "preferir atacar cueste lo que cueste.\p"
	.string "Otro POKéMON puede preferir\n"
	.string "protegerse de cualquier daño.\p"
	.string "Otro más puede disfrutar molestando o\n"
	.string "confundiendo a sus rivales.\p"
	.string "Según su naturaleza, un POKéMON tendrá\n"
	.string "movimientos favoritos en los que sea\l"
	.string "bueno usando.\p"
	.string "También puede que no le gusten ciertos\n"
	.string "movimientos en los que tenga dificultad.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.string "Hay movimientos ofensivos que infligen\n"
	.string "daño directo al rival.\p"
	.string "Hay movimientos defensivos que se usan\n"
	.string "para prepararse ante ataques enemigos\l"
	.string "o para recuperar PS, entre otras cosas.\p"
	.string "También hay otros movimientos algo\n"
	.string "extraños que pueden debilitar a los\l"
	.string "rivales con problemas de estado como\l"
	.string "el envenenamiento o la parálisis.\p"
	.string "Los POKéMON considerarán usar\n"
	.string "movimientos en estas tres categorías.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.string "Cuando no está bajo las órdenes de su\n"
	.string "ENTRENADOR, un POKéMON puede ser\l"
	.string "incapaz de usar ciertos movimientos de\l"
	.string "forma efectiva.\p"
	.string "Un POKéMON no es bueno usando ningún\n"
	.string "movimiento que no le guste.\p"
	.string "Si un POKéMON solo conoce movimientos\n"
	.string "que no coinciden con su naturaleza,\l"
	.string "a menudo será incapaz de alcanzar su\l"
	.string "potencial.$"

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.string "Según su naturaleza, un POKéMON puede\n"
	.string "empezar a usar movimientos que no\l"
	.string "coinciden con su naturaleza cuando se\l"
	.string "encuentre en apuros.\p"
	.string "Si un POKéMON empieza a comportarse de\n"
	.string "forma extraña en un apuro, vigílalo\l"
	.string "atentamente.$"

BattleTentLobby_Text_ExplainLevelRules:
	.string "En esta TIENDA DE BATALLA, los niveles\n"
	.string "de tus oponentes se ajustarán para\l"
	.string "coincidir con los niveles de tus\l"
	.string "POKéMON.\p"
	.string "Sin embargo, ningún ENTRENADOR al que\n"
	.string "te enfrentes tendrá POKéMON por debajo\l"
	.string "del Nivel 30.$"

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.string "Se muestran las reglas de la TIENDA\n"
	.string "DE BATALLA de PUEBLO VERDEGAL.$"
