PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPÁ: ¡Hola, {PLAYER}!\p"
	.string "Acabo de recibir una BAYA muy rara.\n"
	.string "Quiero que la tengas.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si ves BAYAS creciendo en tierra fértil,\n"
	.string "no dudes en cogerlas.\p"
	.string "Pero asegúrate de plantar una BAYA en\n"
	.string "el mismo sitio. Es lo mínimo que se puede\l"
	.string "hacer.\p"
	.string "Toma, te daré esto.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "A juzgar por tu pinta, debes de ser un\n"
	.string "ENTRENADOR, ¿verdad?\p"
	.string "Los ENTRENADORES suelen hacer que sus\n"
	.string "POKéMON lleven BAYAS.\p"
	.string "Depende de ti si prefieres cultivarlas\n"
	.string "o usarlas.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "Regaba las plantas todos los días.\n"
	.string "Han crecido muchas flores.\p"
	.string "Y también me han dado muchas BAYAS.\p"
	.string "¡Toma!\n"
	.string "¡Puedes quedarte con ella!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Voy a intentar con todas mis fuerzas\n"
	.string "conseguir BAYAS de distintos colores.\p"
	.string "¡Espero que tú también lo intentes!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Me pregunto qué color de BAYAS\n"
	.string "buscaré hoy.$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "Me encanta usar la máquina MACHACABAYAS,\n"
	.string "así que estoy coleccionando BAYAS.\p"
	.string "Te daré una, si quieres.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Deberías probar la máquina MACHACABAYAS\n"
	.string "con tus amigos.$"

Route114_Text_FunToThinkAboutBerries:
	.string "¿Qué BAYA debería plantar?\n"
	.string "¿Debería usar las BAYAS o guardarlas?\p"
	.string "Es divertido pensar en ello.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Las BAYAS crecen absorbiendo la luz\n"
	.string "del sol.\p"
	.string "Ayudamos a las BAYAS a crecer regándolas\n"
	.string "con regularidad.\p"
	.string "Es una expresión de amor, ¿no crees?$"

Route120_Text_YesYouUnderstand:
	.string "Sí, sí.\n"
	.string "Entiendes lo que quiero decir.\p"
	.string "Toma esto.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Pero supongo que es importante\n"
	.string "formarse una opinión propia…\p"
	.string "Puedes quedarte con esto.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Creo que esa BAYA es rara.\n"
	.string "Espero que la cuides con cariño.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Conseguiré más BAYAS del\n"
	.string "BAYÓLOGO.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Si lo piensas bien…\p"
	.string "Del mismo modo que un traje me sienta\n"
	.string "perfectamente a mí, una brisa fresca\l"
	.string "le sienta bien al mar.\p"
	.string "Y a ti, una BAYA te sienta de maravilla…\p"
	.string "¿Por qué será?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Si lo piensas bien…\p"
	.string "¡Es porque eres un ENTRENADOR!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Si lo piensas bien…\p"
	.string "Del mismo modo que la sencillez\n"
	.string "dignificada me sienta a mí, los\l"
	.string "{POKEBLOCK}S le sientan perfectamente a\l"
	.string "los POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Puedes llamarme BAYÓLOGO.\p"
	.string "Sueño con llenar el mundo de flores\n"
	.string "preciosas, así que cultivo BAYAS y\l"
	.string "se las reparto a todo el mundo.\p"
	.string "¡Te mereces una!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "¿Por qué ser tacaño?\n"
	.string "¡Toma otra!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Asegúrate de visitar la FLORISTERÍA\n"
	.string "PITIMINÍ, cerca de PUEBLO AZULIZA.\p"
	.string "¡Que el mundo se llene de flores!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "He terminado por hoy.\n"
	.string "Vuelve otro día.\p"
	.string "¡Que el mundo se llene de flores!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "La forma en que mi marido cultiva BAYAS,\n"
	.string "oh, es la mejor del mundo.\p"
	.string "Me enorgullece, eso sí.\p"
	.string "Por cierto, jovencito, ¿has oído\n"
	.string "algún buen refrán últimamente?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "¡Ah! ¡Qué refrán tan extraordinario!\n"
	.string "¡Es inspirador!\p"
	.string "Quiero que te quedes con esto.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "¡Oh! Es un buen refrán.\n"
	.string "Eres todo un personaje.\p"
	.string "Quiero que te quedes con esto.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nuestros cuatro nietos deberían llegar\n"
	.string "a ser más hábiles que mi marido.\p"
	.string "¡La alegría nunca abandona mi vida!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "¡Hola!\p"
	.string "Esta es la FLORISTERÍA PITIMINÍ.\n"
	.string "¡Repartiendo flores por todo el mundo!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, ¿te gustaría aprender\n"
	.string "sobre las BAYAS?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "¿Cómo te llamas?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Es un nombre bonito.\p"
	.string "{PLAYER}{KUN}, ¿te gustaría aprender\n"
	.string "sobre las BAYAS?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Las BAYAS crecen en árboles que solo\n"
	.string "prosperan en tierra fértil y blanda.\p"
	.string "Si coges algunas BAYAS, asegúrate de\n"
	.string "plantar una en la tierra fértil de\l"
	.string "nuevo.\p"
	.string "Una BAYA plantada pronto brotará,\n"
	.string "crecerá hasta convertirse en una planta,\l"
	.string "florecerá preciosamente y luego dará\l"
	.string "BAYAS de nuevo.\p"
	.string "Quiero ver el mundo entero lleno de\n"
	.string "flores preciosas.\l"
	.string "Ese es mi sueño.\p"
	.string "Por favor, ayúdame, {PLAYER}{KUN}.\n"
	.string "Planta BAYAS y llena el mundo de más\l"
	.string "flores.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Las flales traen tanta alegría a la\n"
	.string "gente, ¿no crees?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "¡Hola!\p"
	.string "Cuanto más mimas a las flores, más\n"
	.string "preciosas florecen.\p"
	.string "Seguro que te gusta cuidar flores.\n"
	.string "Estoy segura. Toma esto.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Mientras las plantas de BAYAS crecen,\n"
	.string "riégalas con el CUBO WAILMER.\p"
	.string "Ah, otra cosa.\p"
	.string "Si no recoges las BAYAS durante un\n"
	.string "tiempo, se caerán al suelo.\l"
	.string "Pero volverán a brotar.\p"
	.string "¿No es maravilloso?\n"
	.string "Es como si tuvieran voluntad de vivir.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "Estoy intentando ser como mis hermanas\n"
	.string "mayores. ¡Yo también cultivo flores!\p"
	.string "¡Toma!\n"
	.string "¡Es para ti!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Puedes plantar una BAYA y hacerla\n"
	.string "crecer, o puedes hacer que un POKéMON\l"
	.string "la lleve.\p"
	.string "Pero ahora tienen una máquina que mezcla\n"
	.string "distintas BAYAS y hace caramelos para\l"
	.string "POKéMON.\p"
	.string "Yo también quiero caramelos.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hola, ¿cómo te llamas?\p"
	.string "… … …  … … …  … … …\n"
	.string "Vale. ¡Qué nombre tan bonito!\p"
	.string "Me llamo KIRI.\p"
	.string "Mi mamá y mi papá me pusieron ese\n"
	.string "nombre para que creciera sana y con\l"
	.string "buen corazón.\l"
	.string "Eso es lo que desearon.\p"
	.string "Puedes quedarte con una de estas.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "¡KIRI te dará esta BAYA también!\n"
	.string "¡Me gusta muchísimo!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Me pregunto qué deseo se esconderá\n"
	.string "en tu nombre.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Primavera, verano, otoño e invierno.\p"
	.string "Si naces en primavera, ¿te gusta la\n"
	.string "primavera? Y si naces en verano, ¿te\l"
	.string "gusta el verano?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Entonces KIRI nació en otoño,\n"
	.string "¡así que me encanta el otoño!\p"
	.string "¿A ti qué estación te gusta?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "No importa…\p"
	.string "Hay tantas cosas que quiero saber…$"
