BerryBlender_Text_BlendWithTheBlendMaster:
	.string "LICUÓLOGO: ¡Así es!\n"
	.string "¡El LICUÓLOGO soy yo!\p"
	.string "¡Licuemos juntos y serás testigo\n"
	.string "del dominio que tengo en la licuación!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "LICUÓLOGO: ¡Hmmm! Así que deseas\n"
	.string "ver mi dominio en acción?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "¡Hmmm!\p"
	.string "¡Así que estás ocupado ahora!\p"
	.string "¡Pero no temas!\n"
	.string "¡Estaré aquí todo el día!\l"
	.string "¡Vuelve en cuanto puedas!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "¡Hmmm!\p"
	.string "¡No llevas ni una sola BAYA!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Vuelve con algunas BAYAS!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "¡Por supuesto!\n"
	.string "¡Por supuesto!\p"
	.string "Por cierto…\n"
	.string "¿Sabes cómo hacer {POKEBLOCK}S\l"
	.string "a partir de BAYAS?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "¡Hmmm!\p"
	.string "¡Ah, pero es un proceso sencillo!\p"
	.string "Cuando la flecha de la LICUABAYAS\n"
	.string "llegue a tu marcador, pulsa el\l"
	.string "Botón A.\p"
	.string "Eso es todo lo que tienes que hacer.\p"
	.string "Cuando veas con qué precisión pulso\n"
	.string "el Botón A, lo entenderás.$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "¡Perfecto!\p"
	.string "¡Empecemos, entonces!\p"
	.string "¡Todos junto al LICUÓLOGO,\n"
	.string "a las LICUABAYAS!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "¡Hmmm!\p"
	.string "¡Parece que no tienes el\n"
	.string "TUBO POKéCUBOS!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Consigue el TUBO POKéCUBOS y vuelve!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "¡Hmmm!\p"
	.string "¡Tu TUBO POKéCUBOS parece estar\n"
	.string "lleno!\p"
	.string "¡Estaré aquí todo el día!\n"
	.string "¡Usa algunos {POKEBLOCK}S y vuelve!$"

BerryBlender_Text_WhoaAwesome:
	.string "¡Vaya!\n"
	.string "¡Increíble!$"

BerryBlender_Text_WickedlyFast:
	.string "¡Rapidísimo!$"

BerryBlender_Text_WhatAnExpert:
	.string "¡Qué experto!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "Cuando licué con el LICUÓLOGO,\n"
	.string "¡hicimos unos {POKEBLOCK}S increíbles!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Ojos que siguen la flecha con una\n"
	.string "intensidad maquinal…\p"
	.string "Una mano que pulsa el Botón A con\n"
	.string "una precisión de relojería…\p"
	.string "Poseer estas cualidades hace que el\n"
	.string "LICUÓLOGO sea verdaderamente grande.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "Se dice que el LICUÓLOGO perfecciona\n"
	.string "su técnica en lo más profundo de las\l"
	.string "montañas.\p"
	.string "A veces, viene a CIUDAD CALAGUA\n"
	.string "a licuar BAYAS durante todo el día.$"
