CableClub_Text_WelcomeWhichCableClubService:
	.string "Bienvenido al CLUB CONEXIÓN\n"
	.string "POKéMON.\p"
	.string "¿Qué servicio de los que ofrecemos\n"
	.string "te gustaría usar?$"

CableClub_Text_WhichService:
	.string "¿Qué servicio de los que ofrecemos\n"
	.string "te gustaría usar?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Intercambia POKéMON con otro jugador\n"
	.string "usando un cable Game Link de GBA.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Puedes combatir contra otro ENTRENADOR\n"
	.string "usando un cable Game Link de GBA.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Puedes usar el RINCÓN RÉCORD con\n"
	.string "otros jugadores usando un cable\l"
	.string "Game Link de GBA.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Cerrar este menú.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "Para un COMBATE DOBLE debes tener\n"
	.string "al menos dos POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "Para intercambiar debes tener al\n"
	.string "menos dos POKéMON contigo.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "No se puede intercambiar un POKéMON\n"
	.string "que lleve equipada la BAYA ENIGMA.$"

gText_PleaseWaitForLink::
	.string "Espera un momento.\n"
	.string "… … Botón B: Cancelar$"

gText_ConfirmLinkWhenPlayersReady::
	.string "Cuando todos los jugadores estén listos…\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Iniciar conexión con {STR_VAR_1} jugadores.\n"
	.string "Botón A: Confirmar\l"
	.string "Botón B: Cancelar$"

gText_AwaitingLinkup::
	.string "Esperando conexión…\n"
	.string "… … Botón B: Cancelar$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Es necesario guardar la partida antes\n"
	.string "de conectar. ¿Estás de acuerdo?$"

CableClub_Text_PleaseEnter:
	.string "Pase.$"

CableClub_Text_DirectYouToYourRoom:
	.string "Te llevaré a tu sala ahora.$"

Text_SomeoneIsNotReadyToLink:
	.string "Alguien no está listo para conectar.\p"
	.string "Por favor, vuelve cuando todos\n"
	.string "hayan hecho los preparativos.$"

Text_LinkErrorPleaseReset:
	.string "Lo siento, ha habido un error de\n"
	.string "conexión…\p"
	.string "Reinicia la consola e inténtalo\n"
	.string "de nuevo.$"

Text_PlayersMadeDifferentSelections:
	.string "Parece que los compañeros de conexión\n"
	.string "han elegido opciones distintas.$"

CableClub_Text_PleaseVisitAgain:
	.string "Por favor, vuelve a visitarnos.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "El número de participantes no es\n"
	.string "correcto.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "El modo COMBATE INDIVIDUAL no se puede\n"
	.string "jugar con {STR_VAR_1} jugadores.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "El modo COMBATE DOBLE no se puede\n"
	.string "jugar con {STR_VAR_1} jugadores.$"

CableClub_Text_NeedFourPlayers:
	.string "Se necesitan cuatro jugadores para\n"
	.string "jugar a este modo de combate.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Comprueba el número de jugadores y\n"
	.string "vuelve a empezar.$"

Text_TerminateLinkConfirmation:
	.string "La conexión se interrumpirá si sales\n"
	.string "de la sala. ¿Estás de acuerdo?$"

Text_TerminateLinkPleaseWait:
	.string "Interrumpiendo conexión…\n"
	.string "Te escoltarán fuera de la sala.\l"
	.string "Espera un momento.$"

CableClub_Text_TooBusyToNotice:
	.string "Este ENTRENADOR está demasiado ocupado\n"
	.string "para darse cuenta…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "¡Olé! ¡He podido ver la FICHA DE\n"
	.string "ENTRENADOR de {STR_VAR_1}!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "¡Olé! ¡He podido ver la FICHA DE\n"
	.string "ENTRENADOR de {STR_VAR_1}!\p"
	.string "¡Es una ficha de {STR_VAR_2}!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Ocupad vuestros puestos y empezad\n"
	.string "el combate.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Tomad asiento y empezad el\n"
	.string "intercambio.$"

RecordCorner_Text_ThanksForComing:
	.string "Gracias por venir.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "Los datos de la FICHA DE ENTRENADOR\n"
	.string "se sobreescribirán.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "¡Espero volver a verte!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "Lo siento mucho.\p"
	.string "Todavía no estamos preparados para\n"
	.string "realizar intercambios con ENTRENADORES\l"
	.string "de regiones lejanas…$"

CableClub_Text_OtherTrainerNotReady:
	.string "El otro ENTRENADOR no está listo.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "Tienes al menos un POKéMON que no\n"
	.string "puedes llevar.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Tomad asiento y esperad.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} ha enviado un\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Lo siento, ha habido un error de\n"
	.string "transmisión.\p"
	.string "No puedes mezclar récords con las\n"
	.string "versiones japonesas de Rubí o Zafiro.\p"
	.string "Además, no puedes mezclar récords con\n"
	.string "la versión japonesa de Esmeralda y las\l"
	.string "versiones extranjeras de Rubí o Zafiro\l"
	.string "al mismo tiempo.$"

CableClub_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "conectado correctamente.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Se pide a los participantes que se\n"
	.string "acerquen al mostrador de recepción.$"

@ Unused
CableClub_Text_Hello:
	.string "¡Hola!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Espera un momento.$"

CableClub_Text_YouMayTradeHere::
	.string "Aquí puedes intercambiar tu POKéMON\n"
	.string "con otro ENTRENADOR.$"

CableClub_Text_YouMayBattleHere::
	.string "Aquí puedes combatir con tus amigos.$"

CableClub_Text_CanMakeBerryPowder::
	.string "De dos a cinco ENTRENADORES pueden\n"
	.string "hacer POLVO DE BAYA juntos.$"

CableClub_Text_CanMixRecords::
	.string "Los récords de dos a cuatro jugadores\n"
	.string "pueden mezclarse.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "Guía de los distintos servicios del\n"
	.string "CLUB INALÁMBRICO.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancela la opción seleccionada del\n"
	.string "MENÚ.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "¿Qué modo de combate te gustaría?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Vuelve al paso anterior.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "Para usar el servicio MACHACABAYAS,\n"
	.string "debes tener al menos una BAYA.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "Para entrar en la SALA UNIÓN debes\n"
	.string "tener al menos dos POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "Ningún POKéMON que lleve equipada la\n"
	.string "{STR_VAR_1} BAYA puede entrar en la\l"
	.string "SALA UNIÓN.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "Este es el CLUB INALÁMBRICO POKéMON,\n"
	.string "SALA UNIÓN.\p"
	.string "Lamentablemente, tu Adaptador\n"
	.string "Inalámbrico no está conectado\l"
	.string "correctamente.\p"
	.string "Por favor, vuelve cuando quieras.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "¡Disculpa!$"

CableClub_Text_PlayerIsWaiting:
	.string "Parece que {STR_VAR_1} está jugando\n"
	.string "ahora mismo.\l"
	.string "¡Adelante!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "Puedo explicarte las reglas de los\n"
	.string "juegos, si quieres.\p"
	.string "¿De qué juego te gustaría que te\n"
	.string "hablara?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“SALTO POKéMON”\p"
	.string "Haz que tu POKéMON salte la cuerda\n"
	.string "del LÁTIGO CEPEDA pulsando el\l"
	.string "Botón A.\p"
	.string "Solo los POKéMON pequeños de unas\n"
	.string "28 pulgadas o menos pueden participar.\p"
	.string "Los POKéMON que solo nadan, cavan\n"
	.string "o vuelan no son buenos saltando.\p"
	.string "Por tanto, esos POKéMON no pueden\n"
	.string "participar.\p"
	.string "Pasan cosas buenas si todos saltan\n"
	.string "a la vez.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“RECOGIDA DE BAYAS DODRIO”\p"
	.string "Ordena a las tres cabezas de DODRIO\n"
	.string "que recojan las BAYAS que caen.\p"
	.string "Pulsa derecha, arriba o izquierda en\n"
	.string "la Cruceta de control + para mover\l"
	.string "las cabezas.\p"
	.string "Para jugar a este juego debes tener\n"
	.string "un DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "Si quieres jugar, díselo al anciano\n"
	.string "que está a mi lado.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "¡Hola, bienvenido!\n"
	.string "¿Has venido a jugar usando la\l"
	.string "Comunicación Inalámbrica?\p"
	.string "¿Puedes esperar un momento?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "Muy bien, ¡vuelve cuando quieras!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "El Adaptador Inalámbrico no está\n"
	.string "conectado.\l"
	.string "¡Vuelve cuando lo hayas conectado!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "Muy bien, ¿a qué juego querías\n"
	.string "jugar?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "¿Qué POKéMON te gustaría usar?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Vale, todo listo.\n"
	.string "¡Que no te ganen!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "¿Te vas?\n"
	.string "¡Vuelve cuando quieras!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Parece que no tienes ningún POKéMON\n"
	.string "que pueda participar…\p"
	.string "¿Quieres que te explique qué tipos de\n"
	.string "POKéMON pueden participar?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "El “SALTO POKéMON” es para POKéMON\n"
	.string "de unas 28 pulgadas o menos.\p"
	.string "Los que no pueden participar son\n"
	.string "aquellos POKéMON que no pueden saltar.\p"
	.string "Ya sabes, como los POKéMON que solo\n"
	.string "nadan, cavan o vuelan.\p"
	.string "Eso es todo lo que necesitas saber.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "La RECOGIDA DE BAYAS DODRIO es un\n"
	.string "juego en el que solo puede participar\l"
	.string "DODRIO.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "¿Podrías volver a intentarlo desde\n"
	.string "el principio, por favor?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Bienvenido al RINCÓN DIRECTO del\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes interactuar directamente\n"
	.string "con tus amigos.\p"
	.string "¿A qué sala te gustaría entrar?$"

CableClub_Text_TradePokemon:
	.string "¿Te gustaría intercambiar POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "¿Qué modo de combate te gustaría\n"
	.string "jugar?$"

CableClub_Text_AccessRecordCorner:
	.string "¿Quieres acceder al RINCÓN RÉCORD?$"

CableClub_Text_UseBerryCrush:
	.string "¿Quieres usar el sistema\n"
	.string "MACHACABAYAS?$"

CableClub_Text_ExplainBattleModes:
	.string "Hay tres modos de combate.\p"
	.string "El COMBATE INDIVIDUAL es para dos\n"
	.string "ENTRENADORES con uno o más POKéMON\l"
	.string "cada uno.\p"
	.string "Cada ENTRENADOR puede tener un POKéMON\n"
	.string "en combate a la vez.\p"
	.string "El COMBATE DOBLE es para dos\n"
	.string "ENTRENADORES con dos o más POKéMON\l"
	.string "cada uno.\p"
	.string "Cada ENTRENADOR enviará dos POKéMON\n"
	.string "al combate a la vez.\p"
	.string "El COMBATE MÚLTIPLE es para cuatro\n"
	.string "ENTRENADORES con uno o más POKéMON\l"
	.string "cada uno.\p"
	.string "Cada ENTRENADOR puede tener un POKéMON\n"
	.string "en combate a la vez.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Decidid cuál de vosotros dos será\n"
	.string "el LÍDER.\p"
	.string "El otro jugador debe elegir\n"
	.string "“UNIRSE AL GRUPO.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Decidid cuál de vosotros cuatro será\n"
	.string "el LÍDER DEL GRUPO.\p"
	.string "Los otros jugadores deben elegir\n"
	.string "“UNIRSE AL GRUPO.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Decidid cuál de vosotros será el\n"
	.string "LÍDER DEL GRUPO.\p"
	.string "Los otros jugadores deben elegir\n"
	.string "“UNIRSE AL GRUPO.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Bienvenido a la SALA UNIÓN del\n"
	.string "CLUB INALÁMBRICO POKéMON.\p"
	.string "Aquí puedes interactuar directamente\n"
	.string "con otros ENTRENADORES, algunos de\l"
	.string "los cuales quizá ni siquiera conozcas.\p"
	.string "¿Te gustaría entrar en la SALA?$"

CableClub_Text_UnionRoomInfo:
	.string "Los ENTRENADORES de la SALA UNIÓN\n"
	.string "serán aquellos jugadores de tu\l"
	.string "alrededor que también hayan entrado\l"
	.string "en la SALA.\p"
	.string "Puedes hacer todo tipo de cosas aquí,\n"
	.string "como intercambiar saludos.\p"
	.string "Puedes usar dos POKéMON de hasta\n"
	.string "Nv. 30 para un combate uno contra uno.\p"
	.string "Puedes participar en un chat con\n"
	.string "de dos a cinco personas.\p"
	.string "O puedes registrar un POKéMON para\n"
	.string "intercambiarlo.\p"
	.string "¿Te gustaría entrar en la SALA?$"

CableClub_Text_EnjoyUnionRoom:
	.string "Espero que disfrutes tu estancia en\n"
	.string "la SALA UNIÓN.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "¡Hola!\n"
	.string "Me llamo TEALA.\p"
	.string "Debe ser tu primera vez aquí arriba.\p"
	.string "Te enseñaré cómo funciona el Sistema\n"
	.string "de Comunicación Inalámbrica.\p"
	.string "Primero, déjame enseñarte esta planta\n"
	.string "de nuestro CENTRO POKéMON.\p"
	.string "Por aquí, por favor.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "En la planta de arriba hay dos\n"
	.string "salas.\p"
	.string "Primero, la sala de la izquierda.\n"
	.string "Es la SALA UNIÓN.\p"
	.string "Puedes conectarte con ENTRENADORES de\n"
	.string "tu alrededor que también hayan entrado\l"
	.string "en la SALA UNIÓN.\p"
	.string "Con ellos puedes hacer cosas como\n"
	.string "chatear, combatir e intercambiar.\p"
	.string "Segundo, la sala de la derecha es el\n"
	.string "RINCÓN DIRECTO.\p"
	.string "Puedes intercambiar o combatir con\n"
	.string "tus amigos en esta sala.\p"
	.string "Si el Adaptador Inalámbrico no está\n"
	.string "conectado, puedes conectarte igual\l"
	.string "usando un cable Game Link de GBA.\p"
	.string "En ese caso, debes ir al RINCÓN\n"
	.string "DIRECTO.\p"
	.string "Espero que disfrutes del Sistema de\n"
	.string "Comunicación Inalámbrica.$"

CableClub_Text_AskAboutLinking:
	.string "¡Hola, {PLAYER}!\p"
	.string "Soy yo, TEALA, la encargada de la\n"
	.string "segunda planta del CENTRO POKéMON.\p"
	.string "¿Hay algo que quisieras preguntarme\n"
	.string "sobre la conexión?$"

CableClub_Text_ExplainWirelessClub:
	.string "Te explicaré cómo funciona el CLUB\n"
	.string "INALÁMBRICO POKéMON.\p"
	.string "En esta planta de arriba hay dos\n"
	.string "salas.\p"
	.string "Primero, la sala de la izquierda.\n"
	.string "Es la SALA UNIÓN.\p"
	.string "Puedes conectarte con ENTRENADORES de\n"
	.string "tu alrededor que también hayan entrado\l"
	.string "en la SALA UNIÓN.\p"
	.string "Con ellos puedes hacer cosas como\n"
	.string "chatear, combatir e intercambiar.\p"
	.string "Segundo, la sala de la derecha es el\n"
	.string "RINCÓN DIRECTO.\p"
	.string "Puedes intercambiar o combatir con\n"
	.string "tus amigos en esta sala.\p"
	.string "A veces puede que no encuentres a tus\n"
	.string "amigos en la SALA UNIÓN o en el\l"
	.string "RINCÓN DIRECTO.\p"
	.string "En ese caso, acércate a tus amigos.\p"
	.string "Si el Adaptador Inalámbrico no está\n"
	.string "conectado, puedes conectarte igual\l"
	.string "usando un cable Game Link de GBA.\p"
	.string "En ese caso, debes ir al RINCÓN\n"
	.string "DIRECTO.\p"
	.string "Espero que disfrutes del Sistema de\n"
	.string "Comunicación Inalámbrica.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "Espero que disfrutes del Sistema de\n"
	.string "Comunicación Inalámbrica.$"
