Text_PictureBookShelf:
	.string "Hay unos libros de ilustraciones de\n"
	.string "POKéMON.$"

Text_BookShelf:
	.string "Hay libros de todo tipo.$"

Text_PokemonCenterBookShelf:
	.string "¡Revistas de POKéMON!\n"
	.string "POKéMON AMIGO…\p"
	.string "MANUAL DE POKéMON…\n"
	.string "POKéMON ADORABLES…$"

Text_Vase:
	.string "Este jarrón parece caro…\n"
	.string "Miras dentro…\p"
	.string "Pero está vacío.$"

Text_EmptyTrashCan:
	.string "Está vacío.$"

Text_ShopShelf:
	.string "Los estantes rebosan de artículos\n"
	.string "de POKéMON de todo tipo.$"

Text_Blueprint:
	.string "¿Es un plano?\n"
	.string "¡Es demasiado complicado!$"
