gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2} de {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "CONCURSO$"

gContestRankNormal::
	.string "RANGO NORMAL$"

gContestRankSuper::
	.string "RANGO SÚPER$"

gContestRankHyper::
	.string "RANGO HIPER$"

gContestRankMaster::
	.string "RANGO MASTER$"

gContestLink::
	.string "CONEXIÓN$"

gContestCoolness::
	.string "CARISMA$"

gContestBeauty::
	.string "BELLEZA$"

gContestCuteness::
	.string "DULZURA$"

gContestSmartness::
	.string "INGENIO$"

gContestToughness::
	.string "DUREZA$"

gContestPaintingCool1::
	.string "Superguay sin parar--\n"
	.string "el inestimable {STR_VAR_1}$"

gContestPaintingCool2::
	.string "¡Eh, tú!\n"
	.string "El guapísimo POKéMON {STR_VAR_1}$"

gContestPaintingCool3::
	.string "El maravilloso, estupendo y\n"
	.string "magnífico {STR_VAR_1}$"

gContestPaintingBeauty1::
	.string "La última Venus de este siglo--\n"
	.string "la hermosa {STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "La deslumbrante y brillante\n"
	.string "sonrisa de {STR_VAR_1}$"

gContestPaintingBeauty3::
	.string "El súper ídolo del CENTRO POKéMON--\n"
	.string "el incomparable {STR_VAR_1}$"

gContestPaintingCute1::
	.string "El adorable y dulce {STR_VAR_1}$"

gContestPaintingCute2::
	.string "El retrato ganador del\n"
	.string "precioso {STR_VAR_1}$"

gContestPaintingCute3::
	.string "¡Guíñanos un ojo!\n"
	.string "El monísimo POKéMON {STR_VAR_1}$"

gContestPaintingSmart1::
	.string "El maestro del ingenio--\n"
	.string "el sabio POKéMON {STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}--el elegido\n"
	.string "por encima de todos los POKéMON$"

gContestPaintingSmart3::
	.string "El excelente {STR_VAR_1} en\n"
	.string "su momento de elegancia$"

gContestPaintingTough1::
	.string "El musculoso y poderoso\n"
	.string "velocista {STR_VAR_1}$"

gContestPaintingTough2::
	.string "El fuerte, más fuerte y\n"
	.string "el más fuerte de todos: {STR_VAR_1}$"

gContestPaintingTough3::
	.string "El hiper POKéMON\n"
	.string "superduro {STR_VAR_1}$"
