gTest_MissedTurn::
	.string "Turno perdido$"

gText_LinkStandby4::
	.string "¡Conexión en espera!$"

gText_WinnerIsPlayersMonCongrats::
	.string "El ganador es {STR_VAR_2} de {STR_VAR_1}.\n"
	.string "¡Enhorabuena!$"

gText_WinnerIsPlayersMon::
	.string "El ganador es {STR_VAR_2} de {STR_VAR_1}.{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Evaluación primaria: N.º {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Evaluación secundaria: N.º {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Evento fijado: N.º {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "El movimiento más usado:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "El POKéMON más impresionante:\n"
	.string "{STR_VAR_2} de {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Evento fijado: N.º {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "No se hará un programa de TV por\n"
	.string "conexión porque el ENTRENADOR perdió.{PAUSE_UNTIL_PRESS}$"
