EventTicket_Text_OldSeaMapTooFar:
	.string "¿Qué tal, jovencito?\p"
	.string "¿Cómo? ¿Eres tú quien se supone que\n"
	.string "tiene un viejo mapa hecho jirones?\p"
	.string "Déjame verlo.\n"
	.string "… … … … … …\p"
	.string "Vaya, esto está bastante lejos.\n"
	.string "Me temo que no puedo ayudarte…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BABOR: ¡Espera un momento!\p"
	.string "¿Cómo se te ocurre rechazar a\n"
	.string "alguien a quien le debo tanto?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, lo siento mucho.\p"
	.string "Viniste a mí buscando mi ayuda,\n"
	.string "y casi te dimos calabazas.\p"
	.string "Bueno, déjame enmendar las cosas.\p"
	.string "¡Zarparemos enseguida, por supuesto!\p"
	.string "¡Vamos a encontrar esta isla en\n"
	.string "este MAPA VIEJO!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "¿Eres tú quien ha traído ese\n"
	.string "ticket extraño?\p"
	.string "Adonde intentas ir es una isla\n"
	.string "que está muy, muy lejos.\p"
	.string "Nadie sabe qué te espera allí…\p"
	.string "¡Solo de pensarlo se me enciende\n"
	.string "la sangre de marinero!\p"
	.string "¡Sube a bordo, jovencito!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "El CAPITÁN BABOR puede ser\n"
	.string "terriblemente voluble…\p"
	.string "¿Quieres volver a CIUDAD CALAGUA?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Vaya isla más rara, ¿eh?\n"
	.string "¿Quieres volver a CIUDAD CALAGUA?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "¿Eres tú quien ha traído esos\n"
	.string "tickets extraños?\p"
	.string "… … …Hum.\p"
	.string "Estos tickets te llevarán a islas\n"
	.string "que están muy, muy lejos.\p"
	.string "Nadie sabe qué te espera allí,\n"
	.string "ni qué puede pasar.\p"
	.string "¡Solo de pensarlo se me enciende\n"
	.string "la sangre de marinero!\p"
	.string "¡Sube a bordo, jovencito!\n"
	.string "¿Adónde zarpamos primero?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "¿Has… Has oído eso?\n"
	.string "Ese gruñido grave que venía de\l"
	.string "las profundidades.\p"
	.string "¿Estás seguro de que es seguro?\n"
	.string "¿Crees que deberíamos irnos?$"

FarawayIsland_Entrance_Text_Sign:
	.string "La escritura se desvanece como si se\n"
	.string "hubiera escrito hace mucho tiempo…\p"
	.string "“…bre, día 6\n"
	.string "Si algún humano…pone un pie aquí…\l"
	.string "de nuevo…que sea una persona de\l"
	.string "buen corazón…\p"
	.string "…con esa esperanza, me mar…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
