EventTicket_Text_ShowOldSeaMap:
	.string "El ferry a CIUDAD PORTUAL es…\p"
	.string "¿Perdón?\n"
	.string "¿Podemos zarpar hasta este lugar del mapa?\p"
	.string "Conozco a alguien que te podrá ayudar mejor.\n"
	.string "Por favor, espera.$"

EventTicket_Text_ThatPass:
	.string "El ferry a CIUDAD PORTUAL es…\p"
	.string "¿Oh?\n"
	.string "Ese TICKET…$"

EventTicket_Text_ShowEonTicket:
	.string "Oye, colega, ¿eres tú quien ha traído\n"
	.string "ese TICKET tan raro?\p"
	.string "Te diré que intentas llegar a una\n"
	.string "pequeña isla perdida muy al sur.\p"
	.string "Nadie sabe con qué nos encontraremos\n"
	.string "cuando lleguemos allí.\l"
	.string "¡Eso me pone los pelos de punta!\p"
	.string "¡Todos a bordo!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Oye, colega, no hay nada que ver ni hacer\n"
	.string "en esta isla sin importancia.\p"
	.string "¿Qué tal si zarpamos de vuelta a CIUDAD CALAGUA?$"

EventTicket_Text_SailHome:
	.string "Oye, claro, entonces.\n"
	.string "¡Zarparemos de vuelta a casa!$"

EventTicket_Text_AsYouLike:
	.string "Oye, claro, como quieras.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Todos los sueños son solo otra realidad.\n"
	.string "Nunca lo olvides…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Aquellos cuyos recuerdos se desvanecen\n"
	.string "buscan grabarlos en sus corazones…”$"
