@ Battle Tower
gText_AnabelWonSilver::
	.string "Es una verdadera pena…$"

gText_AnabelDefeatSilver::
	.string "Vale, lo entiendo…$"

gText_AnabelWonGold::
	.string "Lo siento mucho…$"

gText_AnabelDefeatGold::
	.string "Gracias…$"

@ Battle Dome
gText_TuckerWonSilver::
	.string "¡Ajajaja! ¿No te da vergüenza?\n"
	.string "¡Todo el mundo está mirando!$"

gText_TuckerDefeatSilver::
	.string "Grr…\n"
	.string "¿Pero qué…$"

gText_TuckerWonGold::
	.string "¡Mi título de ASTRO CÚPULA\n"
	.string "no es solo de adorno!$"

gText_TuckerDefeatGold::
	.string "¡Ajajaja!\n"
	.string "¡Eres inspirador!$"

@ Battle Factory
gText_NolandWonSilver::
	.string "¡Así se hace!\n"
	.string "¿Ha sido una buena lección, eh?$"

gText_NolandDefeatSilver::
	.string "¡Buen trabajo!\n"
	.string "¡Tú sí que sabes lo que haces!$"

gText_NolandWonGold::
	.string "¡Oye, oye, oye!\n"
	.string "¿Ya has terminado?$"

gText_NolandDefeatGold::
	.string "¿Qué ha pasado aquí?$"

@ Battle Pike
gText_LucyWonSilver::
	.string "Hum…$"

gText_LucyDefeatSilver::
	.string "Ugh…$"

gText_LucyWonGold::
	.string "¡Ja!$"

gText_LucyDefeatGold::
	.string "¡Maldición!$"

@ Battle Arena
gText_GretaWonSilver::
	.string "¡Oye!\n"
	.string "¡Tendrás que esforzarte más que eso!$"

gText_GretaDefeatSilver::
	.string "¡No puede ser!\n"
	.string "¡Bien hecho!$"

gText_GretaWonGold::
	.string "¡Je, je!\n"
	.string "¿Qué te esperabas?$"

gText_GretaDefeatGold::
	.string "¿Eh?\n"
	.string "¿¿Hablas en serio??$"

@ Battle Palace
gText_SpenserWonSilver::
	.string "Tus POKéMON son unos flojos\n"
	.string "porque tú eres un ENTRENADOR flojo.$"

gText_SpenserDefeatSilver::
	.string "Ah…\n"
	.string "Esto es otra cosa…$"

gText_SpenserWonGold::
	.string "¡Guajajaja!\n"
	.string "¡Compañeros, no tenemos nada que temer!$"

gText_SpenserDefeatGold::
	.string "¡Guah!\n"
	.string "¡Jajajaja!$"

@ Battle Pyramid
gText_BrandonWonSilver::
	.string "¡Eh! ¿Qué te pasa?\n"
	.string "¡Demuéstrame algo de esfuerzo!\l"
	.string "¡Levántate!$"

gText_BrandonDefeatSilver::
	.string "¡Eso es! ¡Lo has hecho genial!\n"
	.string "¡Te has esforzado mucho por esto!$"

gText_BrandonWonGold::
	.string "¡Eh! ¡No te rindas ahora!\n"
	.string "¡Levántate!\l"
	.string "¡No pierdas la fe en ti mismo!$"

gText_BrandonDefeatGold::
	.string "¡Eso es! ¡Lo has logrado!\n"
	.string "¡No has dejado de esforzarte\l"
	.string "por esto!$"
