LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Este es el RINCÓN DE LA LOTERÍA POKéMON.\p"
	.string "Todos los clientes de nuestro CENTRO\l"
	.string "COMERCIAL pueden sacar un BILLETE\l"
	.string "de la LOTERÍA POKéMON.\p"
	.string "Si el número del BILLETE coincide con\n"
	.string "el número ID de alguno de tus POKéMON,\l"
	.string "recibirás un fabuloso regalo.\p"
	.string "¿Quieres sacar un BILLETE\n"
	.string "de la LOTERÍA POKéMON?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Por favor, vuelve mañana.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Por favor, vuelve a visitarnos.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Elige un BILLETE de la LOTERÍA.\n"
	.string "…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "El número del BILLETE es {STR_VAR_1}.\p"
	.string "Voy a comprobar si coincide con\n"
	.string "el número ID de alguno de tus\l"
	.string "POKéMON. Espera un momento.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "¡Enhorabuena!\p"
	.string "¡El número ID del {STR_VAR_1} de\n"
	.string "tu equipo coincide con el número\l"
	.string "de tu BILLETE!$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "¡Enhorabuena!\p"
	.string "¡El número ID del {STR_VAR_1} que\n"
	.string "tienes guardado en el PC coincide\l"
	.string "con el número de tu BILLETE!$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Lo siento.\n"
	.string "Ninguno de los números coincide.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Dos dígitos coinciden. ¡Has ganado\n"
	.string "el tercer premio!\l"
	.string "¡Has ganado {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Tres dígitos coinciden. ¡Has ganado\n"
	.string "el segundo premio!\l"
	.string "¡Has ganado {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Cuatro dígitos coinciden. ¡Has ganado\n"
	.string "el primer premio!\l"
	.string "¡Has ganado {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "¡Dios mío, los cinco dígitos\n"
	.string "coinciden!\p"
	.string "¡Has ganado el premio gordo!\n"
	.string "¡Has ganado {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "¿Oh?\n"
	.string "Parece que no tienes espacio para esto.\p"
	.string "Haz espacio en tu MOCHILA y\n"
	.string "vuelve a hablar conmigo.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "¿{PLAYER}?\n"
	.string "Sí, te estaba esperando.\p"
	.string "Este es el premio que te guardamos.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Por favor, vuelve a visitarnos.$"
