GiddyText_SoPretty::
	.string " ¡tan bonito!$"

GiddyText_SoDarling::
	.string " ¡tan adorable!$"

GiddyText_SoRelaxed::
	.string " ¡tan relajado!$"

GiddyText_SoSunny::
	.string " ¡tan radiante!$"

GiddyText_SoDesirable::
	.string " ¡tan deseable!$"

GiddyText_SoExciting::
	.string " ¡tan emocionante!$"

GiddyText_SoAmusing::
	.string " ¡tan divertido!$"

GiddyText_SoMagical::
	.string " ¡tan mágico!$"

GiddyText_Is::
	.string " es$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "¿No te parece?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Me apetece tanto irme de vacaciones.\n"
	.string "¿Conoces algún sitio bonito?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "¡He comprado lápices de 120 colores!\n"
	.string "¿No te parece genial?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "¿No sería maravilloso flotar\n"
	.string "sobre una nube de burbujas?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Cuando escribes en la arena de la playa,\n"
	.string "las olas lo borran todo. Me entristece.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "¿Cómo será el fondo del mar?\n"
	.string "¡Me encantaría ir alguna vez!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Cuando ves la puesta de sol, ¿no te dan\n"
	.string "ganas de volver a casa?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Tumbado en la hierba verde…\n"
	.string "¡Oh, qué maravilla!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "¡Las BASES SECRETAS son una maravilla!\n"
	.string "¿No sientes la emoción?$"
