MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "Este movimiento solo se puede\n"
	.string "aprender una vez. ¿Estás seguro?$"

MoveTutor_Text_SwaggerTeach:
	.string "¡Ja! Mi POKéMON es imbatible.\n"
	.string "¡Es más guay que ningún otro!\p"
	.string "Iba por ahí pavoneándome con aire\n"
	.string "de superioridad cuando el PRESIDENTE\l"
	.string "me echó una buena reprimenda.\p"
	.string "Desde entonces, se me ha quitado\n"
	.string "la chulería de encima.\p"
	.string "Si quieres, puedo enseñar el movimiento\n"
	.string "CONTONEO a uno de tus POKéMON.$"

MoveTutor_Text_SwaggerDeclined:
	.string "¿Cómo? ¿Que no? ¿No sabes apreciar\n"
	.string "el buen ambiente?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "¡Muy bien! ¿Qué POKéMON quiere\n"
	.string "aprender a usar CONTONEO?$"

MoveTutor_Text_SwaggerTaught:
	.string "De ahora en adelante, me limitaré\n"
	.string "a alabar a mi POKéMON sin pavonearme.$"

MoveTutor_Text_RolloutTeach:
	.string "¿Sabías que desde aquí se puede ir\n"
	.string "muy lejos en esa dirección sin\l"
	.string "cambiar de rumbo?\p"
	.string "Igual hasta yo podría llegar\n"
	.string "rodando.\p"
	.string "¿Crees que a tu POKéMON también\n"
	.string "le apetecería rodar?\p"
	.string "Si quieres, puedo enseñarle el movimiento\n"
	.string "DESENROLLAR a uno.$"

MoveTutor_Text_RolloutDeclined:
	.string "No seas tímido.\n"
	.string "¡Vamos, rueda!$"

MoveTutor_Text_RolloutWhichMon:
	.string "¡Je, je! ¡Por supuesto! Sería estupendo\n"
	.string "que el POKéMON se pareciera a mí.$"

MoveTutor_Text_RolloutTaught:
	.string "Rodar por la hierba me pone de buen\n"
	.string "humor. ¡Vamos, rueda conmigo!$"

MoveTutor_Text_FuryCutterTeach:
	.string "Hay un movimiento que se hace más\n"
	.string "potente cuantas más veces se use seguidas.\p"
	.string "Es de tipo BICHO y es tremendamente\n"
	.string "chulo.\p"
	.string "Se llama CORTE FURIA.\n"
	.string "¿Quieres que se lo enseñe a un POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "Parece que no conectamos.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "¡Yupi!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_FuryCutterTaught:
	.string "¡Me emociona ver si el movimiento\n"
	.string "sigue acertando una y otra vez!$"

MoveTutor_MimicTeach:
	.string "¡Eh, jovencito!\p"
	.string "Yo también soy joven, pero imito\n"
	.string "los modales y la forma de hablar de\l"
	.string "los ancianos de este pueblo.\p"
	.string "¿Qué me dices, jovencito?\n"
	.string "¿Aceptarías que te enseñara el movimiento\l"
	.string "MIMÉTICO?$"

MoveTutor_MimicDeclined:
	.string "¡Oh, vaya! ¡Quería enseñar MIMÉTICO\n"
	.string "a tu POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "¡Fwofwo! ¡Así se habla!\n"
	.string "Muéstrame el POKéMON al que\l"
	.string "quieres que le enseñe.$"

MoveTutor_Text_MimicTaught:
	.string "MIMÉTICO es un movimiento muy\n"
	.string "profundo.\p"
	.string "¿Serías capaz de ejecutarlo a la\n"
	.string "perfección, igual que yo…?$"

MoveTutor_Text_MetronomeTeach:
	.string "¡Quiero un montón de cosas!\n"
	.string "Pero me he gastado la paga…\p"
	.string "¿No sería genial que existiera un\n"
	.string "hechizo para hacer aparecer dinero\l"
	.string "moviendo un dedo?\p"
	.string "Si quieres, puedo enseñarle a tu POKéMON\n"
	.string "el movimiento METRÓNOMO.\p"
	.string "No aparecerá dinero, pero tu POKéMON\n"
	.string "moverá un dedo. ¿Te parece bien?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Vale. Si cambias de opinión,\n"
	.string "aquí estaré.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "¡De acuerdo! ¡Se lo enseñaré!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_MetronomeTaught:
	.string "Cuando un POKéMON mueve el dedo\n"
	.string "como un METRÓNOMO, pasan un montón\l"
	.string "de cosas buenas.\p"
	.string "¿No sería genial que nosotros también\n"
	.string "pudiéramos usarlo?$"

MoveTutor_Text_SleepTalkTeach:
	.string "¡Hum! Mi mujer se mantiene despierta\n"
	.string "gracias a PODER OCULTO.\p"
	.string "Debería echarse una siestecita como yo\n"
	.string "y usar SONÁMBULO.\p"
	.string "Puedo enseñarle a tu POKéMON a usar\n"
	.string "SONÁMBULO. ¿Te interesa?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, muy bien, muy bien. Tú también\n"
	.string "quieres mantenerte despierto con PODER\l"
	.string "OCULTO…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "¡Ah, un niño con buen criterio!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_SleepTalkTaught:
	.string "Nunca he acertado el truco de la\n"
	.string "moneda de mi mujer.\p"
	.string "Me haría feliz acertarlo incluso\n"
	.string "mientras uso SONÁMBULO…$"

MoveTutor_Text_SubstituteTeach:
	.string "Cuando contemplo el mundo desde aquí\n"
	.string "arriba, en la azotea…\p"
	.string "Me pregunto qué tal sería haber más\n"
	.string "de una versión de mí misma para poder\l"
	.string "disfrutar de todo tipo de vidas.\p"
	.string "Por supuesto, es imposible.\n"
	.string "Ji, ji…\p"
	.string "¡Ya sé! ¿Te gustaría que uno de tus\n"
	.string "POKéMON aprendiera SUSTITUTO?$"

MoveTutor_Text_SubstituteDeclined:
	.string "¿Oh, que no?\p"
	.string "Con SUSTITUTO, un POKéMON puede crear\n"
	.string "una copia de sí mismo, ¿sabes?$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Ji, ji…\n"
	.string "¿A qué POKéMON quieres que le enseñe\l"
	.string "SUSTITUTO?$"

MoveTutor_Text_SubstituteTaught:
	.string "¡Nosotros, los seres humanos, deberíamos\n"
	.string "disfrutar al máximo de nuestras vidas!\p"
	.string "¡Espero que tú también lo hagas!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "¡No puedo más!\p"
	.string "¡Es totalmente desesperante!\p"
	.string "Soy un ENTRENADOR de tipo LUCHA,\n"
	.string "así que no puedo ganar en el GIMNASIO\l"
	.string "de CIUDAD ALGARIA por mucho que lo intente.\p"
	.string "¡Argh! ¡Puñetazo! ¡Puñetazo! ¡Puñetazo!\n"
	.string "¡Puñetazo! ¡Puñetazo! ¡Puñetazo!\p"
	.string "Oye, ¡no me mires así!\n"
	.string "¡Solo estoy golpeando el suelo!\p"
	.string "Oye, ¿quieres que le enseñe a tu\n"
	.string "POKéMON el movimiento PUÑO DINÁMICO?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "¡Maldita sea! ¿También te estás\n"
	.string "burlando de mí? ¡Puñetazo! ¡Puñetazo!\l"
	.string "¡Puñetazo!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "¿Qué? ¿Que sí? ¡Eres buena persona!\n"
	.string "¿A qué POKéMON se lo enseño?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "¡Quiero que ganes en el GIMNASIO de\n"
	.string "CIUDAD ALGARIA usando ese PUÑO DINÁMICO!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Suspiro…\p"
	.string "El LÍDER del GIMNASIO de ARRECÍPOLIS\n"
	.string "es realmente adorable.\p"
	.string "Pero eso también significa que tengo\n"
	.string "muchas rivales por su atención.\p"
	.string "Tiene un encanto de DOBLE FILO.\n"
	.string "Ni siquiera he logrado llamar su atención.\p"
	.string "Por favor, déjame enseñarle a tu POKéMON\n"
	.string "el movimiento DOBLE FILO.$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\n"
	.string "Hasta tú me has rechazado…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Vale, ¿a qué POKéMON le enseño\n"
	.string "DOBLE FILO?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "¡No viviré más por el amor!\n"
	.string "¡Me volveré dura!$"

MoveTutor_Text_ExplosionTeach:
	.string "No pienso quedarme en este pueblo\n"
	.string "de perdidos para siempre.\p"
	.string "Ya verás, me iré a la ciudad y me\n"
	.string "convertiré en una estrella.\p"
	.string "¡De verdad, voy a causar una EXPLOSIÓN\n"
	.string "de popularidad enorme!\p"
	.string "Si has oído eso, te enseñaré EXPLOSIÓN\n"
	.string "a tu POKéMON con mucho gusto.$"

MoveTutor_Text_ExplosionDeclined:
	.string "¡Gaaah! ¿Me estás rechazando porque\n"
	.string "vivo en el campo?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "¡Vale! ¡Una EXPLOSIÓN!\n"
	.string "¿Qué POKéMON quiere explotar?$"

MoveTutor_Text_ExplosionTaught:
	.string "Durante mucho tiempo he enseñado a los\n"
	.string "POKéMON a usar EXPLOSIÓN, pero todavía\l"
	.string "no he logrado provocar mi propia\l"
	.string "EXPLOSIÓN…\p"
	.string "Quizá sea porque, en el fondo, prefiero\n"
	.string "quedarme aquí…$"
