gText_ObtainedTheItem::
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La MOCHILA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} ha guardado {STR_VAR_2}\n"
	.string "en el bolsillo {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} ha encontrado {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Qué pena!\n"
	.string "La MOCHILA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} ha guardado {STR_VAR_2}\n"
	.string "en la MOCHILA.$"

gText_ObtainedTheDecor::
	.string "¡Has obtenido {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "¡Qué pena! No hay espacio para\n"
	.string "otro {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} ha sido transferido\n"
	.string "al PC.$"
