Text_BootUpPC:
	.string "{PLAYER} ha encendido el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC:
	.string "Accediendo al PC de alguien.$"

gText_StorageSystemOpened:
	.string "Sistema de Almacenamiento de Pokémon abierto.$"

gText_AccessedPlayersPC:
	.string "Accediendo al PC de {PLAYER}.$"

gText_AccessedLanettesPC:
	.string "Accediendo al PC de DONPOLLO.$"
