gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} ha sido transferido al\n"
	.string "PC de alguien.\p"
	.string "Ha sido colocado en la\n"
	.string "CAJA “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} ha sido transferido al\n"
	.string "PC de AREDIA.\p"
	.string "Ha sido colocado en la\n"
	.string "CAJA “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La CAJA “{STR_VAR_3}” del\n"
	.string "PC de alguien estaba llena.\p"
	.string "{STR_VAR_2} ha sido transferido a la\n"
	.string "CAJA “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La CAJA “{STR_VAR_3}” del\n"
	.string "PC de AREDIA estaba llena.\p"
	.string "{STR_VAR_2} ha sido transferido a la\n"
	.string "CAJA “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "¡No hay más espacio para Pokémon!\p"
	.string "¡Las CAJAS POKéMON están llenas y\n"
	.string "no pueden aceptar más!$"

gText_NicknameThisPokemon::
	.string "¿Quieres ponerle un mote a\n"
	.string "este {STR_VAR_1}?$"
