gText_WouldYouLikeToRestYourPkmn::
	.string "Hola, bienvenido al\n"
	.string "CENTRO POKéMON.\p"
	.string "Nos encargamos de curar a tus\n"
	.string "Pokémon y devolverles la energía.\p"
	.string "¿Quieres que curemos a tus Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Vale, déjame tus Pokémon\n"
	.string "un momento.$"

gText_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\p"
	.string "Hemos devuelto la energía a\n"
	.string "tus Pokémon.$"

gText_WeHopeToSeeYouAgain::
	.string "¡Esperamos verte de nuevo!$"

gText_WelcomeCutShort::
	.string "Hola, bienvenido al\n"
	.string "CENTRO POKéMON.\p"
	.string "Nos encargamos de curar a tus\n"
	.string "Pokémon y devolverles la energía.\p"
	.string "¿Quieres...?$"

gText_NoticesGoldCard::
	.string "E-esa tarjeta...\n"
	.string "¿Será...? ¡¿La TARJETA ORO?!\p"
	.string "¡Oh, el color dorado es brillante!\n"
	.string "¡Las cuatro estrellas parecen brillar!\p"
	.string "He visto a varios entrenadores con\n"
	.string "una TARJETA PLATA antes, pero, {PLAYER},\l"
	.string "¡eres el primer entrenador al que veo\l"
	.string "con una TARJETA ORO!\p"
	.string "Vale, {PLAYER}, por favor, ¡permíteme\n"
	.string "el honor de curar a tus Pokémon!$"

gText_YouWantTheUsual::
	.string "¡Me encanta verte, {PLAYER}!\n"
	.string "¿Quieres lo de siempre, verdad?$"

gText_IllTakeYourPkmn2::
	.string "Vale, déjame tus Pokémon\n"
	.string "un momento.$"

gText_ThankYouForWaiting::
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "¡Esperamos verte de nuevo!$"
