gBirchDexRatingText_AreYouCurious::
	.string "PROF. ABEDUL: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Tienes curiosidad por saber cómo va\n"
	.string "tu POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "¿Mmm? Oh, no has atrapado suficientes\n"
	.string "POKéMON como para que merezca la pena.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Mmm...\p"
	.string "Así que has visto {STR_VAR_1} POKéMON,\n"
	.string "y has atrapado {STR_VAR_2} POKéMON...$"

gBirchDexRatingText_LessThan10::
	.string "Ve más a las zonas de hierba alta y\n"
	.string "busca POKéMON con más cuidado.$"

gBirchDexRatingText_LessThan20::
	.string "Supongo que le estás cogiendo el truco.\n"
	.string "Pero, a partir de aquí se pone más\l"
	.string "difícil.$"

gBirchDexRatingText_LessThan30::
	.string "Algunos POKéMON solo aparecen en\n"
	.string "ciertas zonas.\l"
	.string "Debes ser persistente.$"

gBirchDexRatingText_LessThan40::
	.string "Bueno, podría tener más cantidad,\n"
	.string "pero esto ya se parece más a una\l"
	.string "POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Esto está saliendo bastante bien.\n"
	.string "Sigue con el esfuerzo.$"

gBirchDexRatingText_LessThan60::
	.string "¿Estás usando alguna CAÑA?\n"
	.string "Hay muchos POKéMON en el mar.$"

gBirchDexRatingText_LessThan70::
	.string "En vez de solo atrapar POKéMON,\n"
	.string "¿qué tal si también los haces evolucionar?$"

gBirchDexRatingText_LessThan80::
	.string "Esto va a ser una POKéDEX fantástica.\n"
	.string "Esa es la sensación que tengo.$"

gBirchDexRatingText_LessThan90::
	.string "Has coleccionado tantos...\n"
	.string "¡Tu talento es notable!$"

gBirchDexRatingText_LessThan100::
	.string "¿Has visitado la ZONA SAFARI?\p"
	.string "He oído que hay algunos POKéMON que\n"
	.string "solo se pueden atrapar allí.$"

gBirchDexRatingText_LessThan110::
	.string "¡Por fin has alcanzado la marca de\n"
	.string "los 100!\p"
	.string "¡Esta es una POKéDEX impresionante!$"

gBirchDexRatingText_LessThan120::
	.string "Puede que haya POKéMON que se puedan\n"
	.string "encontrar usando GOLPE ROCA.$"

gBirchDexRatingText_LessThan130::
	.string "Deberías conseguir más POKéMON\n"
	.string "intercambiando con otros.$"

gBirchDexRatingText_LessThan140::
	.string "He oído que hay POKéMON que evolucionan\n"
	.string "cuando llegan a querer mucho a sus\l"
	.string "ENTRENADORES.$"

gBirchDexRatingText_LessThan150::
	.string "No tenía ni idea de que hubiera tantas\n"
	.string "especies de POKéMON en la región de\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "En ocasiones, algunos POKéMON aparecen\n"
	.string "en gran número, como brotes.\p"
	.string "No pierdas oportunidades como esas.$"

gBirchDexRatingText_LessThan170::
	.string "Se puede obtener una muy buena idea de\n"
	.string "los POKéMON de la región de HOENN\l"
	.string "mirando tu POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Diría que ya calificas como\n"
	.string "PROFESOR POKéMON, ¡y un bueno, además!$"

gBirchDexRatingText_LessThan190::
	.string "Con una POKéDEX tan completa,\n"
	.string "¡eres un verdadero profesional en esto!$"

gBirchDexRatingText_LessThan200::
	.string "Estás muy cerca de completar esta\n"
	.string "POKéDEX.\l"
	.string "¡Lo presiento en mis huesos!$"

gBirchDexRatingText_DexCompleted::
	.string "¡Enhorabuena!\n"
	.string "¡Tu POKéDEX está completa!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Mmm...\n"
	.string "A nivel nacional...\p"
	.string "Has visto {STR_VAR_1} POKéMON,\n"
	.string "y has atrapado {STR_VAR_2} POKéMON...$"
