Questionnaire_Text_FillOut::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

Questionnaire_Text_ThankYou::
	.string "Gracias por tomarte el tiempo de\n"
	.string "rellenar nuestro cuestionario.\p"
	.string "Tus comentarios serán utilizados\n"
	.string "como referencia en el futuro.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "¡Oh, hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que sabes algo sobre\n"
	.string "el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Una vez que guardes tu partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "¡Oh, hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que sabes algo sobre\n"
	.string "el EVENTO MISTERIOSO.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Una vez que guardes tu partida, podrás\n"
	.string "acceder al EVENTO MISTERIOSO.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Gracias por utilizar el Sistema de\n"
	.string "EVENTOS MISTERIOSOS.\p"
	.string "Debes de ser {PLAYER}.\n"
	.string "Hay un ticket aquí para ti.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Parece ser para usar en el puerto de\n"
	.string "CIUDAD CALAGUA.\p"
	.string "¿Por qué no lo pruebas y ves de qué\n"
	.string "se trata?$"
