.align 2
gText_ConfirmSave::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "¿Estás seguro de que quieres\l"
	.string "sobrescribirla?$"

gText_SavingDontTurnOff::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedGame::
	.string "{PLAYER} ha guardado la partida.$"

gText_DifferentSaveFile::
	.string "¡ATENCIÓN!\p"
	.string "Ya existe una partida guardada\n"
	.string "de otro juego.\p"
	.string "Si guardas ahora, se perderá por\n"
	.string "completo la aventura del otro\l"
	.string "archivo, incluyendo los objetos\l"
	.string "y los POKéMON.\p"
	.string "¿Estás seguro de que quieres\n"
	.string "guardar ahora y sobrescribir la\l"
	.string "otra partida?$"

gText_SaveError::
	.string "Error al guardar.\p"
	.string "Por favor, cambia la\n"
	.string "memoria de respaldo.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
