SecretBase_Text_Trainer0Intro:
	.string "¿Ya has hecho una BASE SECRETA?\p"
	.string "He estado por aquí y por allá antes de\n"
	.string "elegir este lugar.\p"
	.string "Como ya estás aquí, ¿qué te parece si\n"
	.string "luchamos?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "¡Vale!\n"
	.string "¡Aquí vamos!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "¿Eh?\n"
	.string "Oh, no puedes ahora...$"

SecretBase_Text_Trainer0Defeated::
	.string "¡Waaargh! ¡Eres demasiado fuerte!\n"
	.string "Sobre que he perdido... ¡Por favor,\l"
	.string "mantenlo en secreto!$"

SecretBase_Text_Trainer0PostBattle:
	.string "¿Qué te parece mi BASE SECRETA?\n"
	.string "Ven a visitarme mañana otra vez.$"

SecretBase_Text_Trainer0PreChampion:
	.string "¿Ya has hecho una BASE SECRETA?\p"
	.string "He estado por aquí y por allá antes de\n"
	.string "elegir este lugar.\p"
	.string "¡Siéntete como en casa!$"

SecretBase_Text_Trainer5Intro:
	.string "Hay un montón de lugares donde puedes\n"
	.string "hacer una BASE SECRETA.\p"
	.string "Pero este es mi favorito.\n"
	.string "¿No te parece agradable?\p"
	.string "Oh, ¿te apetece luchar?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "¡Vale, allá vamos!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh...\n"
	.string "No puedes ahora, vale.$"

SecretBase_Text_Trainer5Defeated::
	.string "Mmm... Hemos perdido...\n"
	.string "Pero no se lo cuentes a nadie.\l"
	.string "¡Es un secreto confidencial!$"

SecretBase_Text_Trainer5PostBattle:
	.string "Si vuelves por esta zona,\n"
	.string "espero que me visites.$"

SecretBase_Text_Trainer5PreChampion:
	.string "Hay un montón de lugares donde puedes\n"
	.string "hacer una BASE SECRETA.\p"
	.string "Pero este es mi favorito.\n"
	.string "¿No te parece agradable?$"

SecretBase_Text_Trainer1Intro:
	.string "Este es un lugar muy popular.\n"
	.string "Siempre está ocupado.\p"
	.string "¡Oh! ¿También estabas pensando en\n"
	.string "quedarte con este lugar?\p"
	.string "Te diré una cosa, puedes quedarte con\n"
	.string "este lugar si me vences.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "¡Vale!\n"
	.string "¡Voy a defender mi BASE SECRETA!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "¿Eh? ¿Es eso cierto?\n"
	.string "¿No te interesa este lugar?$"

SecretBase_Text_Trainer1Defeated::
	.string "¡No puedo seguir!\n"
	.string "¡Me rindo!$"

SecretBase_Text_Trainer1PostBattle:
	.string "Vale, cuando me mude algún día,\n"
	.string "¡este lugar será tuyo!$"

SecretBase_Text_Trainer1PreChampion:
	.string "Este es un lugar muy popular.\n"
	.string "Siempre está ocupado.\p"
	.string "Esperé mucho tiempo a que se liberara.\n"
	.string "¡Por fin pude usarlo!$"

SecretBase_Text_Trainer6Intro:
	.string "Bienvenido a mi LABORATORIO POKéMON.\p"
	.string "Realizo investigaciones sobre los\n"
	.string "combates en secreto.\p"
	.string "¿Te gustaría ver lo fuerte que soy?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "¡Voy a darlo todo!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "¡Otra vez será, entonces!$"

SecretBase_Text_Trainer6Defeated::
	.string "Mmm... Todavía tengo mucho que aprender.\n"
	.string "Tengo que estudiar más.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Gracias por luchar conmigo.\n"
	.string "Por favor, vuelve mañana.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Bienvenido a mi LABORATORIO POKéMON.\p"
	.string "Realizo investigaciones sobre los\n"
	.string "combates en secreto.$"

SecretBase_Text_Trainer2Intro:
	.string "Una gran mansión es agradable, pero\n"
	.string "prefiero este tipo de lugar.\p"
	.string "Me gusta porque viene toda clase de\n"
	.string "gente a visitarme.\p"
	.string "Así que, ¿qué te parece si luchamos?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "¡Así se habla!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "¡Cuando estés listo, dame un toque!$"

SecretBase_Text_Trainer2Defeated::
	.string "¡Ay! ¡He perdido!\n"
	.string "¡Pero sigue siendo divertido luchar!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Bueno, de todos modos, debería ir a\n"
	.string "comprar algunas decoraciones y muebles.\p"
	.string "Quiero que mi BASE SECRETA sea un lugar\n"
	.string "que otras personas puedan disfrutar.$"

SecretBase_Text_Trainer2PreChampion:
	.string "Una gran mansión es agradable, pero\n"
	.string "prefiero este tipo de lugar.\p"
	.string "Me gusta porque viene toda clase de\n"
	.string "gente a visitarme.$"

SecretBase_Text_Trainer7Intro:
	.string "Simplemente adoro comprar decoraciones\n"
	.string "y muebles.\p"
	.string "También me encanta criar POKéMON\n"
	.string "igual de mucho.\p"
	.string "Si eres tan amable, ¿lucharías con\n"
	.string "mis POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Gracias.\n"
	.string "¿Empezamos?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "Qué decepción...$"

SecretBase_Text_Trainer7Defeated::
	.string "Me rindo...$"

SecretBase_Text_Trainer7PostBattle:
	.string "¡Ha sido muy divertido!\n"
	.string "Ahora voy a ir de compras.$"

SecretBase_Text_Trainer7PreChampion:
	.string "Simplemente adoro comprar decoraciones\n"
	.string "y muebles.\p"
	.string "También me encanta criar POKéMON\n"
	.string "igual de mucho.$"

SecretBase_Text_Trainer3Intro:
	.string "Algunas personas hacen sus BASES\n"
	.string "SECRETAS en lugares difíciles de\l"
	.string "encontrar.\p"
	.string "¿Quieren pasar desapercibidas?\p"
	.string "Pero como ya me has encontrado, ¿qué tal\n"
	.string "si luchamos?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "¡No me voy a rendir fácilmente!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh... ¿Estás cansado de buscar\n"
	.string "este lugar?$"

SecretBase_Text_Trainer3Defeated::
	.string "He caído...$"

SecretBase_Text_Trainer3PostBattle:
	.string "¿Dónde está tu BASE SECRETA?\n"
	.string "Debería ir a visitarte.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Algunas personas hacen sus BASES\n"
	.string "SECRETAS en lugares difíciles de\l"
	.string "encontrar.\p"
	.string "¿Quieren pasar desapercibidas?$"

SecretBase_Text_Trainer8Intro:
	.string "La gente me ha dicho que puedes conseguir\n"
	.string "decoraciones de varias formas.\p"
	.string "¡Deberíamos tener una competición para\n"
	.string "ver quién consigue mejores decoraciones\l"
	.string "y muebles!\p"
	.string "Mientras tanto, ¿quieres luchar?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "Esta es mi BASE SECRETA.\n"
	.string "¡No puedo perder!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "Lucharé contigo cuando quieras.$"

SecretBase_Text_Trainer8Defeated::
	.string "¿Eh?\n"
	.string "¿Acabo de perder?$"

SecretBase_Text_Trainer8PostBattle:
	.string "No perderé en la colección de\n"
	.string "decoraciones. ¡Vuelve a visitarme!$"

SecretBase_Text_Trainer8PreChampion:
	.string "La gente me ha dicho que puedes conseguir\n"
	.string "decoraciones de varias formas.\p"
	.string "¡Deberíamos tener una competición para\n"
	.string "ver quién consigue mejores decoraciones\l"
	.string "y muebles!$"

SecretBase_Text_Trainer4Intro:
	.string "Encontré un lugar que me gustó y lo\n"
	.string "arreglé con mis decoraciones favoritas.\p"
	.string "Crio mis POKéMON favoritos y me hago\n"
	.string "más fuerte con ellos.\p"
	.string "Eso es lo que hago.\n"
	.string "¿Quieres luchar conmigo?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "¡Muéstrame de qué estás hecho!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "Supongo que hay veces en las que no\n"
	.string "tienes ganas.$"

SecretBase_Text_Trainer4Defeated::
	.string "Ahora sé exactamente de qué estás hecho.$"

SecretBase_Text_Trainer4PostBattle:
	.string "Ambos podemos hacernos más fuertes.\n"
	.string "¡Sigamos así!$"

SecretBase_Text_Trainer4PreChampion:
	.string "Encontré un lugar que me gustó y lo\n"
	.string "arreglé con mis decoraciones favoritas.\p"
	.string "Crio mis POKéMON favoritos y me hago\n"
	.string "más fuerte con ellos.\p"
	.string "Cada día es un gran día.$"

SecretBase_Text_Trainer9Intro:
	.string "Puedes aprender mucho sobre el gusto y\n"
	.string "el sentido de las personas por el tipo\l"
	.string "de decoraciones que tienen y cómo las\l"
	.string "colocan.\p"
	.string "¿Qué te parece mi gusto?\n"
	.string "¿Te deja sin palabras?\p"
	.string "¿Quieres ver mi gusto en los combates?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "¡No voy a contenerme!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "Estaré encantado de demostrarte mi estilo\n"
	.string "cuando quieras.$"

SecretBase_Text_Trainer9Defeated::
	.string "¡Eres supremamente talentoso!\n"
	.string "Tu poder parece ilimitado...$"

SecretBase_Text_Trainer9PostBattle:
	.string "¿Qué te pareció mi estilo?\n"
	.string "¡Seguiré puliéndolo!$"

SecretBase_Text_Trainer9PreChampion:
	.string "Puedes aprender mucho sobre el gusto y\n"
	.string "el sentido de las personas por el tipo\l"
	.string "de decoraciones que tienen y cómo las\l"
	.string "colocan.\p"
	.string "¿Qué te parece mi gusto?\n"
	.string "¿Te deja sin palabras?$"
