ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "¿Piensas ir hasta el fondo?\p"
	.string "¿Qué tal si me traes un poco de\n"
	.string "SAL CARDUMEN y CONCHAS CARDUMEN?\p"
	.string "Si me traes los ingredientes, puedo\n"
	.string "hacerte algo bueno.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "Si me traes cuatro SAL CARDUMEN y\n"
	.string "cuatro CONCHAS CARDUMEN, puedo hacerte\l"
	.string "un CAMPANA CONCHA...\p"
	.string "Puedes conseguir esos ingredientes\n"
	.string "todos los días.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "¡Oh, hola! ¡SAL CARDUMEN y CONCHAS\n"
	.string "CARDUMEN! ¡Y bastantes, por cierto!\p"
	.string "¿Quieres que te haga un CAMPANA CONCHA\n"
	.string "con ellos?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "¡Muy bien, entonces! Te haré un CAMPANA\n"
	.string "CONCHA enseguida.\p"
	.string "... ... ... ... ... ... ...\n"
	.string "... ... ... ... ... ... ...\p"
	.string "¡Listo! ¡Ya está!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Haz que un Pokémon lo lleve. Seguro que\n"
	.string "le encanta.\p"
	.string "Vaya, el sonido del CAMPANA CONCHA...\n"
	.string "¡Es simplemente sublime!\p"
	.string "Puedes conseguir los ingredientes todos\n"
	.string "los días, así que puedo hacerte más.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh... ¿Es eso cierto...?\n"
	.string "Quería hacerte un CAMPANA CONCHA...$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "No tienes espacio en la MOCHILA para que\n"
	.string "te lo haga.\p"
	.string "Deberías hacer hueco y volver por el\n"
	.string "CAMPANA CONCHA.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "Había SAL CARDUMEN aquí.\n"
	.string "Pero ahora no hay nada.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "Había una CONCHA CARDUMEN aquí.\n"
	.string "Pero ahora no hay nada.$"
