Route102_Text_CalvinIntro:
	.string "Si llevas POKÉMON contigo, entonces\n"
	.string "¡eres un ENTRENADOR de POKÉMON oficial!\l"
	.string "¡No puedes rechazar mi desafío!$"

Route102_Text_CalvinDefeated:
	.string "Ay, he perdido…\n"
	.string "Debería haber entrenado más a los míos…$"

Route102_Text_CalvinPostBattle:
	.string "Escucha, tú. Si eres fuerte,\n"
	.string "¡deberías habérmelo dicho antes!$"

Route102_Text_CalvinRegister:
	.string "He estado trabajando duro en esto desde\n"
	.string "te vi la última vez.\p"
	.string "Me gustaría volver a luchar contra ti, así que ¿puedes\n"
	.string "¿me registras en tu POKéNAV?$"

Route102_Text_CalvinRegisterShort:
	.string "Me gustaría volver a luchar contra ti, así que ¿puedes\n"
	.string "¿me registras en tu POKéNAV?$"

Route102_Text_CalvinRematchIntro:
	.string "Desde que perdí contra ti, he\n"
	.string "he entrenado a mis POKéMON.\l"
	.string "¡No puedes rechazar mi desafío!$"

Route102_Text_CalvinRematchDefeated:
	.string "¡Ay, he perdido…\n"
	.string "¿Es que mi método de entrenamiento no es el adecuado?$"

Route102_Text_CalvinRematchPostBattle:
	.string "Si vas a hacerte más fuerte,\n"
	.string "yo también me haré más fuerte.$"

Route102_Text_AllenIntro:
	.string "¿Acabas de convertirte en ENTRENADOR?\n"
	.string "¡Los dos somos principiantes!$"

Route102_Text_AllenDefeated:
	.string "Te he desafiado porque pensé\n"
	.string "que podría vencerte fácilmente…$"

Route102_Text_AllenPostBattle:
	.string "Todavía no he ganado ni una vez…\n"
	.string "Ojalá gane algún combate pronto…$"

Route102_Text_RickIntro:
	.string "¡Ajajá! ¡Me estabas mirando!\n"
	.string "¡Te desafío con mis Pokémon bicho!$"

Route102_Text_RickDefeated:
	.string "¡Ooooh! ¡Me has noqueado!$"

Route102_Text_RickPostBattle:
	.string "Si miras a los ojos a un entrenador,\n"
	.string "¡le estás desafiando! ¡Son las reglas!$"

Route102_Text_TianaIntro:
	.string "Voy a seguir con mi racha de victorias\n"
	.string "hasta ser la mejor entrenadora.\l"
	.string "¡Y tú vas a ayudarme!$"

Route102_Text_TianaDefeated:
	.string "Mi carrera está estancada...$"

Route102_Text_TianaPostBattle:
	.string "Para seguir avanzando, tengo que\n"
	.string "atrapar más Pokémon.$"

Route103_Text_DaisyIntro:
	.string "¿Te ha atraído el dulce y relajante\n"
	.string "aroma que emanamos?$"

Route103_Text_DaisyDefeated:
	.string "Pues no ha debido de ser el aroma...$"

Route103_Text_DaisyPostBattle:
	.string "La aromaterapia es una técnica de\n"
	.string "curación mediante el uso de fragancias.$"

Route103_Text_AmyIntro:
	.string "AMY: Soy Ali. Y ésta es mi hermana\n"
	.string "pequeña, Mar. ¡Combatimos juntas!$"

Route103_Text_AmyDefeated:
	.string "AMY: O-o-oh... Hemos perdido...$"

Route103_Text_AmyPostBattle:
	.string "AMY: Tienes que pensar en un montón\n"
	.string "de cosas cuando luchas contra dos\l"
	.string "entrenadores.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: O-o-oh... Hemos perdido...$"

Route103_Text_LivIntro:
	.string "MAR: Luchamos juntas, en equipo.$"

Route103_Text_LivDefeated:
	.string "MAR: O-o-oh, nos han ganado...$"

Route103_Text_LivPostBattle:
	.string "MAR: Mi hermana mayor y yo trabajamos\n"
	.string "perfectamente bien en equipo.\l"
	.string "Pero esta vez no ha ido tan bien...$"

Route103_Text_AmyLivRegister:
	.string "MAR: Mi hermana mayor y yo trabajamos\n"
	.string "perfectamente bien en equipo.\l"
	.string "Pero esta vez no ha ido tan bien...$"

Route103_Text_LivNotEnoughPokemon:
	.string "MAR: Si quieres luchar contra nosotras,\n"
	.string "tienes que tener dos Pokémon.\l"
	.string "¡No es justo si no es así!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: Soy ALI. Y ésta es mi hermana\n"
	.string "pequeña, MAR. ¡Combatimos juntas!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: O-o-oh, no hemos ganado tampoco\n"
	.string "esta vez... ¡Buaaaaa!$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Tienes que pensar en un montón\n"
	.string "de cosas cuando luchas contra dos\l"
	.string "entrenadores.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: O-o-oh... Hemos perdido...$"

Route103_Text_LivRematchIntro:
	.string "MAR: Luchamos juntas, en equipo.$"

Route103_Text_LivRematchDefeated:
	.string "MAR: O-o-oh, hemos perdido otra vez...\n"
	.string "¡Buaaaaa!$"

Route103_Text_LivRematchPostBattle:
	.string "MAR: Mi hermana mayor y yo trabajamos\n"
	.string "perfectamente bien en equipo.\l"
	.string "¿Por qué hemos perdido otra vez?...$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "MAR: Si quieres luchar contra nosotras,\n"
	.string "tienes que tener dos Pokémon.\l"
	.string "¡No es justo si no es así!$"

Route103_Text_AndrewIntro:
	.string "¡Brrrr! ¡Mi hilo de pescar está todo\n"
	.string "enredado! ¡Qué fastidio tan gordo!\l"
	.string "¡La voy a pagar contigo!$"

Route103_Text_AndrewDefeated:
	.string "¡Brrrr! ¡He perdido! ¡Ahora estoy\n"
	.string "aún más mosqueado!$"

Route103_Text_AndrewPostBattle:
	.string "¡Brrrr! ¡Qué mosqueo más tonto\n"
	.string "tengo! ¡Brrrrrrrrrr!$"

Route103_Text_MiguelIntro:
	.string "Mi Pokémon es una monada. ¡Mira,\n"
	.string "te lo voy a enseñar!$"

Route103_Text_MiguelDefeated:
	.string "¡Ay, ay, ay, ay! ¡Mi Pokémon bonito!$"

Route103_Text_MiguelPostBattle:
	.string "Mi querido Pokémon es una monada hasta\n"
	.string "cuando está debilitado.$"

Route103_Text_MiguelRegister:
	.string "¡Eh, mira! Mi preciosísimo Pokémon es\n"
	.string "aún más encantador que antes.$"

Route103_Text_MiguelRematchIntro:
	.string "¡Eh, mira! Mi preciosísimo Pokémon es\n"
	.string "aún más encantador que antes.$"

Route103_Text_MiguelRematchDefeated:
	.string "¡Ay, ay, ay, ay! ¡Mi Pokémon bonito!$"

Route103_Text_MiguelRematchPostBattle:
	.string "Cuanto más tiempo paso con él, más\n"
	.string "mono se vuelve.$"

Route103_Text_PeteIntro:
	.string "A esta distancia…\n"
	.string "¡Deberías nadar!$"

Route103_Text_PeteDefeated:
	.string "¡Oh, eso ha estado bien!$"

Route103_Text_PetePostBattle:
	.string "Oh, ahora entiendo tu punto de vista.\p"
	.string "Si tuviera un Pokémon tan fiel,\n"
	.string "yo también querría hacer SURF con él.$"

Route103_Text_IsabelleIntro:
	.string "¡Mira por dónde vas!\n"
	.string "¡Vamos a chocar!$"

Route103_Text_IsabelleDefeated:
	.string "Uf…$"

Route103_Text_IsabellePostBattle:
	.string "Nado muy mal, así que estaba\n"
	.string "practicando… Perdón por casi chocar\l"
	.string "contigo.$"

Route103_Text_RhettIntro:
	.string "¡Guau! ¿Cómo te has metido aquí?$"

Route103_Text_RhettDefeated:
	.string "¡Guau! ¡Qué potencia!$"

Route103_Text_RhettPostBattle:
	.string "¿A ti te gustan los espacios pequeños?$"

Route103_Text_MarcosIntro:
	.string "Las notas de mi guitarra atraen a la\n"
	.string "gente. ¡La prueba eres tú!$"

Route103_Text_MarcosDefeated:
	.string "Has arruinado mi espectáculo...$"

Route103_Text_MarcosPostBattle:
	.string "Siempre busco lugares solitarios para\n"
	.string "tocar, pero al final acabo rodeado de\l"
	.string "gente. Voy a tener que hacerme\l"
	.string "profesional...$"

Route104_Text_GinaIntro:
	.string "GINA: Vale, ¡luchemos con nuestros\n"
	.string "Pokémon!$"

Route104_Text_GinaDefeat:
	.string "GINA: ¡No me gusta perder!$"

Route104_Text_GinaPostBattle:
	.string "GINA: ¡Está claro que eres fuerte!\n"
	.string "¡Tenemos que entrenar mucho más!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: ¿Oh? ¿Solo un Pokémon?\n"
	.string "Entonces no luchamos contigo.\p"
	.string "Si solo hay un Pokémon, se sentirá\n"
	.string "solo. No es agradable.$"

Route104_Text_MiaIntro:
	.string "MÍA: Somos gemelas, así que\n"
	.string "entablamos combates Pokémon juntas.$"

Route104_Text_MiaDefeat:
	.string "MÍA: Luchamos juntas, pero eso no nos\n"
	.string "ha hecho ganar esta vez...$"

Route104_Text_MiaPostBattle:
	.string "MÍA: Entrenaremos más a nuestros\n"
	.string "Pokémon para ser tan fuertes como tú.$"

Route104_Text_MiaNotEnoughMons:
	.string "MÍA: ¿Quieres luchar con nosotras?\p"
	.string "Es un gran no-no si no llevas dos\n"
	.string "Pokémon contigo. ¡Somos demasiado\l"
	.string "fuertes para ti!$"

Route104_Text_IvanIntro:
	.string "¿Por qué negarlo? ¡Soy un experto en\n"
	.string "Pokémon de tipo Agua!\p"
	.string "¿Eh?\n"
	.string "¿Que no sabes quién soy?$"

Route104_Text_IvanDefeat:
	.string "Pensaba que no era demasiado malo,\n"
	.string "pero me temo que debo mejorar...$"

Route104_Text_IvanPostBattle:
	.string "He estado pescando demasiado.\n"
	.string "Debería haber entrenado a mis\l"
	.string "Pokémon...$"

Route104_Text_BillyIntro:
	.string "¡Dejar huellas en la arena es tan\n"
	.string "divertido!$"

Route104_Text_BillyDefeat:
	.string "¡Aaaaah! ¡Tengo arena en los zapatos!\n"
	.string "¡Es la mar de desagradable!$"

Route104_Text_BillyPostBattle:
	.string "Estoy dejando muchas huellas en la\n"
	.string "arena, pero enseguida desaparecen...$"

Route104_Text_HaleyIntro:
	.string "¿Debería...?\n"
	.string "¿O no debería...?\p"
	.string "¡Venga, sí, vamos a luchar!$"

Route104_Text_HaleyDefeat:
	.string "No hubiera debido...$"

Route104_Text_HaleyPostBattle:
	.string "Si te enfrentas a una decisión y dejas\n"
	.string "que alguien la tome por ti, siempre te\l"
	.string "arrepentirás del resultado...$"

Route104_Text_HaleyRegister1:
	.string "Eres fuerte, pero ¿debería registrarte\n"
	.string "en mi PokéNav? Quizá no debería...\p"
	.string "¡Vale, claro, te registraré!$"

Route104_Text_HaleyRegister2:
	.string "Eres fuerte, pero ¿debería registrarte\n"
	.string "en mi PokéNav? Quizá no debería...\p"
	.string "¡Vale, claro, te registraré!$"

Route104_Text_HaleyRematchIntro:
	.string "¡Vamos, enfréntate a mí!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ooooh... Pensé que podía ganar...$"

Route104_Text_HaleyPostRematch:
	.string "Decidí luchar, así que debo aceptar la\n"
	.string "derrota con espíritu deportivo.\p"
	.string "Aun así hubiera preferido ganar...$"

Route104_Text_WinstonIntro:
	.string "Por supuesto que acepto tu reto.\n"
	.string "¡Me sobra el dinero!$"

Route104_Text_WinstonDefeat:
	.string "¿Por qué no he ganado?$"

Route104_Text_WinstonPostBattle:
	.string "Hay cosas que el dinero no puede\n"
	.string "comprar. Por ejemplo, los Pokémon.$"

Route104_Text_WinstonRegister1:
	.string "¿Mmm?\n"
	.string "Ah, has conseguido un PokéNav.\p"
	.string "Me encantará registrarte.\n"
	.string "Después de todo, tengo mucho dinero.$"

Route104_Text_WinstonRegister2:
	.string "¿Mmm?\n"
	.string "Ah, has conseguido un PokéNav.\p"
	.string "Me encantará registrarte.\n"
	.string "Después de todo, tengo mucho dinero.$"

Route104_Text_WinstonRematchIntro:
	.string "Tras perder contigo, me puse a estudiar\n"
	.string "de todo sobre los Pokémon.$"

Route104_Text_WinstonRematchDefeat:
	.string "¡¿He perdido otra vez?! ¿Por qué no he\n"
	.string "ganado?$"

Route104_Text_WinstonPostRematch:
	.string "Soy rico a rabiar, pero no se me dan\n"
	.string "bien los Pokémon...\p"
	.string "Es un mundo tan complejo...$"

Route104_Text_CindyIntro:
	.string "El destino ha hecho que nos\n"
	.string "cruzáramos. ¿Quieres luchar contra mí?$"

Route104_Text_CindyDefeat:
	.string "Ooooh...$"

Route104_Text_CindyPostBattle:
	.string "“Hola” siempre precede a “adiós”.\n"
	.string "Espero que volvamos a vernos.$"

Route104_Text_CindyRegister1:
	.string "Hola, volvemos a encontrarnos.\p"
	.string "Parece que nos atraemos. Registrémonos\n"
	.string "el uno al otro en nuestros PokéNav.$"

Route104_Text_CindyRegister2:
	.string "Deberíamos conmemorar cómo parece que\n"
	.string "nos atraemos el uno al otro.\p"
	.string "Registrémonos el uno al otro en\n"
	.string "nuestros PokéNav.$"

Route104_Text_CindyRematchIntro:
	.string "Hola, volvemos a encontrarnos.\n"
	.string "¿Quieres luchar contra mí?$"

Route104_Text_CindyRematchDefeat:
	.string "Ooooh... Lo hice lo mejor que pude...$"

Route104_Text_CindyPostRematch:
	.string "“Hola” siempre precede a “adiós”.\n"
	.string "Espero que volvamos a vernos.$"

Route104_Text_DarianIntro:
	.string "¡He pescado un Pokémon con pinta de\n"
	.string "fiero! ¡Se ve a leguas que es especial!\l"
	.string "¡Da miedo!$"

Route104_Text_DarianDefeat:
	.string "Pero...$"

Route104_Text_DarianPostBattle:
	.string "Vaya, Magikarp, lo tuyo es mucho ruido\n"
	.string "y pocas nueces, ¿eh?$"

Route105_Text_FosterIntro:
	.string "Dicen que hay una roca mística por aquí\n"
	.string "cerca. ¿Tú sabes algo?$"

Route105_Text_FosterDefeated:
	.string "Tenía la mente en esa roca y he dejado\n"
	.string "que mis Pokémon se debilitaran...$"

Route105_Text_FosterPostBattle:
	.string "Me puedo pasar las horas muertas mirando\n"
	.string "una roca bonita sin cansarme.$"

Route105_Text_LuisIntro:
	.string "¡Huy! Cuando te vi pensé que eras un crío\n"
	.string "que se estaba ahogando... Parece que\l"
	.string "estás bien, así que ¿qué piensas de\l"
	.string "echar un combate?$"

Route105_Text_LuisDefeated:
	.string "Glu... Glu... Glu...$"

Route105_Text_LuisPostBattle:
	.string "Si te estás ahogando, agita el brazo\n"
	.string "hacia la costa para pedir ayuda.$"

Route105_Text_DominikIntro:
	.string "Nadar entre las olas del mar... ¡Mejor\n"
	.string "que en una piscina!$"

Route105_Text_DominikDefeated:
	.string "He perdido... Qué depre...$"

Route105_Text_DominikPostBattle:
	.string "¿Por qué el mar es azul? Leí la\n"
	.string "explicación en el museo de Ciudad\l"
	.string "Portual, pero no me acuerdo...$"

Route105_Text_BeverlyIntro:
	.string "Mi cuerpo es más ligero en el agua. ¡Es\n"
	.string "como si no pesara nada!$"

Route105_Text_BeverlyDefeated:
	.string "Me has dejado flotando...$"

Route105_Text_PostBattle:
	.string "El peso de tu cuerpo es nueve veces más\n"
	.string "ligero en el agua... ¡Es normal que\l"
	.string "puedas saltar y moverte como si nada!$"

Route105_Text_ImaniIntro:
	.string "El cielo azul... El ancho mar... Qué\n"
	.string "tranquilidad...$"

Route105_Text_ImaniDefeated:
	.string "¡No estaba lista para el combate!$"

Route105_Text_ImaniPostBattle:
	.string "Me gusta que me digan que soy buena\n"
	.string "compañía, ji, ji, ji.$"

Route105_Text_AndresIntro:
	.string "Tengo la certeza de que el mar guarda\n"
	.string "incontables secretos.$"

Route105_Text_AndresDefeated:
	.string "Has descubierto mi secreto... No sé\n"
	.string "luchar...$"

Route105_Text_AndresPostBattle:
	.string "Tengo la certeza de que el mar guarda\n"
	.string "incontables secretos. ¡Y pienso\l"
	.string "descubrirlos todos!$"

Route105_Text_AndresRegister:
	.string "¿Cómo? ¿No soy fuerte y sin embargo me\n"
	.string "quieres registrar en tu PokéNav?$"

Route105_Text_AndresRematchIntro:
	.string "Ya te dije que no soy muy fuerte. ¿Seguro\n"
	.string "que quieres luchar conmigo?$"

Route105_Text_AndresRematchDefeated:
	.string "No es ninguna sorpresa... Ya sabía que\n"
	.string "no podía ganar.$"

Route105_Text_AndresRematchPostBattle:
	.string "Puede que no sepa luchar, pero como\n"
	.string "explorador no tengo igual. ¡Voy a viajar\l"
	.string "por todos los mares del mundo!$"

Route105_Text_JosueIntro:
	.string "Nadar me agota una barbaridad. He\n"
	.string "perdido costumbre. ¡Necesito un\l"
	.string "combate, para variar!$"

Route105_Text_JosueDefeated:
	.string "He perdido, pero sólo porque estamos\n"
	.string "luchando en el mar.$"

Route105_Text_JosuePostBattle:
	.string "La verdad es que prefiero luchar en el\n"
	.string "aire a luchar en el mar.$"

Route106_Text_ElliotIntro:
	.string "¿Qué prefieres? ¿La pesca en agua dulce\n"
	.string "o en el mar?$"

Route106_Text_ElliotDefeated:
	.string "Los Pokémon se me dan tan mal como la\n"
	.string "pesca en alta mar...$"

Route106_Text_ElliotPostBattle:
	.string "Pescar es genial, pero luchar también.\n"
	.string "Podríamos volver a enfrentarnos, ¿no?$"

Route106_Text_ElliotRegister:
	.string "La pesca es un deporte genial, ya sea en\n"
	.string "un río o en el mar... ¿A que piensas\l"
	.string "igual?$"

Route106_Text_ElliotRematchIntro:
	.string "He pescado un montón de Pokémon. ¡Te voy\n"
	.string "a dar una paliza!$"

Route106_Text_ElliotRematchDefeated:
	.string "Los Pokémon se me dan tan mal como la\n"
	.string "pesca en alta mar...$"

Route106_Text_ElliotRematchPostBattle:
	.string "La pesca es un deporte genial, ya sea en\n"
	.string "un río o en el mar... ¿A que piensas\l"
	.string "igual?$"

Route106_Text_NedIntro:
	.string "¿Qué hace un pescador cuando tiene que ir\n"
	.string "al servicio? ¿Qué pasa si un pez gordo\l"
	.string "pica en mi caña justo cuando estoy en el\l"
	.string "servicio? Tengo que aguantarme...$"

Route106_Text_NedDefeated:
	.string "He perdido porque tengo ganas de ir al\n"
	.string "servicio y me estoy aguantando...$"

Route106_Text_NedPostBattle:
	.string "¡Yo no me muevo! ¡Tengo la corazonada de\n"
	.string "que va a picar uno gordo de verdad!$"

Route106_Text_DouglasIntro:
	.string "¡Ja, ja, ja! Corriendo soy una tortuga,\n"
	.string "¡pero en el agua soy un pez!$"

Route106_Text_DouglasDefeated:
	.string "¡Me rindo!$"

Route106_Text_DouglasPostBattle:
	.string "Seguro que no pierdo en una carrera...$"

Route106_Text_KylaIntro:
	.string "En el mar soy un as. ¡No te lo voy a poner\n"
	.string "nada fácil sólo porque seas tan joven!$"

Route106_Text_KylaDefeated:
	.string "Tú no me tomas en serio, ¿verdad?$"

Route106_Text_KylaPostBattle:
	.string "Deslizarse entre las olas... Qué\n"
	.string "placer... ¿Por qué no lo pruebas?$"

Route107_Text_DarrinIntro:
	.string "Bostezo...\p"
	.string "Debo de haberme quedado dormido mientras\n"
	.string "flotaba entre las olas.$"

Route107_Text_DarrinDefeated:
	.string "Ah, ah, he perdido... Voy a dormir un\n"
	.string "poquito más...$"

Route107_Text_DarrinPostBattle:
	.string "Flotar mecido por las olas... Es como\n"
	.string "dormir en una cama de plumas.$"

Route107_Text_TonyIntro:
	.string "El mar es como mi casa. ¡Luchemos!$"

Route107_Text_TonyDefeated:
	.string "He perdido en mi propio terreno... ¡Me\n"
	.string "cuesta creerlo!$"

Route107_Text_TonyPostBattle:
	.string "Surcar los mares con el corazón lleno de\n"
	.string "sueños...\p"
	.string "¡Es una canción!\n"
	.string "Bueno, me voy a seguir nadando.$"

Route107_Text_TonyRegister:
	.string "¡Me has dejado alucinado! Bueno, para que\n"
	.string "no me olvides...$"

Route107_Text_TonyRematchIntro:
	.string "Nadando en el inmenso mar, ¡mis Pokémon\n"
	.string "se han vuelto más fuertes!$"

Route107_Text_TonyRematchDefeated:
	.string "¡Qué alucine! ¡Mis Pokémon se han hecho\n"
	.string "más fuertes, pero yo sigo siendo un\l"
	.string "entrenador de pacotilla!$"

Route107_Text_TonyRematchPostBattle:
	.string "Lo que aprendes en los combates te hace\n"
	.string "un entrenador mejor. Las olas me lo\l"
	.string "enseñaron.$"

Route107_Text_DeniseIntro:
	.string "¿Conoces un pueblecito llamado Pueblo\n"
	.string "Azuliza?$"

Route107_Text_DeniseDefeated:
	.string "¡Qué rabia me da!$"

Route107_Text_DenisePostBattle:
	.string "En la Casa de la Playa de Pueblo Azuliza\n"
	.string "se ha puesto de moda una frase muy rara.$"

Route107_Text_BethIntro:
	.string "¿Quieres luchar conmigo? ¡Vale, me\n"
	.string "apunto!$"

Route107_Text_BethDefeated:
	.string "No he estado a tu altura.$"

Route107_Text_BethPostBattle:
	.string "Creo que vas a seguir mejorando. ¡Yo\n"
	.string "también me esforzaré!$"

Route107_Text_LisaIntro:
	.string "LISA: Nos enfrentamos a ti, hermano y\n"
	.string "hermana.$"

Route107_Text_LisaDefeated:
	.string "LISA: Increíble. Eres de otra liga.$"

Route107_Text_LisaPostBattle:
	.string "LISA: ¿Tienes amigos con los que ir a la\n"
	.string "playa?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: Si quieres luchar con nosotros,\n"
	.string "trae más Pokémon.$"

Route107_Text_RayIntro:
	.string "RAY: Siempre luchamos con Pokémon, mi\n"
	.string "hermana y yo.\p"
	.string "Yo siempre pierdo, pero en combates 2\n"
	.string "contra 2 podemos ganarte.$"

Route107_Text_RayDefeated:
	.string "RAY: ¡Vaya, estás en otra liga!$"

Route107_Text_RayPostBattle:
	.string "RAY: Mi hermana me dio mi Pokémon. Lo he\n"
	.string "entrenado y ahora es mi compañero\l"
	.string "inseparable.$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: Si quieres luchar con nosotros, ¡ve a\n"
	.string "buscar más Pokémon!$"

Route107_Text_CamronIntro:
	.string "Estoy en medio de un triatlón, pero no\n"
	.string "estoy ni cansado.$"

Route107_Text_CamronDefeated:
	.string "Eso me ha dejado sin aliento...$"

Route107_Text_CamronPostBattle:
	.string "Todavía me queda nadar y correr después\n"
	.string "de esto.\p"
	.string "¿Crees que lo conseguiré?$"

Route108_Text_JeromeIntro:
	.string "¡Mi sueño es nadar los siete mares!$"

Route108_Text_JeromeDefeated:
	.string "Así no podré nadar los siete mares...$"

Route108_Text_JeromePostBattle:
	.string "¡Jugar con Pokémon marinos es una de las\n"
	.string "mejores cosas de nadar!$"

Route108_Text_MatthewIntro:
	.string "¡Eh, tú! ¿También vas al BARCO\n"
	.string "ABANDONADO?$"

Route108_Text_MatthewDefeated:
	.string "¡Me hundo!\n"
	.string "Glu... Glu...$"

Route108_Text_MatthewPostBattle:
	.string "Algunos entran incluso dentro del BARCO\n"
	.string "ABANDONADO.$"

Route108_Text_TaraIntro:
	.string "Mi novio mentiroso me dijo que estoy\n"
	.string "guapísima en bikini...$"

Route108_Text_TaraDefeated:
	.string "¡Oh, qué pena!$"

Route108_Text_TaraPostBattle:
	.string "Aunque sea mentira, me encanta que me\n"
	.string "digan que estoy guapa... Las chicas somos\l"
	.string "así de complicadas...$"

Route108_Text_MissyIntro:
	.string "¡Me encanta el mar! ¡Cuando nado me\n"
	.string "olvido de todos mis problemas!$"

Route108_Text_MissyDefeated:
	.string "¡Cuando pierdo un combate me estreso!$"

Route108_Text_MissyPostBattle:
	.string "¡Desahógate nadando! ¡Es muy saludable!$"

Route108_Text_CoryIntro:
	.string "Me encantan los Pokémon de tipo Agua. ¡Y\n"
	.string "también me gustan los demás!$"

Route108_Text_CoryDefeated:
	.string "¡Buaaaah! ¡He perdido!\n"
	.string "¡Buaaaah! ¡Buaaaah!$"

Route108_Text_CoryPostBattle:
	.string "¡Gritar es bueno para mí! ¡Me anima!$"

Route108_Text_CoryRegister:
	.string "¡También me gustan los entrenadores\n"
	.string "fuertes! ¡Regístrame en tu PokéNav!$"

Route108_Text_CoryRematchIntro:
	.string "¡Me da igual ganar o perder, me encanta\n"
	.string "luchar en el mar!$"

Route108_Text_CoryRematchDefeated:
	.string "¡Buaaaah! ¡He perdido otra vez!\n"
	.string "¡Buaaaah! ¡Buaaaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "Si te enfrentas a un desafío, ¡grita al\n"
	.string "mar!$"

Route108_Text_CarolinaIntro:
	.string "Estoy muy orgullosa de mis Pokémon.\n"
	.string "¡Te enseñaré un combate rápido!$"

Route108_Text_CarolinaDefeated:
	.string "Eso no ha sido nada mono...$"

Route108_Text_CarolinaPostBattle:
	.string "Como estoy en el mar, no me importaría\n"
	.string "ponerme un bañador rosa con volantes...$"

Route109_Text_DavidIntro:
	.string "¡Hiyah! ¡Mira mis abdominales de acero!\n"
	.string "¡Esto es lo que se llama estar en forma!$"

Route109_Text_DavidDefeated:
	.string "¡Aiyah!\n"
	.string "¡He flaqueado!$"

Route109_Text_DavidPostBattle:
	.string "¡Hiyah!\p"
	.string "¡Mis abdominales esculpidos no tienen\n"
	.string "nada que ver con los combates Pokémon!$"

Route109_Text_AliceIntro:
	.string "¿Te has protegido bien del sol?$"

Route109_Text_AliceDefeated:
	.string "¡Ay, ay, ay!$"

Route109_Text_AlicePostBattle:
	.string "¡Las mejillas son las que más se\n"
	.string "queman!$"

Route109_Text_HueyIntro:
	.string "He anclado en los puertos de todo el\n"
	.string "mundo, pero el mejor es Ciudad Portual.$"

Route109_Text_HueyDefeated:
	.string "¡Tú también eres lo más!$"

Route109_Text_HueyPostBattle:
	.string "Quien mejor sabe entrenar Pokémon\n"
	.string "está en el mejor puerto...$"

Route109_Text_EdmondIntro:
	.string "Ayyyy... ¿Combate? ¿Tú y yo?$"

Route109_Text_EdmondDefeated:
	.string "Ayyy... Ooooooohhhhhh...\n"
	.string "Ayyyyyyyyy...$"

Route109_Text_EdmondPostBattle:
	.string "Normalmente soy más fuerte... Pero\n"
	.string "tengo un mareo... Ayyyy... Ya sé que\l"
	.string "soy marinero, ya...$"

Route109_Text_RickyIntro:
	.string "Qué sed tengo... Creo que iré a por un\n"
	.string "refresco a la casa de la playa...$"

Route109_Text_RickyDefeated:
	.string "Aaaaargh...$"

Route109_Text_RickyPostBattle:
	.string "Me muero de hambre... Hasta el flotador\n"
	.string "tiene buena pinta...$"

Route109_Text_RickyRegister:
	.string "Cuando ya no tenga tanta sed, ¿vendrás\n"
	.string "a luchar contra mí?$"

Route109_Text_RickyRematchIntro:
	.string "¡Tengo hambre, pero tengo energía de\n"
	.string "sobra para un combate!$"

Route109_Text_RickyRematchDefeated:
	.string "He perdido... Es porque tengo hambre...$"

Route109_Text_RickyRematchPostBattle:
	.string "Cuando comes en la playa, todo sabe\n"
	.string "un poco mejor.$"

Route109_Text_LolaIntro:
	.string "¿A que las sombrillas de playa parecen\n"
	.string "flores gigantes?$"

Route109_Text_LolaDefeated:
	.string "¡Aaaah!$"

Route109_Text_LolaPostBattle:
	.string "¡Si miras a la playa desde el cielo,\n"
	.string "parece un jardín de flores!$"

Route109_Text_LolaRegister:
	.string "¿Yo? ¡Estoy aquí todos los días!$"

Route109_Text_LolaRematchIntro:
	.string "¡No voy a volver a perder contra ti!\n"
	.string "¡Por eso llevo mi flotador!$"

Route109_Text_LolaRematchDefeated:
	.string "¡Aaaah!$"

Route109_Text_LolaRematchPostBattle:
	.string "¡Si llevo un flotador, mi Pokémon y yo\n"
	.string "somos mucho más monos!$"

Route109_Text_AustinaIntro:
	.string "No puedo nadar sin mi flotador, pero\n"
	.string "¡no voy a perder en un combate Pokémon!$"

Route109_Text_AustinaDefeated:
	.string "¿He perdido porque llevo un flotador?$"

Route109_Text_AustinaPostBattle:
	.string "Mi flotador es un complemento de moda.\n"
	.string "No puedo ir sin él.$"

Route109_Text_GwenIntro:
	.string "Hola, entrenador grande.\n"
	.string "¿Quieres luchar conmigo?$"

Route109_Text_GwenDefeated:
	.string "Oh, eres fuerte.$"

Route109_Text_GwenPostBattle:
	.string "¿Cómo te has vuelto tan fuerte?$"

Route109_Text_CarterIntro:
	.string "¡Jajaja! ¡Este tío va a atrapar uno\n"
	.string "gordo!$"

Route109_Text_CarterDefeated:
	.string "Este tío acaba de perder uno...$"

Route109_Text_CarterPostBattle:
	.string "Este tío piensa que eres un pez gordo.\n"
	.string "No, ¡eres un pez gordo en potencia!$"

Route109_Text_PaulIntro:
	.string "LINO: Estábamos tan tranquilos...\p"
	.string "Ojalá no hubieras venido a\n"
	.string "fastidiarnos.$"

Route109_Text_PaulDefeated:
	.string "LINO: Vale, me rindo.$"

Route109_Text_PaulPostBattle:
	.string "LINO: Oye, no le cuentes a nadie que\n"
	.string "estamos aquí. ¡No necesitamos\l"
	.string "metomentodos!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "LINO: Estamos loquitos el uno por el\n"
	.string "otro. Todo Hoenn nos envidia.$"

Route109_Text_MelIntro:
	.string "MELI: Estamos loquitos el uno por el\n"
	.string "otro. Todo Hoenn nos envidia.$"

Route109_Text_MelDefeated:
	.string "MELI: Hemos perdido a pesar de todo.\n"
	.string "Qué mal...$"

Route109_Text_MelPostBattle:
	.string "MELI: Lino, la próxima vez tendremos\n"
	.string "que esforzarnos más...$"

Route109_Text_MelNotEnoughPokemon:
	.string "MELI: Estamos loquitos el uno por el\n"
	.string "otro. Todo Hoenn nos envidia.$"

Route109_Text_ChandlerIntro:
	.string "¡Tachán! ¿Ves? ¡Mi flotador es redondo!$"

Route109_Text_ChandlerDefeated:
	.string "¡Ay, ay!\n"
	.string "¡Qué mala suerte!$"

Route109_Text_ChandlerPostBattle:
	.string "Y eso que te había enseñado mi flotador\n"
	.string "y todo...$"

Route109_Text_HaileyIntro:
	.string "No sé nadar, sólo finjo que sé.$"

Route109_Text_HaileyDefeated:
	.string "¡Si ya lo sabía yo! Como no sé nadar...$"

Route109_Text_HaileyPostBattle:
	.string "Cuando aprenda a nadar, no habrá rival\n"
	.string "digno de mis Pokémon.$"

Route109_Text_ElijahIntro:
	.string "Para un tío tan macho como yo, ¡este tipo\n"
	.string "de Pokémon es la pareja perfecta!$"

Route109_Text_ElijahDefeated:
	.string "Soy guay incluso perdiendo, ¿eh?$"

Route109_Text_ElijahPostBattle:
	.string "Para un tío tan macho como yo, ¡un\n"
	.string "puerto es el escenario perfecto!\p"
	.string "Creo que me iré a Ciudad Portual.$"

Route110_Text_JacobIntro:
	.string "¡Eh! ¡Cuidado! ¡Se ve que no sueles\n"
	.string "hacer carreras de bicis!$"

Route110_Text_JacobDefeated:
	.string "¡Aaaah! ¡Me han fallado los frenos!$"

Route110_Text_JacobPostBattle:
	.string "Cuando las ruedas están desinfladas o\n"
	.string "hay problemas de frenos, puedes tener\l"
	.string "un accidente. ¡Revisa tu bici!$"

Route110_Text_AnthonyIntro:
	.string "¡Eh, tú! ¿Puedes alcanzarme?$"

Route110_Text_AnthonyDefeated:
	.string "¡Me has dejado atrás del todo!$"

Route110_Text_AnthonyPostBattle:
	.string "No basta sólo la velocidad para ganar en\n"
	.string "los combates Pokémon, está claro...$"

Route110_Text_BenjaminIntro:
	.string "¡No tengas miedo si tu bici corre mucho!$"

Route110_Text_BenjaminDefeated:
	.string "No sé por qué tengo miedo en los\n"
	.string "combates Pokémon...$"

Route110_Text_BenjaminPostBattle:
	.string "No hay por qué tener miedo de nada.\n"
	.string "Tómate las cosas con calma...$"

Route110_Text_BenjaminRegister:
	.string "No hay por qué tener miedo de nada.\n"
	.string "Tómate las cosas con calma...\p"
	.string "Si quieres echar un combate tranquilo,\n"
	.string "llámame.$"

Route110_Text_BenjaminRematchIntro:
	.string "¿No vas muy rápido? Para un rato y\n"
	.string "lucha conmigo.$"

Route110_Text_BenjaminRematchDefeated:
	.string "Estaba tranquilo, pero aun así he\n"
	.string "perdido...$"

Route110_Text_BenjaminRematchPostBattle:
	.string "No hay por qué tener miedo de nada.\n"
	.string "Tómate las cosas con calma...$"

Route110_Text_AbigailIntro:
	.string "El triatlón es una prueba muy dura.\n"
	.string "Tienes que competir en natación,\l"
	.string "ciclismo y carrera.$"

Route110_Text_AbigailDefeated:
	.string "¡Los combates Pokémon tampoco son\n"
	.string "precisamente fáciles!$"

Route110_Text_AbigailPostBattle:
	.string "Estoy agotada, necesito descansar.\n"
	.string "Es importante no sobreentrenar.$"

Route110_Text_AbigailRegister:
	.string "¡Sabes cuánto te aprecio! Te espero en\n"
	.string "el camino de bicis.$"

Route110_Text_AbigailRematchIntro:
	.string "¿A que mola luchar y montar en bici a\n"
	.string "la vez?$"

Route110_Text_AbigailRematchDefeated:
	.string "Uf... ¿Cómo puedes ser tan fuerte?$"

Route110_Text_AbigailRematchPostBattle:
	.string "¿Quieres lograr un nuevo récord? Pues\n"
	.string "perdona por haberte entretenido.$"

Route110_Text_JasmineIntro:
	.string "¡He estado montando en bici tanto,\n"
	.string "tanto, que tengo los gemelos duros\l"
	.string "como una piedra!$"

Route110_Text_JasmineDefeated:
	.string "Creo que me ha dado un calambre...$"

Route110_Text_JasminePostBattle:
	.string "Así que tienes medallas de gimnasio...\n"
	.string "¡Ahora lo entiendo todo!$"

Route110_Text_EdwardIntro:
	.string "Sé lo que piensas hacer... ¡No puedo\n"
	.string "perder!$"

Route110_Text_EdwardDefeated:
	.string "No he sabido predecir mi propia\n"
	.string "derrota...$"

Route110_Text_EdwardPostBattle:
	.string "Puedo ver tu futuro...\p"
	.string "Veo, veo...\n"
	.string "Mmm... Una luz muy brillante...$"

Route110_Text_JaclynIntro:
	.string "¡Ja, ja, ja, ja! Te voy a dejar de\n"
	.string "piedra...$"

Route110_Text_JaclynDefeated:
	.string "Ahora yo estoy patidifusa...$"

Route110_Text_JaclynPostBattle:
	.string "¡Esta vez has ganado de milagro! ¡Ha\n"
	.string "sido pura chorra! ¡No siempre será así,\l"
	.string "ya verás!$"

Route110_Text_EdwinIntro:
	.string "¿Puedo ver tus Pokémon? Sólo una\n"
	.string "miradita...$"

Route110_Text_EdwinDefeated:
	.string "Yo sólo quería completar mi colección...$"

Route110_Text_EdwinPostBattle:
	.string "Cuando veo un Pokémon que no conozco,\n"
	.string "mi pasión de coleccionista sale a flote.$"

Route110_Text_EdwinRegister:
	.string "A mí también me gusta llenar la agenda\n"
	.string "del móvil.$"

Route110_Text_EdwinRematchIntro:
	.string "Hola, ¿has atrapado nuevos Pokémon?\n"
	.string "¿Puedo verlos? Sólo una miradita...$"

Route110_Text_EdwinRematchDefeated:
	.string "Qué Pokémon tan molones tienes...\n"
	.string "Qué envidia...$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, cómo quisiera que todos los Pokémon\n"
	.string "raros que existen fueran míos...$"

Route110_Text_DaleIntro:
	.string "¡Eh!\n"
	.string "¡No me des la lata por detrás!$"

Route110_Text_DaleDefeated:
	.string "¡He perdido!\n"
	.string "¡Maldita sea!$"

Route110_Text_DalePostBattle:
	.string "La pesca requiere concentración.\n"
	.string "Tienes que estar pendiente del corcho\l"
	.string "para ver si ha picado algo.$"

Route110_Text_IsabelIntro:
	.string "¡Ja, ja, ja! ¡Iría al fin del mundo sólo\n"
	.string "para fardar de Pokémon!$"

Route110_Text_IsabelDefeated:
	.string "Ésta no era precisamente la idea que\n"
	.string "tenía yo...$"

Route110_Text_IsabelPostBattle:
	.string "Más que luchar, debería presumir de\n"
	.string "Pokémon en el Club de fans.$"

Route110_Text_IsabelRegister:
	.string "Eso no se acerca a lo que podría hacer\n"
	.string "para presumir de Pokémon.\p"
	.string "¡Te tendré como público cautivo cada\n"
	.string "vez que pueda!$"

Route110_Text_IsabelRematchIntro:
	.string "¡Ja, ja, ja! ¡Yo es que no me canso de\n"
	.string "fardar de Pokémon lo que haga falta!$"

Route110_Text_IsabelRematchDefeated:
	.string "Ésta no era precisamente la idea que\n"
	.string "tenía yo...$"

Route110_Text_IsabelRematchPostBattle:
	.string "No creo que fardar de Pokémon me canse\n"
	.string "jamás. ¡Pero también me gusta luchar!$"

Route110_Text_TimmyIntro:
	.string "He encontrado algunos Pokémon\n"
	.string "carismáticos entre la hierba.$"

Route110_Text_TimmyDefeated:
	.string "Que tengan carisma no basta para\n"
	.string "ganar...$"

Route110_Text_TimmyPostBattle:
	.string "Lo que pasa es que cuesta controlar a\n"
	.string "los Pokémon que acabas de atrapar...$"

Route110_Text_AlyssaIntro:
	.string "Me he caído del camino de bicis...\p"
	.string "¡Aunque no tengas la culpa, vas a pagar\n"
	.string "por ello!$"

Route110_Text_AlyssaDefeated:
	.string "¡Huy! ¡He perdido!$"

Route110_Text_AlyssaPostBattle:
	.string "Me he caído... He perdido... ¡Qué\n"
	.string "humillación más grande!$"

Route110_Text_JosephIntro:
	.string "¡Vale! ¡A tope! Si no sabes moverte,\n"
	.string "¡te quedas atrás!$"

Route110_Text_JosephDefeated:
	.string "¡Tú sí que sabes moverte!$"

Route110_Text_JosephPostBattle:
	.string "¡Esto no me va a venir abajo!\n"
	.string "¡Perder me ha hecho más fuerte!$"

Route110_Text_KalebIntro:
	.string "Cuando unos Pokémon monos se ayudan\n"
	.string "entre sí... ¡No hay imagen más\l"
	.string "encantadora!$"

Route110_Text_KalebDefeated:
	.string "¿Pero tú no tienes corazón o qué?$"

Route110_Text_KalebPostBattle:
	.string "Ea, ea, tranquilos, chiquitines.\n"
	.string "Habéis dado lo mejor de vosotros.$"

Route111_Text_DrewIntro:
	.string "¡Oh, hola! Esas gafas a prueba de arena\n"
	.string "te quedan bien. Pero yo creo que me\l"
	.string "quedarían mejor a mí.\p"
	.string "¡Vamos a ver a quién le quedan mejor\n"
	.string "mediante un combate!$"

Route111_Text_DrewDefeat:
	.string "No podía ver lo que pasaba a los lados\n"
	.string "por culpa de las gafas a prueba de arena.$"

Route111_Text_DrewPostBattle:
	.string "Las gafas a prueba de arena permiten\n"
	.string "cruzar tormentas de arena.\l"
	.string "¡Eso me alegra!$"

Route111_Text_HeidiIntro:
	.string "Estoy de picnic en el desierto.\p"
	.string "Siempre puedes encontrar un entrenador,\n"
	.string "así que también puedo disfrutar de un\l"
	.string "combate aquí.$"

Route111_Text_HeidiDefeat:
	.string "¡Oooh! ¡Qué malo eres!$"

Route111_Text_HeidiPostBattle:
	.string "Cuando luchas en una tormenta de arena,\n"
	.string "vigila los PS de tus Pokémon.\p"
	.string "¡Pueden debilitarse si no los controlas!$"

Route111_Text_BeauIntro:
	.string "Llevar estas gafas a prueba de arena me\n"
	.string "hace sentir como un superhéroe.\l"
	.string "¡Ahora nadie puede vencerme!$"

Route111_Text_BeauDefeat:
	.string "No puedo ganar sólo con espíritu...$"

Route111_Text_BeauPostBattle:
	.string "Algún día seré un verdadero héroe.\n"
	.string "Voy a esforzarme más para hacerme más\l"
	.string "fuerte junto con mis Pokémon.$"

Route111_Text_BeckyIntro:
	.string "He oído que hay fósiles en el desierto.\n"
	.string "¿Dónde estarán?$"

Route111_Text_BeckyDefeat:
	.string "Me he quedado corta...$"

Route111_Text_BeckyPostBattle:
	.string "Si pueden encontrar fósiles en el\n"
	.string "desierto, antes debió de ser un mar.$"

Route111_Text_DustyIntro:
	.string "¡Llevo treinta años buscando ruinas\n"
	.string "antiguas! ¿Vas a desafiarme?$"

Route111_Text_DustyDefeat:
	.string "Mientras buscaba ruinas, no he buscado\n"
	.string "Pokémon fuertes...$"

Route111_Text_DustyPostBattle:
	.string "¡Llevo treinta años buscando ruinas\n"
	.string "antiguas!\p"
	.string "No, espera, ¿eran cuarenta?\n"
	.string "¿Cuántos eran?$"

Route111_Text_DustyRegister:
	.string "No he estado buscando Pokémon fuertes.\p"
	.string "Pero, por alguna razón, me gustan\n"
	.string "mucho los PokéNav.$"

Route111_Text_DustyRematchIntro:
	.string "¡Llevo treinta años buscando ruinas\n"
	.string "antiguas!\p"
	.string "No, espera, ¿eran cuarenta?\n"
	.string "De todos modos, ¿vas a desafiarme?$"

Route111_Text_DustyRematchDefeat:
	.string "No he encontrado ruinas, ni tampoco\n"
	.string "Pokémon fuertes...$"

Route111_Text_DustyPostRematch:
	.string "¡Llevo treinta años buscando ruinas\n"
	.string "antiguas!\p"
	.string "No, espera, ¿eran cuarenta años?\p"
	.string "Mmm... Podrían incluso ser cincuenta...\n"
	.string "¿Cuánto tiempo llevo en esto?$"

Route111_Text_TravisIntro:
	.string "¡Estoy lleno de energía!\n"
	.string "¡Y mi Pokémon también está lleno de\l"
	.string "energía!$"

Route111_Text_TravisDefeat:
	.string "Mi Pokémon ha perdido toda su energía...$"

Route111_Text_TravisPostBattle:
	.string "Cuando veo a un entrenador lleno de\n"
	.string "energía, no puedo evitar mirarlo.$"

Route111_Text_IreneIntro:
	.string "No sé adónde vas, pero ¿quieres\n"
	.string "luchar?$"

Route111_Text_IreneDefeat:
	.string "¡Oh, eres asquerosamente bueno!$"

Route111_Text_IrenePostBattle:
	.string "Estoy pensando en ir al Monte Cenizo,\n"
	.string "pero las vistas por aquí también son\l"
	.string "muy bonitas.$"

Route111_Text_DaisukeIntro:
	.string "¡Me desafío a todos los que encuentro\n"
	.string "para entrenarme!$"

Route111_Text_DaisukeDefeat:
	.string "¡Me rindo! ¡Me doy por vencido!$"

Route111_Text_DaisukePostBattle:
	.string "Todo lo que puedo hacer es seguir\n"
	.string "entrenando hasta poder derrotar a\l"
	.string "entrenadores fuertes como tú.$"

Route111_Text_WiltonIntro:
	.string "Muéstrame lo mucho que has fortalecido\n"
	.string "a tus Pokémon.$"

Route111_Text_WiltonDefeat:
	.string "Veo que los has fortalecido\n"
	.string "considerablemente.$"

Route111_Text_WiltonPostBattle:
	.string "Los Pokémon y los entrenadores\n"
	.string "aprenden mucho luchando.\p"
	.string "Lo importante es nunca rendirse,\n"
	.string "aunque pierdas.$"

Route111_Text_WiltonRegister:
	.string "Hay mucho que aprender de tu estilo de\n"
	.string "entrenamiento.\p"
	.string "Te pido una revancha si te parece bien.$"

Route111_Text_WiltonRematchIntro:
	.string "Estamos entrenando aquí para elevar\n"
	.string "nuestro nivel al siguiente.\l"
	.string "¡Quédate y entrena con nosotros!$"

Route111_Text_WiltonRematchDefeat:
	.string "¡Ooh, eres decente!$"

Route111_Text_WiltonPostRematch:
	.string "Como eres tan fuerte, deberías aspirar\n"
	.string "a la Liga Pokémon.$"

Route111_Text_BrookeIntro:
	.string "Oh, tus Pokémon parecen actores\n"
	.string "serios. Debo pedirte un combate.$"

Route111_Text_BrookeDefeat:
	.string "¡No solo parecían fuertes,\n"
	.string "lo eran!$"

Route111_Text_BrookePostBattle:
	.string "Pensaba que estaba entrenando a mis\n"
	.string "Pokémon diligentemente, pero oh, no,\l"
	.string "todavía queda mucho por hacer.$"

Route111_Text_BrookeRegister:
	.string "Ojalá pudiera hacerme amiga de más\n"
	.string "gente fuerte como tú.$"

Route111_Text_BrookeRematchIntro:
	.string "Puedes hacer que los Pokémon sean más\n"
	.string "fuertes o más débiles dependiendo de\l"
	.string "los movimientos que les enseñes.\p"
	.string "¿Qué movimientos conocen tus Pokémon?$"

Route111_Text_BrookeRematchDefeat:
	.string "¡Les has enseñado buenos movimientos!$"

Route111_Text_BrookePostRematch:
	.string "Quizá debería haber impedido que mis\n"
	.string "Pokémon evolucionaran hasta que\l"
	.string "aprendieran mejores movimientos...$"

Route111_Text_CeliaIntro:
	.string "No debería haber venido a un lugar\n"
	.string "como este de picnic.$"

Route111_Text_CeliaDefeat:
	.string "¡Aaaah!\n"
	.string "¡Realmente no debería haber venido!$"

Route111_Text_CeliaPostBattle:
	.string "En una tormenta de arena como esta, no\n"
	.string "puedo preparar el picnic incluso con\l"
	.string "las gafas a prueba de arena puestas...$"

Route111_Text_BryanIntro:
	.string "¿Qué tan fuerte eres?\n"
	.string "¡Vamos a descubrir ese secreto!$"

Route111_Text_BryanDefeat:
	.string "¡Oh! ¡Tu fuerza!\n"
	.string "¡Está envuelta en misterio!$"

Route111_Text_BryanPostBattle:
	.string "¡Este desierto alberga misterios en\n"
	.string "sus arenas movedizas!$"

Route111_Text_BrandenIntro:
	.string "Te daré parte de mi bocadillo si\n"
	.string "pierdes.$"

Route111_Text_BrandenDefeat:
	.string "¡Tch! Pensé que un bocadillo sería\n"
	.string "suficiente soborno...$"

Route111_Text_BrandenPostBattle:
	.string "Mi Sandshrew adora comerse mis\n"
	.string "bocadillos.$"

Route111_Text_TyronIntro:
	.string "¡Este es mi tipo de Pokémon favorito!$"

Route111_Text_TyronDefeat:
	.string "¡Espera!\n"
	.string "¿Has visto bien mi Pokémon?$"

Route111_Text_TyronPostBattle:
	.string "Cuando tengo un combate, me encanta\n"
	.string "presumir de mis Pokémon.\p"
	.string "¡Apuesto a que a todo el mundo le gusta\n"
	.string "presumir cuando entra en un combate!$"

Route111_Text_CelinaIntro:
	.string "Muéstrame cómo poner un poco de\n"
	.string "emoción en mi vida.$"

Route111_Text_CelinaDefeat:
	.string "Oh... Dios...\n"
	.string "Eso fue demasiada emoción.$"

Route111_Text_CelinaPostBattle:
	.string "Mi pulso todavía está acelerado.\n"
	.string "Eres un entrenador fabuloso.$"

Route111_Text_HaydenIntro:
	.string "Cuando tienes tanta hambre como yo,\n"
	.string "¡no hay lugar para la compasión!$"

Route111_Text_HaydenDefeat:
	.string "¡Groan...$"

Route111_Text_HaydenPostBattle:
	.string "¡Mi estómago está rugiendo!\n"
	.string "Quizá pueda asar algunas bayas...$"

Route111_Text_BiancaIntro:
	.string "¿Vienes de Malvalona?\n"
	.string "¡Entonces debes estar lleno de energía!$"

Route111_Text_BiancaDefeat:
	.string "¡Ooh lala!\n"
	.string "¡Eso es mucho para asimilar!$"

Route111_Text_BiancaPostBattle:
	.string "Por aquí...\n"
	.string "Tienes bastante camino por delante.$"

Route112_Text_BriceIntro:
	.string "¡Ja, ja, ja, ja! ¿Qué tal si luchamos\n"
	.string "un poco? ¡Tú y yo! ¡Ja, ja, ja, ja!$"

Route112_Text_BriceDefeat:
	.string "¡He perdido! ¡Ja, ja, ja, ja!$"

Route112_Text_BricePostBattle:
	.string "¡Ja, ja, ja, ja! ¡Algo me está haciendo\n"
	.string "cosquillas en la nariz! Ji, ji, ji, ji...\l"
	.string "¡A-a-achís!$"

Route112_Text_TrentIntro:
	.string "Tengo las piernas fuertes como un roble\n"
	.string "de tanto subir y bajar montañas.\l"
	.string "¡No van a flaquear tan fácilmente!$"

Route112_Text_TrentDefeat:
	.string "¡Ay! ¡Me ha dado un calambre!$"

Route112_Text_TrentPostBattle:
	.string "Prueba a caminar, pero en serio, por\n"
	.string "estos senderos de montaña con una\l"
	.string "mochila bien cargada. ¡Por fuerza te\l"
	.string "pones en forma!$"

Route112_Text_TrentRegister:
	.string "Ah, tengo calambres en las piernas.\n"
	.string "¿Me puedes pasar unas vendas que hay\l"
	.string "en mi mochila? ¡No, eso es mi PokéNav!\l"
	.string "Bueno, vale, te voy a registrar.$"

Route112_Text_TrentRematchIntro:
	.string "Me mantengo en forma gracias al\n"
	.string "senderismo. ¡Estoy hecho un toro!$"

Route112_Text_TrentRematchDefeat:
	.string "¿Estaré hecho un ternero?$"

Route112_Text_TrentRematchPostBattle:
	.string "Me han dicho que hay entrenadores muy\n"
	.string "fuertes en la cima del Monte Cenizo.\l"
	.string "¡Voy a ir allí a desafiarlos a todos!$"

Route112_Text_LarryIntro:
	.string "Soy fuerte psicológicamente. Perder no\n"
	.string "me supone ningún trauma.$"

Route112_Text_LarryDefeat:
	.string "¡Buaaaaaaaaaaaaa!$"

Route112_Text_LarryPostBattle:
	.string "¡No estoy llorando! ¡Es que me ha\n"
	.string "entrado algo en el ojo!$"

Route112_Text_CarolIntro:
	.string "Cuando sales de picnic, tienes que\n"
	.string "cantar a pleno pulmón. ¡Venga, canta\l"
	.string "conmigo!$"

Route112_Text_CarolDefeat:
	.string "¡Guau, qué fuerte eres!$"

Route112_Text_CarolPostBattle:
	.string "No importa lo bueno que seas cantando\n"
	.string "o entrenando Pokémon. ¡La cosa está en\l"
	.string "divertirse!$"

Route112_Text_BryantIntro:
	.string "¡He atrapado unos Pokémon alucinantes\n"
	.string "en la Senda Ígnea! ¡Mira, mira!$"

Route112_Text_BryantDefeat:
	.string "¡Menudo palizón me has dado!$"

Route112_Text_BryantPostBattle:
	.string "Me gusta tu forma de pelear. Tienes un\n"
	.string "estilo propio.$"

Route112_Text_ShaylaIntro:
	.string "¡Oh, qué placer cruzarme contigo!\n"
	.string "¡Estoy deseando luchar con una persona\l"
	.string "tan especial como tú!$"

Route112_Text_ShaylaDefeat:
	.string "¡Oh, qué fuerte eres! ¡No quepo en mí\n"
	.string "de asombro!$"

Route112_Text_ShaylaPostBattle:
	.string "¿Tienes un momento? Estaba pensando\n"
	.string "que quizás podríamos volver a luchar ya\l"
	.string "mismo... Pero si tienes cosas que hacer...$"

Route113_Text_JaylenIntro:
	.string "¿Sabes por qué es tan chachi estar por\n"
	.string "aquí?$"

Route113_Text_JaylenDefeat:
	.string "¡Aaaaah! ¡Esto no es nada chachi!$"

Route113_Text_JaylenPostBattle:
	.string "La ceniza volcánica no absorbe los rayos\n"
	.string "del sol, así que no se calienta. Por mí,\l"
	.string "chachi piruli... ¡No soporto el calor!$"

Route113_Text_DillonIntro:
	.string "Cuando un volcán entra en erupción, te\n"
	.string "das cuenta de que la tierra está viva.$"

Route113_Text_DillonDefeat:
	.string "¡Tienes la potencia de un volcán!$"

Route113_Text_DillonPostBattle:
	.string "Me has extinguido... ¿Lo pillas? Tú eres\n"
	.string "un volcán activo y yo uno extinguido,\l"
	.string "je, je, je. Vale, sí, no tiene gracia...$"

Route113_Text_MadelineIntro:
	.string "Uso este parasol para proteger a mi\n"
	.string "querido Numel de esta horrible y\l"
	.string "pegajosa ceniza volcánica.$"

Route113_Text_MadelineDefeat:
	.string "Uf, uf... Luchar con parasol es\n"
	.string "agotador.$"

Route113_Text_MadelinePostBattle:
	.string "Mi parasol y yo te esperamos. Déjame\n"
	.string "registrarte en mi PokéNav.$"

Route113_Text_MadelineRegister:
	.string "Mi parasol y yo te esperamos. Déjame\n"
	.string "registrarte en mi PokéNav.$"

Route113_Text_MadelineRematchIntro:
	.string "Oye, se te da muy bien esto. Estoy\n"
	.string "impresionada.$"

Route113_Text_MadelineRematchDefeat:
	.string "Uf, uf... Luchar con parasol es\n"
	.string "agotador.$"

Route113_Text_MadelinePostRematch:
	.string "Oye, se te da muy bien esto. Estoy\n"
	.string "impresionada.$"

Route113_Text_LaoIntro:
	.string "¡Surjo de entre las cenizas como una\n"
	.string "sombra! ¡Kiaaaaaaaaa! ¿Aceptas mi\l"
	.string "desafío?$"

Route113_Text_LaoDefeat:
	.string "Acepto mi derrota...$"

Route113_Text_LaoPostBattle:
	.string "Tengo que perfeccionar mi técnica de\n"
	.string "camuflaje. ¡Me piro, vampiro!$"

Route113_Text_LaoRegister:
	.string "¡Yijaaaa! ¡Maravíllate con la antigua\n"
	.string "técnica ninja de registro en PokéNav!$"

Route113_Text_LaoRematchIntro:
	.string "¡Surjo de entre las cenizas como una\n"
	.string "sombra! ¡Kiaaaaaaaaa! ¿Aceptas mi\l"
	.string "desafío?$"

Route113_Text_LaoRematchDefeat:
	.string "Acepto mi derrota...$"

Route113_Text_LaoPostRematch:
	.string "Mi perfecto camuflaje no me sirvió de\n"
	.string "nada porque mis habilidades de combate\l"
	.string "son inmaduras... ¡Me piro, vampiro!$"

Route113_Text_LungIntro:
	.string "¡Has sabido encontrarme! ¡Pero ahora\n"
	.string "debes derrotarme!$"

Route113_Text_LungDefeat:
	.string "Voy a usar el poder del ninjutsu...\n"
	.string "¡“remolino de sombras volcánico”!\l"
	.string "¿Que “yatá”? ¿Cómo que “yatá”?$"

Route113_Text_LungPostBattle:
	.string "¿Sabes lo más chungo de camuflarse? Que,\n"
	.string "si nadie te encuentra, te aburres.$"

Route113_Text_ToriIntro:
	.string "TEA: Nosotras dos recogemos ceniza y\n"
	.string "además entrenamos Pokémon.$"

Route113_Text_ToriDefeat:
	.string "TEA: Hemos perdido... Qué rollo... Me\n"
	.string "voy a buscar más ceniza...$"

Route113_Text_ToriPostBattle:
	.string "TEA: ¿Cuánta ceniza tenemos ya? ¿Es\n"
	.string "suficiente para la flauta blanca?$"

Route113_Text_ToriNotEnoughMons:
	.string "TEA: Nosotras dos recogemos ceniza y\n"
	.string "además entrenamos Pokémon.$"

Route113_Text_TiaIntro:
	.string "BEA: Nosotras dos recogemos ceniza y\n"
	.string "además entrenamos Pokémon.$"

Route113_Text_TiaDefeat:
	.string "BEA: Hemos perdido... Qué rollo... Me\n"
	.string "voy a buscar más ceniza...$"

Route113_Text_TiaPostBattle:
	.string "BEA: ¡Tenemos un montón de ceniza! ¿Es\n"
	.string "bastante para la flauta blanca?$"

Route113_Text_TiaNotEnoughMons:
	.string "BEA: Si quieres luchar contra nosotras,\n"
	.string "tienes que tener dos Pokémon.\l"
	.string "¡No es justo si no es así!$"

Route113_Text_CobyIntro:
	.string "¡Je, con estas alas te voy a enviar\n"
	.string "volando por los aires!$"

Route113_Text_CobyDefeat:
	.string "¿Qué? ¿Cómo? ¿Cuándo? ¿Por qué?$"

Route113_Text_CobyPostBattle:
	.string "Que me derroten con tanta facilidad me\n"
	.string "deja sin palabras...$"

Route113_Text_SophieIntro:
	.string "Este calor me da sueño. Lucha conmigo,\n"
	.string "a ver si me despierto.$"

Route113_Text_SophieDefeat:
	.string "Seguro que estoy soñando. ¡No puedo\n"
	.string "haber perdido!$"

Route113_Text_SophiePostBattle:
	.string "Perder me quema mucho... Y lo único que\n"
	.string "me relaja es echar una siestecita, así\l"
	.string "que zzzzz...$"

Route113_Text_LawrenceIntro:
	.string "¿Es posible que estés recogiendo cenizas\n"
	.string "volcánicas?$"

Route113_Text_LawrenceDefeat:
	.string "Je, je, je, qué cenizo soy... Has ganado\n"
	.string "con todas las de la ley.$"

Route113_Text_LawrencePostBattle:
	.string "Me voy a esconder entre las cenizas y,\n"
	.string "si te he visto, no me acuerdo.$"

Route113_Text_WyattIntro:
	.string "¿Qui-quieres luchar conmigo? ¿Aunque\n"
	.string "acabe de capturar mis Pokémon?$"

Route113_Text_WyattDefeat:
	.string "¿Te alegra ha-haber ganado? ¿Aunque no\n"
	.string "sea más que un novato?$"

Route113_Text_WyattPostBattle:
	.string "Oh, ¿te dignas dirigir la palabra al\n"
	.string "perdedor? ¿Tú siempre vas de guay?\l"
	.string "¡Bah!$"

Route114_Text_LennyIntro:
	.string "¡Ue-i-a-oooo!\p"
	.string "Como aquí no hay eco, me pongo a cantar\n"
	.string "al estilo tirolés para divertirme.$"

Route114_Text_LennyDefeat:
	.string "¡Ue-ia-ooo!$"

Route114_Text_LennyPostBattle:
	.string "¡Cuando era un pitufín, creía que el eco\n"
	.string "era alguien escondido que repetía todo\l"
	.string "lo que yo decía!$"

Route114_Text_LucasIntro:
	.string "Si no te preparas bien antes, ni se te\n"
	.string "ocurra hacer montañismo.$"

Route114_Text_LucasDefeat:
	.string "Las montañas son traicioneras...$"

Route114_Text_LucasPostBattle:
	.string "En invierno las montañas encierran\n"
	.string "trampas mortales: tormentas de nieve,\l"
	.string "avalanchas...$"

Route114_Text_ShaneIntro:
	.string "¡Acampar es la caña! ¡Puedes pescar,\n"
	.string "asar patatas y contar historias de\l"
	.string "terror! ¡Pero lo mejor son los combates\l"
	.string "Pokémon!$"

Route114_Text_ShaneDefeat:
	.string "¡Eres mucho más fuerte que yo!$"

Route114_Text_ShanePostBattle:
	.string "Me encanta ir de acampada con mis\n"
	.string "Pokémon.$"

Route114_Text_NancyIntro:
	.string "Me apetece un combate para bajar la\n"
	.string "comida. ¿Qué me dices?$"

Route114_Text_NancyDefeat:
	.string "¡Oh, no!$"

Route114_Text_NancyPostBattle:
	.string "Creo que he comido demasiado... Me está\n"
	.string "entrando sueño...$"

Route114_Text_SteveIntro:
	.string "¡Jua, jua, jua, jua! ¿Quieres luchar\n"
	.string "contra mi Pokémon?$"

Route114_Text_SteveDefeat:
	.string "Mi pobre Pokémon...$"

Route114_Text_StevePostBattle:
	.string "¡Acuérdate de mí! ¡Nuestro próximo\n"
	.string "encuentro será inolvidable!\p"
	.string "Yo sé muy bien qué Pokémon quiero... ¡Uno\n"
	.string "con la piel dura y llena de bultos,\l"
	.string "cuernos enormes y colmillos afilados!$"

Route114_Text_SteveRegister:
	.string "¡Acuérdate de mí! ¡Nuestro próximo\n"
	.string "encuentro será inolvidable!$"

Route114_Text_SteveRematchIntro:
	.string "¡Jua, jua, jua, jua! ¿Quieres luchar\n"
	.string "contra mi Pokémon?$"

Route114_Text_SteveRematchDefeat:
	.string "¡Qué suerte la mía poder ver tus\n"
	.string "Pokémon!$"

Route114_Text_StevePostRematch:
	.string "¡Jua, jua, jua, jua!\p"
	.string "Cuando veo combates Pokémon, me pongo\n"
	.string "todo tembloroso y nervioso...$"

Route114_Text_BernieIntro:
	.string "Si vas a encender una fogata, ten agua\n"
	.string "cerca por si acaso...$"

Route114_Text_BernieDefeat:
	.string "¿Ves? ¡Casi me quemo la mano!$"

Route114_Text_BerniePostBattle:
	.string "Tienes que tener muchísimo cuidado\n"
	.string "cuando haces fogatas en el bosque...\l"
	.string "¡El fuego es peligroso!$"

Route114_Text_BernieRegister:
	.string "¡Ardo de ganas de enfrentarme a ti!\n"
	.string "¡Vamos a registrarnos!$"

Route114_Text_BernieRematchIntro:
	.string "¿Tienes agua a mano por si la fogata se\n"
	.string "desmanda?$"

Route114_Text_BernieRematchDefeat:
	.string "¡Me has apagado antes de que pudiera\n"
	.string "encenderme!$"

Route114_Text_BerniePostRematch:
	.string "Tienes que tener muchísimo cuidado\n"
	.string "cuando haces fogatas en el bosque...\l"
	.string "¡El fuego es peligroso!$"

Route114_Text_ClaudeIntro:
	.string "En una competición de pesca, no\n"
	.string "tendrías ni una oportunidad... A ver,\l"
	.string "¡enséñame tus Pokémon!$"

Route114_Text_ClaudeDefeat:
	.string "En una competición de pesca, te hubiera\n"
	.string "dado mil vueltas...$"

Route114_Text_ClaudePostBattle:
	.string "Creo que voy a probar suerte en la\n"
	.string "Cascada Meteoro, a ver si pican. Estoy\l"
	.string "convencido de que hay peces muy gordos\l"
	.string "por allí...$"

Route114_Text_NolanIntro:
	.string "Me gusta pescar, ¡pero también me gusta\n"
	.string "luchar! Si alguien me reta, no puedo\l"
	.string "decir que no, aunque esté pescando.$"

Route114_Text_NolanDefeat:
	.string "Me gusta luchar, pero eso no quiere\n"
	.string "decir que se me dé bien en absoluto...$"

Route114_Text_NolanPostBattle:
	.string "¡La próxima vez verás! Es lo que siempre\n"
	.string "digo, para animarme a seguir con los\l"
	.string "combates Pokémon.$"

Route114_Text_TyraIntro:
	.string "TULA: Sí, sí, encantada. Hoy estoy de\n"
	.string "buen humor. Te voy a enseñar algo sobre\l"
	.string "Pokémon.$"

Route114_Text_TyraDefeat:
	.string "TULA: ¡Qué gran estilo de lucha! ¡No te\n"
	.string "queda gran cosa que aprender!$"

Route114_Text_TyraPostBattle:
	.string "TULA: Pero mi pupila, Ilda, sí tiene que\n"
	.string "aprender bastante todavía...$"

Route114_Text_TyraNotEnoughMons:
	.string "TULA: Si quieres luchar con nosotras,\n"
	.string "tienes que tener dos Pokémon.\l"
	.string "¡No es justo si no es así!$"

Route114_Text_IvyIntro:
	.string "ILDA: ¿Quién te ha enseñado lo que sabes\n"
	.string "sobre los Pokémon?$"

Route114_Text_IvyDefeat:
	.string "ILDA: ¡Vaya estilazo combatiendo!$"

Route114_Text_IvyPostBattle:
	.string "ILDA: Empecé a entrenar Pokémon porque\n"
	.string "Tula, mi tutora, quiere que sea una\l"
	.string "figura algún día.$"

Route114_Text_IvyNotEnoughMons:
	.string "ILDA: Si quieres luchar con nosotras,\n"
	.string "tienes que tener dos Pokémon.\l"
	.string "¡No es justo si no es así!$"

Route114_Text_KaiIntro:
	.string "¡He pescado uno enooorme! ¡Grande como\n"
	.string "él solo, ya verás!$"

Route114_Text_KaiDefeat:
	.string "¿Qué ha pasado aquí? ¿Se habrá encogido\n"
	.string "mi Pokémon?$"

Route114_Text_KaiPostBattle:
	.string "¡Me importa un comino! ¡Voy a pescar uno\n"
	.string "aún mayor!$"

Route114_Text_CharlotteIntro:
	.string "¡Quiero que sepas una cosa! ¡No soy sólo\n"
	.string "una cara bonita!$"

Route114_Text_CharlotteDefeat:
	.string "¡Esta pelea ha sido de todo menos bonita!$"

Route114_Text_CharlottePostBattle:
	.string "Yo no quiero un Pokémon que sea\n"
	.string "únicamente una monada. Me gustan los\l"
	.string "Pokémon bonitos que, además, tienen\l"
	.string "alguna peculiaridad.$"

Route114_Text_AngelinaIntro:
	.string "¿Has conseguido que tus Pokémon evolucionen\n"
	.string "mucho?$"

Route114_Text_AngelinaDefeat:
	.string "Ya veo que sí. Pues mira qué bien.$"

Route114_Text_AngelinaPostBattle:
	.string "¡Algunos Pokémon cambian tanto al\n"
	.string "evolucionar que ni los reconoces!$"

Route115_Text_TimothyIntro:
	.string "Mmmm... Pareces capaz... ¡Comprobemos\n"
	.string "si además lo eres!$"

Route115_Text_TimothyDefeat:
	.string "¡Pues lo eres mucho más de lo que lo\n"
	.string "pareces!$"

Route115_Text_TimothyPostBattle:
	.string "Nadie nace sabiendo. ¡Hay que esforzarse!\n"
	.string "Ésa es una gran verdad.$"

Route115_Text_TimothyRegister:
	.string "Mmm... La derrota que sufrí es ahora\n"
	.string "apenas un recuerdo lejano. Si te parece\l"
	.string "bien, quisiera tener otra oportunidad de\l"
	.string "vencerte en combate.$"

Route115_Text_TimothyRematchIntro:
	.string "Mmmm... Pareces capaz... ¡Comprobemos\n"
	.string "si además lo eres!$"

Route115_Text_TimothyRematchDefeat:
	.string "¡Pues lo eres mucho más de lo que lo\n"
	.string "pareces!$"

Route115_Text_TimothyPostRematch:
	.string "Nadie nace sabiendo. ¡Hay que esforzarse!\n"
	.string "Ésa es una gran verdad.$"

Route115_Text_KoichiIntro:
	.string "¡Tú! ¡Mis Machop! ¡Pelead! ¡Ahora!$"

Route115_Text_KoichiDefeat:
	.string "¡Ay, huy, oy!$"

Route115_Text_KoichiPostBattle:
	.string "¡Mis Machop! ¡Mientras sigan motivados,\n"
	.string "yo seguiré mejorando con ellos!$"

Route115_Text_NobIntro:
	.string "¡Mi mayor habilidad es romper ladrillos\n"
	.string "con la frente!$"

Route115_Text_NobDefeat:
	.string "¡Ayyyyy! ¡Qué dolor de cabeza más maloooo!$"

Route115_Text_NobPostBattle:
	.string "Estoy enseñando karate a mi Pokémon.\n"
	.string "Creo que acabará siendo mucho mejor que\l"
	.string "yo. Qué emoción.$"

Route115_Text_NobRegister:
	.string "¡Me has impresionado hasta la médula!\n"
	.string "¡Volvamos a luchar cuando haya terminado\l"
	.string "mi entrenamiento!$"

Route115_Text_NobRematchIntro:
	.string "Tras perder contra ti, he entrenado a\n"
	.string "fondo para mejorar mis habilidades.\l"
	.string "¡Vamos, dame una revancha!$"

Route115_Text_NobRematchDefeat:
	.string "¡Ayyyyy! ¡Qué dolor de cabeza más maloooo!$"

Route115_Text_NobPostRematch:
	.string "¡Mis Machop! ¡Mientras sigan motivados,\n"
	.string "yo seguiré mejorando con ellos!$"

Route115_Text_CyndyIntro:
	.string "Esta playa es mi campo de entrenamiento\n"
	.string "secreto. ¡Ya te puedes ir a otra parte!$"

Route115_Text_CyndyDefeat:
	.string "¡No he entrenado bastante!$"

Route115_Text_CyndyPostBattle:
	.string "Me gusta entrenarme aquí porque la arena\n"
	.string "amortigua las caídas y así no te haces\l"
	.string "tanto daño.$"

Route115_Text_CyndyRegister:
	.string "Venga, va, puedes venir aquí cuando te\n"
	.string "apetezca, pero a cambio quiero volver a\l"
	.string "luchar contigo.$"

Route115_Text_CyndyRematchIntro:
	.string "¡Vale, vamos a luchar!$"

Route115_Text_CyndyRematchDefeat:
	.string "¡No he entrenado bastante!$"

Route115_Text_CyndyPostRematch:
	.string "Me gusta entrenarme aquí porque la arena\n"
	.string "amortigua las caídas y así no te haces\l"
	.string "tanto daño.$"

Route115_Text_HectorIntro:
	.string "Tengo un Pokémon rarísimo. ¿A que quieres\n"
	.string "verlo?$"

Route115_Text_HectorDefeat:
	.string "Tú... ¡Tú quieres quedarte con mi Pokémon!\n"
	.string "¿A que sí?$"

Route115_Text_HectorPostBattle:
	.string "Tengo un Pokémon raro y eso es lo único\n"
	.string "que me importa para ser feliz.$"

Route115_Text_KyraIntro:
	.string "¡Lucharé mientras corro! ¡A ver si\n"
	.string "aguantas el ritmo!$"

Route115_Text_KyraDefeat:
	.string "Ah, que me ahogo...$"

Route115_Text_KyraPostBattle:
	.string "¡Intentar luchar y correr al mismo tiempo\n"
	.string "ha sido un error! Será mejor que haga\l"
	.string "unos estiramientos para relajarme...$"

Route115_Text_JaidenIntro:
	.string "¡Toma ya! ¡Ataque ninja Pokémon en\n"
	.string "acción!$"

Route115_Text_JaidenDefeat:
	.string "¡Buaaaaa! ¡Nuestra estrategia ha fallado!$"

Route115_Text_JaidenPostBattle:
	.string "Pero mis Pokémon eran geniales, ¡no te\n"
	.string "atrevas a negarlo!$"

Route115_Text_HeleneIntro:
	.string "¡Mis Pokémon son cinturón negro en\n"
	.string "fortaleza!$"

Route115_Text_HeleneDefeat:
	.string "¡Qué humillación!$"

Route115_Text_HelenePostBattle:
	.string "No suelo encontrar a nadie que me\n"
	.string "aventaje... ¡Ya sé! Eres líder de\l"
	.string "gimnasio, ¿verdad?$"

Route115_Text_AlixIntro:
	.string "¡No te escondas que te he visto! ¡Ahora\n"
	.string "no puedes escapar!$"

Route115_Text_AlixDefeat:
	.string "¡Bah! ¡Te defiendes bien!$"

Route115_Text_AlixPostBattle:
	.string "En fin, visto lo visto, creo que me voy a\n"
	.string "teletransportar a casa.$"

Route115_Text_MarleneIntro:
	.string "Has interrumpido mi meditación... Y vas\n"
	.string "a pagar por esa afrenta...$"

Route115_Text_MarleneDefeat:
	.string "¡Me has roto la concentración!$"

Route115_Text_MarlenePostBattle:
	.string "Quisiera meditar junto a mis Pokémon,\n"
	.string "pero este lugar no se presta a ello...$"

Route116_Text_ClarkIntro:
	.string "Si no acaban el túnel, no importa: en vez\n"
	.string "de atravesar la montaña, la escalaré.$"

Route116_Text_ClarkDefeat:
	.string "Uf... Uf... Me he quedado sin aliento...$"

Route116_Text_ClarkPostBattle:
	.string "¡Qué más da que haya túnel o no! Los\n"
	.string "montañeros lo tenemos chupado.$"

Route116_Text_JoeyIntro:
	.string "¡Mis Pokémon son lo más! ¡Ahora vas a\n"
	.string "ver!$"

Route116_Text_JoeyDefeat:
	.string "¡Ay! ¡Me he hecho un arañazo! ¿Dónde\n"
	.string "hay tiritas por aquí?$"

Route116_Text_JoeyPostBattle:
	.string "Las tiritas son una señal de todo lo que\n"
	.string "se ha luchado. ¡Mira mi colección!$"

Route116_Text_JoseIntro:
	.string "Mis Pokémon de tipo bicho son duros\n"
	.string "como ellos solos... ¡Ahora verás!$"

Route116_Text_JoseDefeat:
	.string "¡He perdido! ¡Y eso que pensaba que esto\n"
	.string "era pan comido!$"

Route116_Text_JosePostBattle:
	.string "Los Pokémon de tipo bicho evolucionan\n"
	.string "muy rápido. Es decir, mejoran rápido.$"

Route116_Text_JaniceIntro:
	.string "¡Déjame mostrarte lo fuerte que es mi\n"
	.string "Pokémon del alma!$"

Route116_Text_JaniceDefeat:
	.string "Eres un pelín mejor que yo...$"

Route116_Text_JanicePostBattle:
	.string "Los Pokémon que son dulces y fuertes son\n"
	.string "los mejores, en mi opinión.$"

Route116_Text_JerryIntro:
	.string "Aprendemos un montón de teoría en la\n"
	.string "Escuela de entrenadores. ¡Ha llegado la\l"
	.string "hora de practicar!$"

Route116_Text_JerryDefeat:
	.string "He estado ganduleando en clase, por eso\n"
	.string "he perdido...$"

Route116_Text_JerryPostBattle:
	.string "Voy a tener que repetir el curso en la\n"
	.string "Escuela de entrenadores. Si no, Petra va\l"
	.string "a echar humo...$"

Route116_Text_JerryRegister1:
	.string "Aprendemos un montón de teoría en la\n"
	.string "Escuela de entrenadores. ¡Ha llegado la\l"
	.string "hora de practicar!$"

Route116_Text_JerryRegister2:
	.string "Aprendemos un montón de teoría en la\n"
	.string "Escuela de entrenadores. ¡Ha llegado la\l"
	.string "hora de practicar!$"

Route116_Text_JerryRematchIntro:
	.string "He estado empollando un montón en la\n"
	.string "Escuela de entrenadores. Esta vez no\l"
	.string "voy a perder...$"

Route116_Text_JerryRematchDefeat:
	.string "Pero... Pero... ¡Pero si he estudiado\n"
	.string "mogollón!$"

Route116_Text_JerryPostRematch:
	.string "Voy a tener que repetir el curso en la\n"
	.string "Escuela de la entrenadores. Si no, Petra\l"
	.string "va a echar humo...$"

Route116_Text_KarenIntro:
	.string "Yo estudio en la escuela, en casa, en el\n"
	.string "camino de la escuela a casa...$"

Route116_Text_KarenDefeat:
	.string "No me lo puedo creer... ¿He perdido?$"

Route116_Text_KarenPostBattle:
	.string "Aaaaah... ¡Así nunca llegaré a ser una\n"
	.string "gran entrenadora, como Petra!$"

Route116_Text_KarenRegister1:
	.string "¡He hincado los codos a fondo desde la\n"
	.string "última vez! ¡Ahora vas a ver!$"

Route116_Text_KarenRegister2:
	.string "¡He hincado los codos a fondo desde la\n"
	.string "última vez! ¡Ahora vas a ver!$"

Route116_Text_KarenRematchIntro:
	.string "¡He hincado los codos a fondo desde la\n"
	.string "última vez! ¡Ahora vas a ver!$"

Route116_Text_KarenRematchDefeat:
	.string "No me lo puedo creer... ¿He perdido?\n"
	.string "¿Otra vez?$"

Route116_Text_KarenPostRematch:
	.string "¿Has vencido a Petra? Pues entonces es\n"
	.string "normal que no te gane... Al menos por\l"
	.string "ahora.$"

Route116_Text_SarahIntro:
	.string "Para tu información, nunca nadie ha\n"
	.string "logrado superarme en nada.$"

Route116_Text_SarahDefeat:
	.string "Ay, qué fatalidad. Es una nueva\n"
	.string "experiencia para mí.$"

Route116_Text_SarahPostBattle:
	.string "Llevo un tren de vida muy lujoso. Puedo\n"
	.string "tener todo lo que deseo. Pero mi riqueza\l"
	.string "de poco sirve en lo que respecta a los\l"
	.string "Pokémon.$"

Route116_Text_DawsonIntro:
	.string "¡Cuando veas la maravillosa piel de mis\n"
	.string "Pokémon, caerás ante su belleza y la\l"
	.string "victoria será mía!$"

Route116_Text_DawsonDefeat:
	.string "¡No puede ser y además es imposible!$"

Route116_Text_DawsonPostBattle:
	.string "¡No, no, no y no! ¡Has destrozado la piel\n"
	.string "de mis Pokémon! ¡Y además me has\l"
	.string "despeinado! ¡Te pienso enviar la\l"
	.string "factura!$"

Route116_Text_DevanIntro:
	.string "¡Prepárate para una buena sacudida!$"

Route116_Text_DevanDefeat:
	.string "¡Aaaah! ¡Ha sido visto y no visto!$"

Route116_Text_DevanPostBattle:
	.string "Debería probar con diferentes tipos de\n"
	.string "Pokémon. Creo que me iría mejor.$"

Route116_Text_JohnsonIntro:
	.string "Por aquí no se llega a ningún sitio. Me\n"
	.string "aburro, así que, ¿luchamos?$"

Route116_Text_JohnsonDefeat:
	.string "Qué divertido, y eso que he perdido.$"

Route116_Text_JohnsonPostBattle:
	.string "¿Te quieres quedar aquí a hacerme\n"
	.string "compañía?$"

Route117_Text_IsaacIntro:
	.string "Oye, ¿podrías combatir contra los\n"
	.string "Pokémon que estoy entrenando?$"

Route117_Text_IsaacDefeat:
	.string "Los tuyos están entrenados a la perfección...$"

Route117_Text_IsaacPostBattle:
	.string "Los combates Pokémon no consisten sólo en\n"
	.string "potencia.\p"
	.string "Sacar lo mejor de las características\n"
	.string "especiales de cada Pokémon es otra forma\l"
	.string "de disfrutar de los combates.$"

Route117_Text_IsaacRegister:
	.string "Voy a redoblar mis esfuerzos en el\n"
	.string "entrenamiento. ¿Vendrás a verme?$"

Route117_Text_IsaacRematchIntro:
	.string "Los Pokémon que estoy entrenando están\n"
	.string "tan bien como siempre.$"

Route117_Text_IsaacRematchDefeat:
	.string "Los tuyos están entrenados a la perfección...$"

Route117_Text_IsaacPostRematch:
	.string "Los combates Pokémon no consisten sólo en\n"
	.string "potencia.\p"
	.string "Sacar lo mejor de las características\n"
	.string "especiales de cada Pokémon es otra forma\l"
	.string "de disfrutar de los combates.$"

Route117_Text_LydiaIntro:
	.string "Permíteme evaluar si estás cuidando\n"
	.string "bien a tus Pokémon.$"

Route117_Text_LydiaDefeat:
	.string "Sí, parece que los cuidas bien.$"

Route117_Text_LydiaPostBattle:
	.string "Prueba a entrenar a tus Pokémon\n"
	.string "prestando más atención a sus\l"
	.string "características.$"

Route117_Text_LydiaRegister:
	.string "Me alegra haber encontrado a un entrenador\n"
	.string "tan estupendo como tú. Espero volver a\l"
	.string "verte.$"

Route117_Text_LydiaRematchIntro:
	.string "Permíteme reevaluar si estás cuidando\n"
	.string "bien a tus Pokémon.$"

Route117_Text_LydiaRematchDefeat:
	.string "Sí, parece que los cuidas bien.$"

Route117_Text_LydiaPostRematch:
	.string "Los Pokémon parecen preferir diferentes\n"
	.string "tipos de Pokécubos según su\l"
	.string "naturaleza.$"

Route117_Text_DylanIntro:
	.string "Estoy en medio de un triatlón, pero da\n"
	.string "igual, ¡luchemos!$"

Route117_Text_DylanDefeat:
	.string "¡Se me han acabado las fuerzas!$"

Route117_Text_DylanPostBattle:
	.string "Creo que la he cagado...\p"
	.string "Puede que haya bajado de posición en la\n"
	.string "clasificación del triatlón por culpa de\l"
	.string "este combate...$"

Route117_Text_DylanRegister:
	.string "¿Los Pokémon también tienen que ser\n"
	.string "fuertes? ¡Entrena tú a mí también!$"

Route117_Text_DylanRematchIntro:
	.string "Estoy en medio de un triatlón, pero voy\n"
	.string "bastante bien. ¡Vamos a hacer un combate\l"
	.string "rápido!$"

Route117_Text_DylanRematchDefeat:
	.string "¡Se me han acabado las fuerzas otra vez!$"

Route117_Text_DylanPostRematch:
	.string "Soy el mejor en natación y ciclismo, pero\n"
	.string "en los combates Pokémon no tengo tanta\l"
	.string "confianza...$"

Route117_Text_MariaIntro:
	.string "Entreno para el triatlón con mis Pokémon,\n"
	.string "así que estoy bastante segura de mi\l"
	.string "velocidad.$"

Route117_Text_MariaDefeat:
	.string "Tendré que entrenar más, supongo...$"

Route117_Text_MariaPostBattle:
	.string "El entrenamiento sólo tiene sentido si lo\n"
	.string "haces con regularidad.\p"
	.string "¡Vale! ¡Voy a seguir entrenando!\n"
	.string "¡Mañana!$"

Route117_Text_MariaRegister:
	.string "Parece que entrenas bastante bien...\n"
	.string "Si quieres, podemos luchar más adelante.$"

Route117_Text_MariaRematchIntro:
	.string "¿Sigues entrenando? ¡Yo sí! ¡Te voy a\n"
	.string "mostrar las pruebas!$"

Route117_Text_MariaRematchDefeat:
	.string "Tendré que entrenar más, supongo...$"

Route117_Text_MariaPostRematch:
	.string "Voy a seguir entrenando mañana.\n"
	.string "¡Luchemos otra vez en algún momento!$"

Route117_Text_DerekIntro:
	.string "¡Antes era un cazabichos! ¡Ahora soy un\n"
	.string "friki de los bichos!\p"
	.string "¡Pero mi amor por los Pokémon sigue\n"
	.string "siendo el mismo!$"

Route117_Text_DerekDefeat:
	.string "Mi ineptitud también sigue siendo la\n"
	.string "misma...$"

Route117_Text_DerekPostBattle:
	.string "Sólo seguí mi corazón y ahora me llaman\n"
	.string "friki de los bichos...\p"
	.string "Pero es cierto que soy un experto en\n"
	.string "Pokémon de tipo bicho, así que tiene\l"
	.string "sentido que me llamen así.$"

Route117_Text_AnnaIntro:
	.string "ANA: Estoy con mi preciosa compañera\n"
	.string "novata. ¡Tengo que darlo todo!$"

Route117_Text_AnnaDefeat:
	.string "ANA: Estoy con mi preciosa compañera\n"
	.string "novata. ¡Déjame ganar!$"

Route117_Text_AnnaPostBattle:
	.string "ANA: Tus Pokémon tienen buenas\n"
	.string "combinaciones.\p"
	.string "¡Diría que eres el segundo mejor después\n"
	.string "de nosotras!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANA: ¡No podemos quedarnos con los\n"
	.string "brazos cruzados! ¿Volverás, verdad?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANA: Si quieres luchar contra nosotras,\n"
	.string "trae dos Pokémon contigo.$"

Route117_Text_MegIntro:
	.string "MEG: ¡Voy a luchar junto a mi super\n"
	.string "compañera novata y te vamos a ganar!$"

Route117_Text_MegDefeat:
	.string "MEG: ¡Oh, no!\n"
	.string "¡Lo siento, ANA! Te he decepcionado...$"

Route117_Text_MegPostBattle:
	.string "MEG: He arrastrado a ANA hacia abajo...\n"
	.string "Si no fuera por mí, ella habría ganado.$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: ¿Solo tienes un Pokémon?\n"
	.string "Entonces no podemos luchar contigo.\p"
	.string "Queremos un combate 2 contra 2.$"

Route117_Text_AnnaRematchIntro:
	.string "ANA: No puedo seguir perdiendo delante\n"
	.string "de mi compañera novata, ¿verdad?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANA: No he podido entrar en ritmo.$"

Route117_Text_AnnaPostRematch:
	.string "ANA: Tus Pokémon tienen buenas\n"
	.string "combinaciones.\p"
	.string "¡Diría que eres el segundo mejor después\n"
	.string "de nosotras!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANA: Si quieres luchar contra nosotras,\n"
	.string "trae dos Pokémon contigo.$"

Route117_Text_MegRematchIntro:
	.string "MEG: ¡Voy a luchar junto a mi compañera\n"
	.string "novata y esta vez vamos a ganar!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: ¡Demasiado fuerte!$"

Route117_Text_MegPostRematch:
	.string "MEG: He luchado junto a mi compañera\n"
	.string "novata, pero hemos perdido...\p"
	.string "Es tan desalentador...$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: ¿Solo tienes un Pokémon?\n"
	.string "Entonces no podemos luchar contigo.\p"
	.string "Queremos un combate 2 contra 2.$"

Route117_Text_MelinaIntro:
	.string "¿A que es agradable? ¿Luchar mientras\n"
	.string "contemplas flores tan bonitas?$"

Route117_Text_MelinaDefeat:
	.string "¡Oh, eso es impresionante!$"

Route117_Text_MelinaPostBattle:
	.string "Es maravilloso correr mientras miras\n"
	.string "flores.$"

Route117_Text_BrandiIntro:
	.string "¡Déjame mostrarte el poder oculto de\n"
	.string "un Pokémon de tipo psíquico!$"

Route117_Text_BrandiDefeat:
	.string "¡Asombroso!$"

Route117_Text_BrandiPostBattle:
	.string "Los Pokémon de tipo psíquico son\n"
	.string "complejos. Deberías intentar atrapar\l"
	.string "algunos.$"

Route117_Text_AishaIntro:
	.string "Concéntrate en ganar. ¡Así es como\n"
	.string "combato yo!$"

Route117_Text_AishaDefeat:
	.string "No pierdo el tiempo enfadándome por una\n"
	.string "derrota. Prefiero entrenar.$"

Route117_Text_AishaPostBattle:
	.string "Creo que si te preocupas por perder,\n"
	.string "es más probable que pierdas.$"

Route118_Text_RoseIntro:
	.string "El aroma de las flores tiene un poder\n"
	.string "mágico. Nos limpia el cuerpo y el alma.$"

Route118_Text_RoseDefeat:
	.string "Oh, Dios mío.\n"
	.string "Parece que he perdido.$"

Route118_Text_RosePostBattle:
	.string "Las flores, los Pokémon...\n"
	.string "Me encanta todo lo que huele bien.\p"
	.string "Las cosas que huelen mal...\n"
	.string "Prefiero pasar.$"

Route118_Text_RoseRegister:
	.string "¡Olor a PokéNav! ¡Tenemos que\n"
	.string "registrarnos el uno al otro!$"

Route118_Text_RoseRematchIntro:
	.string "¿Te ha atraído el dulce aroma?$"

Route118_Text_RoseRematchDefeat:
	.string "El poder del aroma...\n"
	.string "No parece haber funcionado mucho.$"

Route118_Text_RosePostRematch:
	.string "Si usas un aroma dulce correctamente,\n"
	.string "los Pokémon se sentirán atraídos.$"

Route118_Text_PerryIntro:
	.string "Los Pokémon pájaro que vuelan elegantemente\n"
	.string "por el cielo... ¡Son lo mejor!$"

Route118_Text_PerryDefeat:
	.string "Uf...\n"
	.string "Me he estrellado...$"

Route118_Text_PerryPostBattle:
	.string "Tienes unos Pokémon estupendos.\n"
	.string "Tendré que entrenar más a los míos.$"

Route118_Text_ChesterIntro:
	.string "¡Vuela, vuela!\n"
	.string "¡Mis Pokémon pájaro!$"

Route118_Text_ChesterDefeat:
	.string "Sí que han volado...$"

Route118_Text_ChesterPostBattle:
	.string "Si se hicieran más fuertes, podrían\n"
	.string "volar con más libertad...$"

Route118_Text_BarnyIntro:
	.string "Soy pescador, pero también entrenador.\n"
	.string "Entreno a los Pokémon que pesco.$"

Route118_Text_BarnyDefeat:
	.string "Pensaba que me estaba yendo bastante bien\n"
	.string "en el entrenamiento...$"

Route118_Text_BarnyPostBattle:
	.string "No he podido ganar entrenando Pokémon\n"
	.string "mientras pescaba...\p"
	.string "¿Estaría haciendo las cosas a medias?$"

Route118_Text_WadeIntro:
	.string "Para un pescador, el equipo es la clave.\p"
	.string "Pero para un entrenador, los ingredientes\n"
	.string "clave son los Pokémon y el corazón, por\l"
	.string "supuesto.$"

Route118_Text_WadeDefeat:
	.string "¿He perdido en corazón?$"

Route118_Text_WadePostBattle:
	.string "Ahora que lo pienso, la pesca es un\n"
	.string "combate entre un pescador y un Pokémon.$"

Route118_Text_DaltonIntro:
	.string "¡Deja que mi melodía conmueva tu alma!$"

Route118_Text_DaltonDefeat:
	.string "La-la-lalala...$"

Route118_Text_DaltonPostBattle:
	.string "Una guitarra eléctrica no siempre tiene\n"
	.string "que ser ruidosa...\p"
	.string "Se puede rasguear para arrancar una\n"
	.string "melodía que conmueva el corazón...$"

Route118_Text_DaltonRegister:
	.string "Cuando componga mejores melodías, tendrás\n"
	.string "que venir a escucharme, ¿vale?$"

Route118_Text_DaltonRematchIntro:
	.string "Una melodía de mis Pokémon y yo...\n"
	.string "Déjanos tocarla para tu alma.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-la-lalala...$"

Route118_Text_DaltonPostRematch:
	.string "Cuando toco, mis emociones deberían\n"
	.string "llegarte a través de mi guitarra\l"
	.string "eléctrica...$"

Route118_Text_DeandreIntro:
	.string "¡Vamos, vamos, vamos!\n"
	.string "¡Pokémon 1, 2 y 3!$"

Route118_Text_DeandreDefeat:
	.string "¿Entran, Pokémon? ¿Estáis bien?\n"
	.string "¡Pokémon 1, 2 y 3?!$"

Route118_Text_DeandrePostBattle:
	.string "¿A que mola tener un equipo de combate\n"
	.string "Pokémon?\p"
	.string "Puedes copiarme si quieres, no me\n"
	.string "importa.$"

Route119_Text_BrentIntro:
	.string "¡Somos el círculo de imitadores!\n"
	.string "¡Imitamos todo lo que haces!$"

Route119_Text_BrentDefeat:
	.string "¡Mira tú por dónde...! ¡He perdido!$"

Route119_Text_BrentPostBattle:
	.string "¿Que por qué mola imitar a la gente?\n"
	.string "Je, je, je... Nunca lo entenderías,\l"
	.string "mequetrefe...$"

Route119_Text_DonaldIntro:
	.string "¡Por fin nos conocemos! ¡Mis Pokémon\n"
	.string "de tipo bicho están encantados!$"

Route119_Text_DonaldDefeat:
	.string "Ojalá no te hubiera conocido nunca...$"

Route119_Text_DonaldPostBattle:
	.string "Quiero seguir imitando a gente...\n"
	.string "¿Te quieres pirar ya de una vez?$"

Route119_Text_TaylorIntro:
	.string "Si tú avanzas, nosotros avanzamos.\n"
	.string "Si retrocedes, nosotros también...$"

Route119_Text_TaylorDefeat:
	.string "Pero, si tú ganas, nosotros perdemos...$"

Route119_Text_TaylorPostBattle:
	.string "No puedo imitarte ganando un combate,\n"
	.string "es imposible. Qué frustrante es esto...$"

Route119_Text_DougIntro:
	.string "¡Sí, por fin me has encontrado! ¿O más\n"
	.string "bien querías evitarme?$"

Route119_Text_DougDefeat:
	.string "¡Guau, qué buen combate!$"

Route119_Text_DougPostBattle:
	.string "¡Somos el círculo de imitadores!\n"
	.string "Espero que hayas disfrutado de nuestra\l"
	.string "actuación.$"

Route119_Text_GregIntro:
	.string "No sabes quién soy, ¿verdad? Pero yo\n"
	.string "tampoco sé quién eres tú y no me\l"
	.string "importa. ¡Te desafío!$"

Route119_Text_GregDefeat:
	.string "¡Eres bastante fuerte!$"

Route119_Text_GregPostBattle:
	.string "Mientras estés aquí, seguiremos\n"
	.string "imitando cada uno de tus movimientos.$"

Route119_Text_KentIntro:
	.string "El círculo de imitadores lo fundó gente\n"
	.string "a la que le gusta imitar a los demás.\l"
	.string "Basta de charlas. ¡A luchar!$"

Route119_Text_KentDefeat:
	.string "¡Me rindo!$"

Route119_Text_KentPostBattle:
	.string "¿No quieres formar parte del círculo\n"
	.string "de imitadores?$"

Route119_Text_JacksonIntro:
	.string "¿Quién tiene el conocimiento y la\n"
	.string "técnica para sobrevivir?\p"
	.string "¡Los Pokéguardas, por supuesto!$"

Route119_Text_JacksonDefeat:
	.string "No tenía suficiente conocimiento\n"
	.string "sobre Pokémon...$"

Route119_Text_JacksonPostBattle:
	.string "Alejarse de la civilización y despertar\n"
	.string "el espíritu salvaje que hay dentro.\l"
	.string "Ésa es nuestra visión.$"

Route119_Text_JacksonRegister:
	.string "Espero que me des una revancha sin\n"
	.string "burlarte de mi falta de conocimiento.$"

Route119_Text_JacksonRematchIntro:
	.string "Voy a despertar mi espíritu salvaje\n"
	.string "gracias a los Pokémon.$"

Route119_Text_JacksonRematchDefeat:
	.string "¡Sigues fuerte como un toro!$"

Route119_Text_JacksonPostRematch:
	.string "Ten confianza en tus Pokémon. Ten\n"
	.string "confianza en ti. Así conseguirás todo\l"
	.string "lo que te propongas.$"

Route119_Text_CatherineIntro:
	.string "Oh, mírate.\p"
	.string "Para alguien que está de viaje, vas\n"
	.string "muy ligero de equipaje.$"

Route119_Text_CatherineDefeat:
	.string "¡Los accidentes ocurren cuando no\n"
	.string "estás preparado!$"

Route119_Text_CatherinePostBattle:
	.string "Vas ligero de equipaje, pero tienes\n"
	.string "todo lo que necesitas.\p"
	.string "Estás bien preparado mental y\n"
	.string "físicamente.$"

Route119_Text_CatherineRegister:
	.string "¿Tienes un PokéNav? Es una herramienta\n"
	.string "imprescindible para cualquier\l"
	.string "entrenador.\p"
	.string "¡Ah, sí que tienes uno!\n"
	.string "¡Registrémonos el uno al otro, entonces!$"

Route119_Text_CatherineRematchIntro:
	.string "¿Qué tal te va en tu viaje con los\n"
	.string "Pokémon?$"

Route119_Text_CatherineRematchDefeat:
	.string "Sigo sin estar preparada... ¿Pero qué\n"
	.string "me falta? ¿Qué?$"

Route119_Text_CatherinePostRematch:
	.string "Del mismo modo que un entrenador confía\n"
	.string "en sus Pokémon, los Pokémon confían en\l"
	.string "su entrenador.$"

Route119_Text_HughIntro:
	.string "¡El cielo infinito encierra todo tipo de\n"
	.string "promesas y sueños! ¡No hay nada más\l"
	.string "hermoso que volar!$"

Route119_Text_HughDefeat:
	.string "He caído en picado...$"

Route119_Text_HughPostBattle:
	.string "¡Gracias a mis Pokémon pájaro, mi sueño\n"
	.string "de surcar los aires es realidad!$"

Route119_Text_PhilIntro:
	.string "¡Te voy a enseñar la fuerza del ataque\n"
	.string "de mi Pokémon pájaro!$"

Route119_Text_PhilDefeat:
	.string "Todavía nos falta un hervor...$"

Route119_Text_PhilPostBattle:
	.string "Desde que era pequeñito, siempre he\n"
	.string "querido tener Pokémon pájaro...$"

Route119_Text_YasuIntro:
	.string "Acechar entre las sombras, vivir en la\n"
	.string "oscuridad... Ése es mi destino...\l"
	.string "¡Y ahora salgo a la luz para retarte!$"

Route119_Text_YasuDefeat:
	.string "¡Acepto mi derrota!$"

Route119_Text_YasuPostBattle:
	.string "Aquellos que pierden un combate han de\n"
	.string "volver silenciosos a las sombras...\l"
	.string "El destino lo quiere así...$"

Route119_Text_TakashiIntro:
	.string "¡Si no estás en guardia, te espera una\n"
	.string "buena tunda!$"

Route119_Text_TakashiDefeat:
	.string "¡Me has dejado patidifuso!$"

Route119_Text_TakashiPostBattle:
	.string "Mi ataque sorpresa ha sido un fiasco...$"

Route119_Text_HideoIntro:
	.string "El mejor lugar para esconder un árbol\n"
	.string "es... ¡un bosque!$"

Route119_Text_HideoDefeat:
	.string "Me inclino ante tu superioridad en\n"
	.string "combate...$"

Route119_Text_HideoPostBattle:
	.string "El mejor lugar para esconder un árbol\n"
	.string "es... ¡un bosque! Y el mejor para\l"
	.string "esconder un Pokémon es... ¡otro\l"
	.string "Pokémon! ¿Tú entiendes lo que acabo de\l"
	.string "decir? ¡Yo tampoco, ja, ja, ja!$"

Route119_Text_ChrisIntro:
	.string "Me has hablado...\n"
	.string "¡Así que quieres luchar contra mí!\p"
	.string "¡Vale! Voy a probar a los Pokémon que\n"
	.string "he pescado mientras hacía SURF.$"

Route119_Text_ChrisDefeat:
	.string "No tengo ni idea de lo que hace falta\n"
	.string "para ganar.$"

Route119_Text_ChrisPostBattle:
	.string "Ir haciendo SURF en mi Pokémon...\p"
	.string "Y luego pescar desde su lomo...\p"
	.string "¡Es un momento de lujo indescriptible!$"

Route119_Text_FabianIntro:
	.string "¡Que suene una música triunfal! ¡La\n"
	.string "victoria es mía! ¡Éste es mi momento\l"
	.string "de gloria!$"

Route119_Text_FabianDefeat:
	.string "Oh, no, ¡ahora ya sé quién manda! No\n"
	.string "soy yo, ¡pondré una demanda!$"

Route119_Text_FabianPostBattle:
	.string "Que suene una música triste... Y\n"
	.string "piérdete de mi vista... ¡Te haré pagar\l"
	.string "por mi derrota!$"

Route119_Text_DaytonIntro:
	.string "¡Jo, jo, jo! ¡Me gusta luchar con las\n"
	.string "nuevas generaciones! ¡Vamos allá!$"

Route119_Text_DaytonDefeat:
	.string "¡Menudos bríos! ¡Jo, jo, jo!$"

Route119_Text_DaytonPostBattle:
	.string "¡Jo, jo, jo! ¡Intentaré poner en\n"
	.string "práctica las nuevas técnicas de lucha!$"

Route119_Text_RachelIntro:
	.string "Mi parasol me acompaña allá donde voy.$"

Route119_Text_RachelDefeat:
	.string "Oh, no... No es justo.$"

Route119_Text_RachelPostBattle:
	.string "¿Dices que mi parasol pesa demasiado?\n"
	.string "Ja, tú sí que tienes la mochila llena de\l"
	.string "tonterías que seguro que no usas.$"

Route120_Text_ColinIntro:
	.string "¿Tienes algún movimiento que pueda\n"
	.string "golpear a un Pokémon volador?$"

Route120_Text_ColinDefeat:
	.string "¡Has volado por encima de mí!$"

Route120_Text_ColinPostBattle:
	.string "El movimiento VUELO es muy útil,\n"
	.string "¿verdad?\p"
	.string "Mientras el Pokémon está volando, casi\n"
	.string "ningún movimiento puede golpearlo.$"

Route120_Text_RobertIntro:
	.string "¡Mi Pokémon es fuerte! ¿Y los tuyos?$"

Route120_Text_RobertDefeat:
	.string "Tus Pokémon son más fuertes...$"

Route120_Text_RobertPostBattle:
	.string "Se puede confiar en los Pokémon que\n"
	.string "crecen de forma continua.$"

Route120_Text_RobertRegister:
	.string "Puedo confiar en que mejorarás.\n"
	.string "Me gustaría registrarte en mi PokéNav.$"

Route120_Text_RobertRematchIntro:
	.string "Se puede confiar en los Pokémon que\n"
	.string "crecen de forma continua.$"

Route120_Text_RobertRematchDefeat:
	.string "Tus Pokémon son seriamente fuertes.$"

Route120_Text_RobertPostRematch:
	.string "Mis Pokémon están creciendo más\n"
	.string "fuertes. Yo también tengo que hacerme\l"
	.string "más fuerte.$"

Route120_Text_LorenzoIntro:
	.string "Voy a comprobar si tus Pokémon están\n"
	.string "en forma para la vida al aire libre.$"

Route120_Text_LorenzoDefeat:
	.string "¡Con Pokémon tan fuertes, no corres\n"
	.string "ningún peligro de necesitar rescate!$"

Route120_Text_LorenzoPostBattle:
	.string "Viajar donde tu corazón desee con tus\n"
	.string "Pokémon... Ésa es la alegría de ser\l"
	.string "entrenador.$"

Route120_Text_JennaIntro:
	.string "¿Cómo está tu forma física? Si no estás\n"
	.string "en forma, podrías tener problemas en\l"
	.string "situaciones críticas.$"

Route120_Text_JennaDefeat:
	.string "Estoy totalmente en forma, pero...$"

Route120_Text_JennaPostBattle:
	.string "El entrenamiento físico es parte de mi\n"
	.string "rutina. Siempre corro con mis Pokémon.$"

Route120_Text_JeffreyIntro:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "¿Quieres luchar?$"

Route120_Text_JeffreyDefeat:
	.string "Perdido...$"

Route120_Text_JeffreyPostBattle:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Lo intentaré más duro...$"

Route120_Text_JeffreyRegister:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "¿Tienes un PokéNav...?$"

Route120_Text_JeffreyRematchIntro:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "¿Quieres luchar otra vez?$"

Route120_Text_JeffreyRematchDefeat:
	.string "... ... ... ... ... ...\n"
	.string "He perdido otra vez...$"

Route120_Text_JeffreyPostRematch:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...\l"
	.string "Lo intentaré más duro...\l"
	.string "Por mis queridos Pokémon de tipo bicho...$"

Route120_Text_JenniferIntro:
	.string "Los Pokémon tienen muchas habilidades\n"
	.string "especiales. Si quieres ser un entrenador\l"
	.string "de primera, aprende sobre ellas.$"

Route120_Text_JenniferDefeat:
	.string "Obviamente estás pensando.$"

Route120_Text_JenniferPostBattle:
	.string "Las habilidades especiales de los\n"
	.string "Pokémon hacen que los estilos de combate\l"
	.string "cambien.$"

Route120_Text_ChipIntro:
	.string "¿Quién eres tú?\p"
	.string "¿Acaso estás buscando ruinas antiguas\n"
	.string "que, según la leyenda, podrían existir?$"

Route120_Text_ChipDefeat:
	.string "Qué revés más vergonzoso...$"

Route120_Text_ChipPostBattle:
	.string "Esa roca gigante... Me gustaría creer\n"
	.string "que podría contener ruinas antiguas.\l"
	.string "Pero no veo ninguna entrada.$"

Route120_Text_ClarissaIntro:
	.string "¿Por qué llevo este parasol?\n"
	.string "Te lo diré si me vences.$"

Route120_Text_ClarissaDefeat:
	.string "Un parasol no puede parar los ataques\n"
	.string "Pokémon...$"

Route120_Text_ClarissaPostBattle:
	.string "No creo que este sol tan fuerte sea bueno\n"
	.string "para mis Pokémon... Por eso los cubro\l"
	.string "con este parasol.$"

Route120_Text_AngelicaIntro:
	.string "Yo, mis Pokémon y mi parasol...\p"
	.string "Si falta alguno de ellos, el cuadro de\n"
	.string "la belleza se arruinaría.$"

Route120_Text_AngelicaDefeat:
	.string "Has arruinado completamente mi belleza...$"

Route120_Text_AngelicaPostBattle:
	.string "Un parasol no te quedaría nada bien.\p"
	.string "Algo como esto solo te estorbaría.$"

Route120_Text_KeigoIntro:
	.string "Voy a adoptar los movimientos de los\n"
	.string "Pokémon para crear nuevas técnicas\l"
	.string "ninja.$"

Route120_Text_KeigoDefeat:
	.string "La creación de nuevas técnicas ninja\n"
	.string "sigue siendo un sueño lejano...$"

Route120_Text_KeigoPostBattle:
	.string "Quizá debería aprender de un maestro\n"
	.string "ninja.$"

Route120_Text_RileyIntro:
	.string "Los ninja nos ocultamos bajo nuestras\n"
	.string "capas de camuflaje.\l"
	.string "¡Apuesto a que no sabías dónde estaba!$"

Route120_Text_RileyDefeat:
	.string "¡He perdido!\n"
	.string "¡Debería camuflar mi vergüenza!$"

Route120_Text_RileyPostBattle:
	.string "Nuestras capas de camuflaje están\n"
	.string "hechas a mano.$"

Route120_Text_CallieIntro:
	.string "¡Si no prestas atención, podrías\n"
	.string "hacerte daño!$"

Route120_Text_CallieDefeat:
	.string "¡Ay!\n"
	.string "¡Soy yo la que se ha hecho daño!$"

Route120_Text_CalliePostBattle:
	.string "Me pregunto... ¿Debería hacer evolucionar\n"
	.string "a mis Pokémon? Son monos tal como están.$"

Route120_Text_LeonelIntro:
	.string "¿Los Pokémon de tu equipo...\n"
	.string "Son de diferentes tipos?$"

Route120_Text_LeonelDefeat:
	.string "¡He visto tu política en acción!$"

Route120_Text_LeonelPostBattle:
	.string "Creo que es genial que seas tan fuerte\n"
	.string "luchando con tus Pokémon favoritos.$"

Route121_Text_VanessaIntro:
	.string "¿Jugarías con mi precioso y adorable\n"
	.string "Pokémon?$"

Route121_Text_VanessaDefeat:
	.string "¡Esto no es lo que quería!$"

Route121_Text_VanessaPostBattle:
	.string "Voy a un concurso en Ciudad Calagua.\p"
	.string "Mis Pokémon no deberían tener problemas\n"
	.string "para arrasar en la categoría Maestro.$"

Route121_Text_WalterIntro:
	.string "Con mis Pokémon, he viajado a los\n"
	.string "cuatro rincones del mundo.\p"
	.string "Podría decirse que tengo cierta\n"
	.string "confianza en mis habilidades.$"

Route121_Text_WalterDefeat:
	.string "Ah, bien jugado.$"

Route121_Text_WalterPostBattle:
	.string "Me gustaría dar la vuelta al mundo una\n"
	.string "vez más con mis Pokémon.$"

Route121_Text_WalterRegister:
	.string "Tu habilidad con los Pokémon es\n"
	.string "notable. Permíteme registrarte como\l"
	.string "recuerdo.$"

Route121_Text_WalterRematchIntro:
	.string "Con mis Pokémon, he viajado a los\n"
	.string "cuatro rincones del mundo.\p"
	.string "Podría decirse que tengo cierta\n"
	.string "confianza en mis habilidades.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, bien jugado.$"

Route121_Text_WalterPostRematch:
	.string "Tus Pokémon y tú...\p"
	.string "Vuestra habilidad conjunta será\n"
	.string "considerada fuerte, incluso en el\l"
	.string "extranjero.$"

Route121_Text_TammyIntro:
	.string "Hay poderes más allá de nuestra\n"
	.string "comprensión en el mundo...$"

Route121_Text_TammyDefeat:
	.string "He perdido...$"

Route121_Text_TammyPostBattle:
	.string "Monte Pírico...\n"
	.string "Hay un poder misterioso en\l"
	.string "acción allí...$"

Route121_Text_KateIntro:
	.string "KATE: Juntas, ¡no tenemos miedo de nada!\n"
	.string "¡Te demostraremos lo duras que somos!$"

Route121_Text_KateDefeat:
	.string "KATE: La he cagado delante de mi\n"
	.string "compañera novata...$"

Route121_Text_KatePostBattle:
	.string "KATE: Cuando alguien confía en mí, me\n"
	.string "entran ganas de quedar bien delante\l"
	.string "de ella...$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: Si solo tienes un Pokémon, no\n"
	.string "podemos luchar contigo.\p"
	.string "Eso sería intimidación.$"

Route121_Text_JoyIntro:
	.string "JOY: Juntas, ¡no tenemos miedo de nada!\n"
	.string "¡Te demostraremos lo duras que somos!$"

Route121_Text_JoyDefeat:
	.string "JOY: ¡Por favor, perdóname, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Je, je, tendré que entrenar con\n"
	.string "KATE, mi compañera novata, otra vez.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: Necesitas al menos dos Pokémon si\n"
	.string "vas a desafiarnos.$"

Route121_Text_JessicaIntro:
	.string "¡Alto! ¡Mira bien mis preciosos\n"
	.string "Pokémon!$"

Route121_Text_JessicaDefeat:
	.string "¡Oh, cómo te atreves!\n"
	.string "¡No te lo tomes tan en serio!$"

Route121_Text_JessicaPostBattle:
	.string "Quizá vaya a atrapar más Pokémon a la\n"
	.string "Zona Safari.$"

Route121_Text_JessicaRegister:
	.string "¡Esta vez te lo he puesto fácil!\n"
	.string "¡La próxima vez no será así!$"

Route121_Text_JessicaRematchIntro:
	.string "¡Mis preciosos Pokémon han crecido!\n"
	.string "¡Míralos bien!$"

Route121_Text_JessicaRematchDefeat:
	.string "¡Oh, cómo te atreves!\n"
	.string "¡Todavía no te lo tomas en serio!$"

Route121_Text_JessicaPostRematch:
	.string "Quizá vaya a atrapar más Pokémon a la\n"
	.string "Zona Safari.$"

Route121_Text_CristinIntro:
	.string "Tengo una rutina.\n"
	.string "Derrotar a cinco entrenadores al día.\l"
	.string "¡Adivina qué! ¡Eres el número cinco!$"

Route121_Text_CristinDefeat:
	.string "¡No!\n"
	.string "¡Eres horrible!$"

Route121_Text_CristinPostBattle:
	.string "No esperaba perder tan fácilmente...\n"
	.string "¡Ganaré la próxima vez!$"

Route121_Text_CristinRegister:
	.string "¡Eso ha sido una humillación total!\n"
	.string "No te olvidaré...\l"
	.string "¡Dame tu PokéNav!$"

Route121_Text_CristinRematchIntro:
	.string "Tengo una nueva rutina.\n"
	.string "Derrotar a diez entrenadores al día.\l"
	.string "¡Adivina qué! ¡Eres el número diez!$"

Route121_Text_CristinRematchDefeat:
	.string "¡Espera! ¡Eso es horrible!\n"
	.string "¡Exijo una revancha!$"

Route121_Text_CristinPostRematch:
	.string "Un oponente que simplemente no puedo\n"
	.string "vencer... Bua...\l"
	.string "No puedo creer que esto esté pasando...$"

Route121_Text_CaleIntro:
	.string "¿No ves que llevo todo esto?\p"
	.string "¿A pesar de eso, aún insistes en que\n"
	.string "luchemos?$"

Route121_Text_CaleDefeat:
	.string "¡Por supuesto que he perdido!\n"
	.string "¡Llevo cosas en ambas manos!$"

Route121_Text_CalePostBattle:
	.string "He comprado demasiadas cosas en el\n"
	.string "Centro Comercial de Ciudad Calagua.\p"
	.string "Está justo por aquí.\n"
	.string "Ojalá tuviera una MOCHILA como la tuya.$"

Route121_Text_MylesIntro:
	.string "No hay nada que me guste más que\n"
	.string "mirar los Pokémon de los demás.$"

Route121_Text_MylesDefeat:
	.string "¡Superguay!$"

Route121_Text_MylesPostBattle:
	.string "¡Son geniales, tus Pokémon!\n"
	.string "¿Cómo los entrenas?$"

Route121_Text_PatIntro:
	.string "¡Quiero que todo el mundo vea los\n"
	.string "Pokémon que he criado!$"

Route121_Text_PatDefeat:
	.string "¡Guau!\n"
	.string "¡Espectacular!$"

Route121_Text_PatPostBattle:
	.string "Crió cada Pokémon con el mismo amor y\n"
	.string "cuidado. No tengo favoritos.$"

Route121_Text_MarcelIntro:
	.string "¡Mis Pokémon nunca han sabido lo que es\n"
	.string "perder!\p"
	.string "¡En su próxima victoria, los inscribiré\n"
	.string "en concursos!$"

Route121_Text_MarcelDefeat:
	.string "Oh, ¿qué ha pasado aquí?$"

Route121_Text_MarcelPostBattle:
	.string "Quizá deba entrenar a mi pandilla un\n"
	.string "poco más antes de inscribirme en\l"
	.string "ningún concurso.$"

Route123_Text_WendyIntro:
	.string "¿Quieres saber lo fuerte que eres?\n"
	.string "¡Yo seré tu prueba!$"

Route123_Text_WendyDefeat:
	.string "¡Has superado la prueba con nota!$"

Route123_Text_WendyPostBattle:
	.string "Si eres capaz de vencerme...\n"
	.string "¡Tu fuerza es asombrosa!$"

Route123_Text_BraxtonIntro:
	.string "Parece que tienes un montón de medallas\n"
	.string "de gimnasio.\p"
	.string "¡Déjame ver si realmente te las\n"
	.string "mereces!$"

Route123_Text_BraxtonDefeat:
	.string "¡Oh, claro que te las mereces!$"

Route123_Text_BraxtonPostBattle:
	.string "¡Has hecho honor a tus medallas en ese\n"
	.string "combate!$"

Route123_Text_VioletIntro:
	.string "Dicen que los buenos momentos están\n"
	.string "llenos de buenos aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh...\n"
	.string "Huelo el amargo aroma de la derrota...$"

Route123_Text_VioletPostBattle:
	.string "El jardín del Bayólogo está lleno de\n"
	.string "fragancias reconfortantes.$"

Route123_Text_CameronIntro:
	.string "Ser un médium es cuestión de voluntad.\p"
	.string "Me he convencido a mí mismo de no perder\n"
	.string "contra nadie. ¡Eso me hace fuerte!$"

Route123_Text_CameronDefeat:
	.string "Me siento triste...$"

Route123_Text_CameronPostBattle:
	.string "Ser un médium es cuestión de voluntad.\n"
	.string "Pensé que no perdería contra ti...$"

Route123_Text_CameronRegister:
	.string "¡Lo presiento! ¡Tú y yo volveremos a\n"
	.string "luchar!\p"
	.string "Aunque no sé si ganaré...\n"
	.string "Déjame ver tu PokéNav.$"

Route123_Text_CameronRematchIntro:
	.string "Me he convencido a mí mismo de que no\n"
	.string "voy a perder más. ¡Eso me hace fuerte!$"

Route123_Text_CameronRematchDefeat:
	.string "Me siento triste...$"

Route123_Text_CameronPostRematch:
	.string "Debería entrenar en el Monte Pírico...\n"
	.string "Así nunca te venceré...$"

Route123_Text_JackiIntro:
	.string "No te alegres demasiado si tus Pokémon\n"
	.string "desarrollan poderes psíquicos.\p"
	.string "Necesitas refinar esos poderes para\n"
	.string "hacerlos realmente útiles.$"

Route123_Text_JackiDefeat:
	.string "¡Aplastado!$"

Route123_Text_JackiPostBattle:
	.string "Todos tenemos poderes psíquicos.\n"
	.string "Sólo hemos olvidado cómo usarlos.$"

Route123_Text_JackiRegister:
	.string "Me gustaría enfrentarme a ti otra vez.\n"
	.string "¿Te parece bien?$"

Route123_Text_JackiRematchIntro:
	.string "¿Has despertado los poderes psíquicos\n"
	.string "que hay dentro de ti?$"

Route123_Text_JackiRematchDefeat:
	.string "¡Asombroso!$"

Route123_Text_JackiPostRematch:
	.string "Tu poder con los Pokémon...\n"
	.string "Eso también podría ser un poder psíquico.$"

Route123_Text_MiuIntro:
	.string "MIU: Hola, entrenador. Espero que tus\n"
	.string "Pokémon no lloren cuando pierdan.$"

Route123_Text_MiuDefeat:
	.string "MIU: Oh, hemos perdido.$"

Route123_Text_MiuPostBattle:
	.string "MIU: Entrenador, tus Pokémon son\n"
	.string "fuertes porque sois amigos.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: No es divertido luchar si no tienes\n"
	.string "dos Pokémon.$"

Route123_Text_YukiIntro:
	.string "YUKI: ¡Vale!\n"
	.string "¡Vamos a ganar al entrenador!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Oh, hemos perdido.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: ¿Por qué eres tan fuerte?\n"
	.string "Nunca habíamos perdido antes.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: No es divertido luchar si no tienes\n"
	.string "dos Pokémon.$"

Route123_Text_KindraIntro:
	.string "Monte Pírico...\n"
	.string "Donde duermen los espíritus de los\l"
	.string "Pokémon...\n"
	.string "¿Tus Pokémon dormirán?$"

Route123_Text_KindraDefeat:
	.string "Desbordante de vitalidad...$"

Route123_Text_KindraPostBattle:
	.string "Monte Pírico...\n"
	.string "Donde duermen los espíritus de los\l"
	.string "Pokémon...\p"
	.string "Debe desbordar un poder que calma\n"
	.string "los espíritus...$"

Route123_Text_FernandoIntro:
	.string "¡Voy a apagar tus luces mientras rasgueo\n"
	.string "esta canción!$"

Route123_Text_FernandoDefeat:
	.string "¡Eh, espera!\n"
	.string "¡Todavía estaba tocando la intro!$"

Route123_Text_FernandoPostBattle:
	.string "Eres una roca sólida.\n"
	.string "Me gustaría escribir una canción sobre\l"
	.string "ti.$"

Route123_Text_FernandoRegister:
	.string "La próxima vez, préstame tus oídos\n"
	.string "para escuchar la canción completa, ¿vale?$"

Route123_Text_FernandoRematchIntro:
	.string "¡Hoy es el día! ¡Voy a apagar tus luces\n"
	.string "antes de terminar mi canción!$"

Route123_Text_FernandoRematchDefeat:
	.string "¡Eh, espera!\n"
	.string "¡Ni siquiera he llegado al estribillo!$"

Route123_Text_FernandoPostRematch:
	.string "Pensaba que estarías tan embelesado por\n"
	.string "mi canción que perderías.$"

Route123_Text_DavisIntro:
	.string "¡Este es mi increíble Pokémon de tipo\n"
	.string "bicho! Mi hermano mayor me lo regaló.$"

Route123_Text_DavisDefeat:
	.string "¡Buaaaaa!\n"
	.string "¡Eres un malvado!$"

Route123_Text_DavisPostBattle:
	.string "No le cuentes a mi hermano que he\n"
	.string "perdido. ¡Tienes que guardar el secreto!$"

Route123_Text_JazmynIntro:
	.string "Mi confianza aumentará si le gano a\n"
	.string "alguien obviamente fuerte como tú!$"

Route123_Text_JazmynDefeat:
	.string "Ahí va mi confianza...$"

Route123_Text_JazmynPostBattle:
	.string "Dicen que no se puede juzgar a una\n"
	.string "persona por su apariencia.\p"
	.string "Pero a menudo, las apariencias no\n"
	.string "mienten...$"

Route123_Text_FrederickIntro:
	.string "¡Hola, niño!\n"
	.string "¿Tienes un momento?$"

Route123_Text_FrederickDefeat:
	.string "¡Ah, un niño muy capaz!\n"
	.string "Déjame contribuir a tu paga.$"

Route123_Text_FrederickPostBattle:
	.string "¿Contribuir a tu paga?\n"
	.string "¿No te ha dado bastante el dinero del\l"
	.string "combate?$"

Route123_Text_AlbertoIntro:
	.string "Debo decirte que los Pokémon pájaro son\n"
	.string "mi obsesión.\p"
	.string "¡Los pájaros molan!\n"
	.string "¡Son lo mejor!$"

Route123_Text_AlbertoDefeat:
	.string "¡Incluso en la derrota, los Pokémon\n"
	.string "pájaro molan!$"

Route123_Text_AlbertoPostBattle:
	.string "Recojo plumas de Pokémon pájaro que\n"
	.string "se esparcen durante los combates.\p"
	.string "Voy a hacer un sombrero con plumas de\n"
	.string "Pokémon pájaro.$"

Route123_Text_EdIntro:
	.string "Cuando no hay entrenadores cerca, dejo\n"
	.string "que mis Pokémon luchen entre ellos.\l"
	.string "Los observo.$"

Route123_Text_EdDefeat:
	.string "Me gustan tus Pokémon.$"

Route123_Text_EdPostBattle:
	.string "Je, je, estoy robando tus tácticas de\n"
	.string "combate. Creo que me harán mejorar.$"

Route123_Text_JonasIntro:
	.string "¡He tendido una emboscada y un entrenador\n"
	.string "ha caído en mi trampa!$"

Route123_Text_JonasDefeat:
	.string "Si no pierdes, ¿cómo se supone que voy\n"
	.string "a divertirme jugando a ser ninja?$"

Route123_Text_JonasPostBattle:
	.string "Voy a tender una emboscada a un\n"
	.string "entrenador que parezca más débil la\l"
	.string "próxima vez.$"

Route123_Text_KayleyIntro:
	.string "Acabo de comprar este parasol.\n"
	.string "¡Mi encanto debería aumentar un tercio!$"

Route123_Text_KayleyDefeat:
	.string "Eres mejor que yo por un factor de\n"
	.string "cinco.$"

Route123_Text_KayleyPostBattle:
	.string "Usar accesorios de forma efectiva es el\n"
	.string "secreto del atractivo de la moda.$"

Route124_Text_SpencerIntro:
	.string "Oye, ¿te has perdido en el mar?\p"
	.string "Si puedes vencer a mis Pokémon, puedo\n"
	.string "servirte de guía.$"

Route124_Text_SpencerDefeat:
	.string "¡He perdido el norte en el combate!$"

Route124_Text_SpencerPostBattle:
	.string "Mucha gente se pierde en el mar.\p"
	.string "Si eres de esos, deberías consultar el\n"
	.string "mapa del PokéNav.$"

Route124_Text_RolandIntro:
	.string "¡Anda! ¡Montas un Pokémon, así que no\n"
	.string "tienes que nadar! ¡Qué envidia!$"

Route124_Text_RolandDefeat:
	.string "Oh...\n"
	.string "No puedo...$"

Route124_Text_RolandPostBattle:
	.string "Me estoy quedando arrugado... Llevo\n"
	.string "demasiado tiempo en el agua...\p"
	.string "Si pudiera montar un Pokémon como tú...$"

Route124_Text_JennyIntro:
	.string "Si te quedas flotando en el mar así, los\n"
	.string "Pokémon vienen a jugar contigo.$"

Route124_Text_JennyDefeat:
	.string "Oh... Perdida en el mar...$"

Route124_Text_JennyPostBattle:
	.string "Nadando, nadando, me he dado cuenta de\n"
	.string "que hay Pokémon que atacan, mientras que\l"
	.string "otros sólo miran... Se ve que cada\l"
	.string "Pokémon tiene una personalidad diferente.$"

Route124_Text_JennyRegister:
	.string "Tengo un capricho: quiero que me\n"
	.string "registres en tu PokéNav.$"

Route124_Text_JennyRematchIntro:
	.string "Si te quedas flotando en el mar así, ¡los\n"
	.string "entrenadores te desafían!$"

Route124_Text_JennyRematchDefeat:
	.string "Esto es rarísimo... He vuelto a perder...$"

Route124_Text_JennyPostRematch:
	.string "No es que tenga nada que ver, pero creo\n"
	.string "que voy a ir a la Casa Treta.$"

Route124_Text_GraceIntro:
	.string "Estoy harta de nadar. ¿Y si luchamos un\n"
	.string "rato?$"

Route124_Text_GraceDefeat:
	.string "¡Si hubiera sabido que eras tan fuerte,\n"
	.string "no habría dicho nada!$"

Route124_Text_GracePostBattle:
	.string "Te esfuerzas tanto que ésa debe de ser\n"
	.string "la razón de que seas tan fuerte.$"

Route124_Text_ChadIntro:
	.string "Ja, ja, ja... Buceo hasta el fondo para\n"
	.string "que nadie me vea. ¡Soy un as del buceo!$"

Route124_Text_ChadDefeat:
	.string "Glu, glu, glu... Me hundo...$"

Route124_Text_ChadPostBattle:
	.string "Sé de buena tinta que hay un lugar donde\n"
	.string "hacer buceo por aquí. Me están entrando\l"
	.string "ganas de ir allí...$"

Route124_Text_LilaIntro:
	.string "RITA: Ay... Aquí estoy, en medio del mar,\n"
	.string "¿y con quién? ¡Con el enano de mi\l"
	.string "hermano! ¡Estoy tan estresada que tengo\l"
	.string "que combatir con alguien!$"

Route124_Text_LilaDefeat:
	.string "RITA: ¡SAÚL! ¡Que hayamos perdido es\n"
	.string "culpa tuya! ¡Ya verás luego!$"

Route124_Text_LilaPostBattle:
	.string "RITA: Ay... Si en vez de estar con mi\n"
	.string "hermano, estuviera con mis colegas...$"

Route124_Text_LilaNotEnoughMons:
	.string "RITA: ¿Piensas luchar con nosotros?\n"
	.string "No, si no tienes dos Pokémon.$"

Route124_Text_RoyIntro:
	.string "SAÚL: Mi hermana mayor es la reina de\n"
	.string "los Pokémon. ¡Ahora verás!$"

Route124_Text_RoyDefeat:
	.string "SAÚL: Ay, ay, ay... Mi hermana dirá que\n"
	.string "es culpa mía...$"

Route124_Text_RoyPostBattle:
	.string "SAÚL: Mi hermana es un poco abusona y da\n"
	.string "miedo cuando se enfada. Ojalá estuviera\l"
	.string "con mis amigos...$"

Route124_Text_LilaRoyRegister:
	.string "SAÚL: ¡Vuelve a luchar con nosotros!\n"
	.string "¡Pero ponnos las cosas más fáciles!$"

Route124_Text_RoyNotEnoughMons:
	.string "SAÚL: ¿Quieres luchar con nosotros?\n"
	.string "Trae dos Pokémon, entonces.$"

Route124_Text_LilaRematchIntro:
	.string "RITA: Ay... Aquí estoy, en medio del mar,\n"
	.string "¿y con quién? ¡Con el enano de mi\l"
	.string "hermano! ¡Ah, hola! Mira, estoy tan\l"
	.string "estresada que tengo que luchar con\l"
	.string "alguien...$"

Route124_Text_LilaRematchDefeat:
	.string "RITA: ¡SAÚL! ¡Hemos vuelto a perder por\n"
	.string "tu culpa! ¡Luego vas a tener una buena\l"
	.string "sesión de entrenamiento, a ver si\l"
	.string "aprendes!$"

Route124_Text_LilaPostRematch:
	.string "RITA: Ay... Si estuviera con mis colegas,\n"
	.string "no habría rival que se resistiera...$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "RITA: ¿Piensas luchar con nosotros?\n"
	.string "No, si no tienes dos Pokémon.$"

Route124_Text_RoyRematchIntro:
	.string "SAÚL: Si perdemos, me cae una gorda...\n"
	.string "¡Voy a poner toda la carne en el asador!$"

Route124_Text_RoyRematchDefeat:
	.string "SAÚL: Ay, ay, ay... Mi hermana dirá que\n"
	.string "es culpa mía...$"

Route124_Text_RoyPostRematch:
	.string "SAÚL: Mi hermana es un poco abusona y da\n"
	.string "miedo cuando se enfada. Seguro que me\l"
	.string "obliga a entrenar como un burro con los\l"
	.string "Pokémon luego...$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "SAÚL: ¿Quieres luchar con nosotros?\n"
	.string "Trae dos Pokémon, entonces.$"

Route124_Text_DeclanIntro:
	.string "Aquí estoy, nadando más solo que la una\n"
	.string "en este vasto y hermoso mar. No hay otro\l"
	.string "modo de describirlo... ¡Es para echarse\l"
	.string "a llorar!$"

Route124_Text_DeclanDefeat:
	.string "Qué depre tengo... Más vasta que el vasto\n"
	.string "mar...$"

Route124_Text_DeclanPostBattle:
	.string "Voy a buscar a alguna nadadora que quiera\n"
	.string "flotar un rato conmigo.$"

Route124_Text_IsabellaIntro:
	.string "Los surfistas me rebotan. ¡No pienso\n"
	.string "dejarte ganar!$"

Route124_Text_IsabellaDefeat:
	.string "¡Que no! ¡Que no estoy llorando! ¡Es que\n"
	.string "me has salpicado!$"

Route124_Text_IsabellaPostBattle:
	.string "Por aquí se encuentran trozos de cosas\n"
	.string "de todos los colores.$"

Route125_Text_NolenIntro:
	.string "Te estaba esperando... ¡Voy a por ti!$"

Route125_Text_NolenDefeat:
	.string "¡Piedaaad!$"

Route125_Text_NolenPostBattle:
	.string "El sonido viaja más rápido en el agua que\n"
	.string "en el aire. Interesante, ¿eh?$"

Route125_Text_StanIntro:
	.string "¡Hola, hola! ¡Mira qué Pokémon tan chulo\n"
	.string "tengo!$"

Route125_Text_StanDefeat:
	.string "No he luchado con ganas...$"

Route125_Text_StanPostBattle:
	.string "Me dejé engatusar por el encanto de\n"
	.string "Horsea, por eso empecé a nadar.$"

Route125_Text_TanyaIntro:
	.string "Estoy hasta las narices de nadar. ¿Te\n"
	.string "apetece luchar contra mí?$"

Route125_Text_TanyaDefeat:
	.string "¡Eres impresionante!$"

Route125_Text_TanyaPostBattle:
	.string "Da igual... ¿Cómo se llega hasta\n"
	.string "Ciudad Algaria?$"

Route125_Text_SharonIntro:
	.string "¿Estás de humor para enfrentarte a mis\n"
	.string "Pokémon de tipo Agua?$"

Route125_Text_SharonDefeat:
	.string "He perdido...$"

Route125_Text_SharonPostBattle:
	.string "Qué fuerza... No he visto nada igual...\n"
	.string "¡Estoy impresionada!$"

Route125_Text_ErnestIntro:
	.string "¡Ah del barco! Soy un Marinero muy\n"
	.string "curtido. ¡Un lobo de mar!$"

Route125_Text_ErnestDefeat:
	.string "¡Grrr! ¡No he logrado derrotarte!$"

Route125_Text_ErnestPostBattle:
	.string "La marea sube y baja en el interior de\n"
	.string "la Cueva Cardumen.\p"
	.string "Ah, ¿sabías que hay seis horas de\n"
	.string "diferencia entre la marea alta y la baja?$"

Route125_Text_ErnestRegister:
	.string "Regístrame en tu PokéNav y te contaré\n"
	.string "algo interesante.$"

Route125_Text_ErnestRematchIntro:
	.string "¡Es hora de que me des una revancha!\n"
	.string "¡Vamos, lucha conmigo!$"

Route125_Text_ErnestRematchDefeat:
	.string "¡No he podido ganar!\n"
	.string "¡No he podido ganar de ninguna manera!$"

Route125_Text_ErnestRematchPostBattle:
	.string "La Cueva Cardumen...\p"
	.string "Hay lugares a los que puedes y no puedes\n"
	.string "acceder dependiendo de la marea.\p"
	.string "Ah, ¿sabías que hay seis horas de\n"
	.string "diferencia entre la marea alta y la baja?\l"
	.string "¡No lo olvides!$"

Route125_Text_KimIntro:
	.string "BETH: He oído que en la Cueva Cardumen\n"
	.string "hay un anciano un poco rarito. ¿Tú\l"
	.string "también vas a ir a verlo?$"

Route125_Text_KimDefeat:
	.string "BETH: Y eso que parecía tener la victoria\n"
	.string "en el bolsillo.$"

Route125_Text_KimPostBattle:
	.string "BETH: En la Cueva Cardumen hay un anciano\n"
	.string "rarito, ¿no? ¿Pues a qué esperamos? ¡Vamos\l"
	.string "a verlo!$"

Route125_Text_KimNotEnoughMons:
	.string "BETH: No, no, no. Necesitas dos Pokémon,\n"
	.string "si no, no hay combate.$"

Route125_Text_IrisIntro:
	.string "ISIS: ¿Pero qué habrá en ese sitio?$"

Route125_Text_IrisDefeat:
	.string "ISIS: Estuvimos a puntito a puntito.$"

Route125_Text_IrisPostBattle:
	.string "ISIS: ¿De verdad que quieres entrar en\n"
	.string "la Cueva Cardumen? ¡Nos vamos a calar\l"
	.string "hasta los huesos!$"

Route125_Text_IrisNotEnoughMons:
	.string "ISIS: Oh, nunca haríamos nada como un\n"
	.string "combate 2 contra 1.$"

Route125_Text_PresleyIntro:
	.string "¿Qué hace un ornitólogo como yo con el\n"
	.string "agua hasta el cuello?$"

Route125_Text_PresleyDefeat:
	.string "Vale, te voy a decir qué hago aquí.$"

Route125_Text_PresleyPostBattle:
	.string "Voy a meter un mensaje en una botella\n"
	.string "para que se la lleve el mar. ¡Seguro que\l"
	.string "la encuentra una nadadora!$"

Route125_Text_AuronIntro:
	.string "¡Oye! ¿Estabas tirando basura al mar?$"

Route125_Text_AuronDefeat:
	.string "Ah, no, tú eres una persona la mar de\n"
	.string "limpia.$"

Route125_Text_AuronPostBattle:
	.string "Antes he visto una botella asquerosa entre\n"
	.string "las olas. ¡Me pone de malas pulgas la\l"
	.string "gente que contamina el mar!$"

Route126_Text_BarryIntro:
	.string "¡Nadar es un ejercicio para todo el\n"
	.string "cuerpo! ¡Te pondrás en forma!$"

Route126_Text_BarryDefeat:
	.string "¡Lo reconozco! ¡Tú ganas!$"

Route126_Text_BarryPostBattle:
	.string "Gracias a mi rutina diaria de natación...\n"
	.string "¡Mira! ¡Contempla este cuerpo esculpido!$"

Route126_Text_DeanIntro:
	.string "Esta enorme montaña blanca de roca es\n"
	.string "Ciudad Algaria.$"

Route126_Text_DeanDefeat:
	.string "¿Me ha ganado?$"

Route126_Text_DeanPostBattle:
	.string "No encuentro la entrada a Ciudad\n"
	.string "Algaria. ¿Dónde estará?$"

Route126_Text_NikkiIntro:
	.string "¡Jua, jua, jua, jua! ¡Soy una sirena!$"

Route126_Text_NikkiDefeat:
	.string "¡Mi fantasía ha explotado como una\n"
	.string "burbuja! ¡Blub, blub, blub...!$"

Route126_Text_NikkiPostBattle:
	.string "Me has dado una paliza... Quiero\n"
	.string "desaparecer entre las olas de la\l"
	.string "desesperación...$"

Route126_Text_BrendaIntro:
	.string "¡Hola, peque! ¿Quieres luchar conmigo?$"

Route126_Text_BrendaDefeat:
	.string "¡Oh, noooooh!$"

Route126_Text_BrendaPostBattle:
	.string "¡Me encanta jugar con mis Pokémon en el\n"
	.string "mar así!$"

Route126_Text_PabloIntro:
	.string "¡Mira este cuerpo esculpido! ¡Estoy más\n"
	.string "cachas que un cinturón negro!$"

Route126_Text_PabloDefeat:
	.string "¡Vaya! ¡Demasiado fuerte! ¡No está mal,\n"
	.string "no está mal en absoluto!$"

Route126_Text_PabloPostBattle:
	.string "Perder contra ti me ha estimulado los\n"
	.string "sentidos. ¡Voy a entrenarme más a mí\l"
	.string "mismo y a mis Pokémon!$"

Route126_Text_PabloRegister:
	.string "Sí, no está mal en absoluto. ¡Me gustaría\n"
	.string "conocerte mejor!$"

Route126_Text_PabloRematchIntro:
	.string "¡Mira este cuerpo esculpido! ¡Estoy más\n"
	.string "cachas que un nadador!$"

Route126_Text_PabloRematchDefeat:
	.string "¡Vaya! ¡Realmente demasiado fuerte! ¡No\n"
	.string "está mal, no está mal en absoluto!$"

Route126_Text_PabloPostRematch:
	.string "¡Voy a entrenar aún más duro! ¡Eres un\n"
	.string "gran motivador! ¡Tienes que volver!$"

Route126_Text_LeonardoIntro:
	.string "El año pasado ni siquiera sabía nadar,\n"
	.string "pero ahora soy un nadador decente.\p"
	.string "Creo que soy capaz de cualquier cosa\n"
	.string "ahora.$"

Route126_Text_LeonardoDefeat:
	.string "Vaya, ser ambicioso no me ha servido de\n"
	.string "nada.$"

Route126_Text_LeonardoPostBattle:
	.string "Si practicas algo, mejorarás en ello.\n"
	.string "Eres joven, ¡no tengas miedo de probar\l"
	.string "todo tipo de cosas!$"

Route126_Text_IsobelIntro:
	.string "Cuando te entra agua de mar en la nariz,\n"
	.string "¿no es horrible?$"

Route126_Text_IsobelDefeat:
	.string "¡Agh! ¿Por qué tú...?\n"
	.string "¡Glu!$"

Route126_Text_IsobelPostBattle:
	.string "¡Ooh, me he tragado agua! ¡Es amarga!\n"
	.string "¡Es salada!!$"

Route126_Text_SiennaIntro:
	.string "¡Voy a poner todo mi corazón en esto!$"

Route126_Text_SiennaDefeat:
	.string "¡Tú tenías más corazón!$"

Route126_Text_SiennaPostBattle:
	.string "Necesito refrescarme... Creo que voy a\n"
	.string "bucear un poco.$"

Route127_Text_CamdenIntro:
	.string "Te lo veo en la cara. Quieres luchar\n"
	.string "conmigo, ¿verdad?$"

Route127_Text_CamdenDefeat:
	.string "Aaaaaaaaah...$"

Route127_Text_CamdenPostBattle:
	.string "Un combate bien jugado me deja\n"
	.string "refrescado y sereno.$"

Route127_Text_DonnyIntro:
	.string "¿Tienes algún rival al que odies perder?$"

Route127_Text_DonnyDefeat:
	.string "¡Aaaargh! ¡Odio perder!$"

Route127_Text_DonnyPostBattle:
	.string "Si tienes un rival, ¿no sientes que\n"
	.string "tienes que seguir mejorando?$"

Route127_Text_JonahIntro:
	.string "Gracias a la pesca, he alcanzado un\n"
	.string "estado de serenidad absoluta...\p"
	.string "Por favor, permíteme demostrártelo...$"

Route127_Text_JonahDefeat:
	.string "Aunque he perdido, mi corazón sigue\n"
	.string "en calma...$"

Route127_Text_JonahPostBattle:
	.string "Me da igual si no pesco nada. La línea\n"
	.string "sigue en el agua...$"

Route127_Text_HenryIntro:
	.string "¡Vaya! ¿No me digas que he enganchado\n"
	.string "un Pokémon haciendo SURF?$"

Route127_Text_HenryDefeat:
	.string "¡No puedo seguir el ritmo!$"

Route127_Text_HenryPostBattle:
	.string "Sería un lío si enganchara a un Pokémon\n"
	.string "tan fuerte como el tuyo.$"

Route127_Text_RogerIntro:
	.string "¡Bueno, bueno! ¡Este es un combate entre\n"
	.string "un fanático de los Pokémon y un\l"
	.string "apasionado de la pesca!$"

Route127_Text_RogerDefeat:
	.string "¡No! ¡Mi sedal está enredado!\n"
	.string "¡Se acabó la fiesta!$"

Route127_Text_RogerPostBattle:
	.string "¡Mi sedal de pesca está bailando la\n"
	.string "tarantela! ¡Ja, ja, ja, enredado!$"

Route127_Text_AidanIntro:
	.string "Los Pokémon pájaro tienen una visión\n"
	.string "excelente. Detectan a su presa desde\l"
	.string "gran altura.$"

Route127_Text_AidanDefeat:
	.string "Uf... Me rindo.$"

Route127_Text_AidanPostBattle:
	.string "Hay muchos lugares para bucear en el mar\n"
	.string "de por aquí.\p"
	.string "Puedes verlos fácilmente desde el cielo\n"
	.string "por su color más oscuro.$"

Route127_Text_KojiIntro:
	.string "Corre descalzo. Así endurecerás las\n"
	.string "plantas de los pies.$"

Route127_Text_KojiDefeat:
	.string "¡Ay! ¡Me he clavado una piedra en el\n"
	.string "dedo del pie!$"

Route127_Text_KojiPostBattle:
	.string "Ir descalzo es genial. Pero tus\n"
	.string "zapatillas de deporte también molan.$"

Route127_Text_KojiRegister:
	.string "¡Esto es lo que hago con los que me\n"
	.string "vencen! Espero que volvamos a luchar.$"

Route127_Text_KojiRematchIntro:
	.string "Sigo corriendo descalzo todos los días.\n"
	.string "¡Tengo las plantas duras como una piedra!$"

Route127_Text_KojiRematchDefeat:
	.string "¡Ay! ¡Me he clavado una piedra en el\n"
	.string "arco del pie!$"

Route127_Text_KojiPostRematch:
	.string "¿Quieres ir descalzo un rato? Así puedo\n"
	.string "probar tus zapatillas de deporte.$"

Route127_Text_AthenaIntro:
	.string "Deberíamos tener un combate lento y\n"
	.string "metódico.$"

Route127_Text_AthenaDefeat:
	.string "No me has dado la oportunidad de\n"
	.string "usar ninguna estrategia.$"

Route127_Text_AthenaPostBattle:
	.string "Cuando estoy rodeada de mar y cielo\n"
	.string "azules, siento que el tiempo se detiene.$"

Route128_Text_IsaiahIntro:
	.string "Ciudad Colosalia todavía está lejos...$"

Route128_Text_IsaiahDefeat:
	.string "Mi primera victoria también parece estar\n"
	.string "lejos...$"

Route128_Text_IsaiahPostBattle:
	.string "Toda mi vida ha sido una serie de\n"
	.string "derrotas, pero nunca me rendiré.$"

Route128_Text_IsaiahRegister:
	.string "Sé que no soy bueno ahora, pero creo que\n"
	.string "puedo ganar eventualmente.\p"
	.string "Por favor, regístrame en tu PokéNav.$"

Route128_Text_IsaiahRematchIntro:
	.string "Todavía me siento bien. Seguiré nadando\n"
	.string "hasta Ciudad Colosalia.$"

Route128_Text_IsaiahRematchDefeat:
	.string "Todavía no he saboreado mi primera\n"
	.string "victoria...$"

Route128_Text_IsaiahPostRematch:
	.string "Llegaré a Ciudad Colosalia eventualmente\n"
	.string "y allí podré ganar eventualmente...$"

Route128_Text_KatelynIntro:
	.string "En un triatlón tienes que nadar, montar\n"
	.string "en bici y luego correr una maratón.\p"
	.string "Es una carrera agotadora que consiste en\n"
	.string "tres eventos.$"

Route128_Text_KatelynDefeat:
	.string "Un combate Pokémon también es agotador...$"

Route128_Text_KatelynPostBattle:
	.string "Ahora tengo que montar en bici, pero...\n"
	.string "Estoy a punto de tirar la toalla...$"

Route128_Text_KatelynRegister:
	.string "Bueno, podría aprovechar esto. Me\n"
	.string "gustaría una revancha en algún momento.$"

Route128_Text_KatelynRematchIntro:
	.string "Un triatlón es largo. Pero supongo que el\n"
	.string "camino para convertirse en el Campeón\l"
	.string "Pokémon también es largo y agotador.$"

Route128_Text_KatelynRematchDefeat:
	.string "Un combate Pokémon realmente es duro e\n"
	.string "implacable...$"

Route128_Text_KatelynPostRematch:
	.string "Deberías pensar seriamente en los retos\n"
	.string "de la Calle Victoria.$"

Route128_Text_AlexaIntro:
	.string "Hemos estado trabajando mucho para\n"
	.string "montar un desafío a la Liga Pokémon...\p"
	.string "¡No podemos permitirnos perder ahora!$"

Route128_Text_AlexaDefeat:
	.string "¡Oh!\n"
	.string "¿Cómo ha podido pasar esto?$"

Route128_Text_AlexaPostBattle:
	.string "Después de todo lo que he hecho para\n"
	.string "llegar aquí, no me rendiré tras un\l"
	.string "contratiempo.$"

Route128_Text_RubenIntro:
	.string "¡No hay entrenador más fuerte que yo!$"

Route128_Text_RubenDefeat:
	.string "¡Esto no puede ser!$"

Route128_Text_RubenPostBattle:
	.string "Probablemente no haya entrenador más\n"
	.string "fuerte que tú.$"

Route128_Text_WayneIntro:
	.string "Quiero ir a Ciudad Colosalia, así que\n"
	.string "he atrapado un Pokémon que sabe el\l"
	.string "movimiento CASCADA para superar las\l"
	.string "cascadas.$"

Route128_Text_WayneDefeat:
	.string "¡Estoy desanimado!$"

Route128_Text_WaynePostBattle:
	.string "¡Aaaah, vaya!\p"
	.string "Mi Pokémon sabe CASCADA, pero no tengo la\n"
	.string "medalla del Gimnasio de Ciudad Algaria.$"

Route128_Text_HarrisonIntro:
	.string "Pareces muy fuerte. Me pregunto si\n"
	.string "podré ganar...$"

Route128_Text_HarrisonDefeat:
	.string "¡Ay!\n"
	.string "Supongo que era imposible ganar.$"

Route128_Text_HarrisonPostBattle:
	.string "Hay entrenadores muy fuertes por toda\n"
	.string "Ciudad Colosalia.\p"
	.string "¿Crees que podré estar a su altura?$"

Route128_Text_CarleeIntro:
	.string "La luz del sol parece más intensa en\n"
	.string "esta zona.$"

Route128_Text_CarleeDefeat:
	.string "No podía ver bien por el resplandor del\n"
	.string "sol.$"

Route128_Text_CarleePostBattle:
	.string "Debería volver pronto. Necesito\n"
	.string "reaplicarme protector solar.$"

Route129_Text_ChaseIntro:
	.string "Este es mi primer triatlón. ¡Estoy\n"
	.string "tenso y nervioso!$"

Route129_Text_ChaseDefeat:
	.string "¡Wroooooar!\n"
	.string "¡No he logrado ganar!$"

Route129_Text_ChasePostBattle:
	.string "Si estoy tenso, no podré dar lo mejor de\n"
	.string "mí.$"

Route129_Text_AllisonIntro:
	.string "Estoy en medio de un triatlón, pero da\n"
	.string "igual, ¿por qué no luchamos?$"

Route129_Text_AllisonDefeat:
	.string "¡Pensaba que ganaría!$"

Route129_Text_AllisonPostBattle:
	.string "¿Sabes qué es lo mejor de los\n"
	.string "triatlones?\p"
	.string "¡Poner a prueba los límites de tu propia\n"
	.string "fuerza y resistencia contra la Madre\l"
	.string "Naturaleza!$"

Route129_Text_ReedIntro:
	.string "¡Dí que sí, dí que sí!\n"
	.string "¡Vamos a luchar!$"

Route129_Text_ReedDefeat:
	.string "Derrotado, estoy derrotado.\n"
	.string "Eso es todo, se acabó.$"

Route129_Text_ReedPostBattle:
	.string "No hay nada para un perdedor.\n"
	.string "Es hora de volver a casa.$"

Route129_Text_TishaIntro:
	.string "¿Cuál es la prisa?\n"
	.string "Tomémonos las cosas con calma.$"

Route129_Text_TishaDefeat:
	.string "Oh, Dios mío.\n"
	.string "Quería relajarme un poco más...$"

Route129_Text_TishaPostBattle:
	.string "¿No odias cometer errores cuando vas\n"
	.string "con prisa?\p"
	.string "Por eso intento tomarme las cosas\n"
	.string "despacio.$"

Route129_Text_ClarenceIntro:
	.string "Hacer SURF no es tan fácil como parece,\n"
	.string "¿verdad?$"

Route129_Text_ClarenceDefeat:
	.string "Ganar tampoco es fácil.$"

Route129_Text_ClarencePostBattle:
	.string "¿Tienes la vista puesta en la Liga\n"
	.string "Pokémon? ¡Sigue así!$"

Route130_Text_RodneyIntro:
	.string "¡Qué sorpresa! ¡No sabía que los\n"
	.string "entrenadores salían al mar!\p"
	.string "¡Luchemos para celebrarlo!$"

Route130_Text_RodneyDefeat:
	.string "Uf... Eres fuerte, ya lo creo...$"

Route130_Text_RodneyPostBattle:
	.string "Tus ojos tienen ese brillo propio de los\n"
	.string "que están acostumbrados a aceptar retos\l"
	.string "y salir airosos. ¡Te va muy bien!$"

Route130_Text_KatieIntro:
	.string "Mi corazón se regocija cuando floto entre\n"
	.string "las suaves olas del ancho y profundo mar...$"

Route130_Text_KatieDefeat:
	.string "La amplitud de mi derrota se pierde en\n"
	.string "el horizonte...$"

Route130_Text_KatiePostBattle:
	.string "Todos los niños del mundo sueñan con\n"
	.string "convertirse en campeones Pokémon algún\l"
	.string "día. ¡Lógico!$"

Route130_Text_SantiagoIntro:
	.string "Qué bien se está flotando en el mar...\n"
	.string "Se te olvidan todos los problemas.$"

Route130_Text_SantiagoDefeat:
	.string "¿Por qué has venido a darme problemas?$"

Route130_Text_SantiagoPostBattle:
	.string "Nadar, luchar; luchar, nadar...\n"
	.string "No sé qué me gusta más...$"

Route131_Text_RichardIntro:
	.string "El mar está lleno de Pokémon. No es\n"
	.string "fácil nadar, te lo digo yo.$"

Route131_Text_RichardDefeat:
	.string "Los Pokémon criados por entrenadores son\n"
	.string "seriamente duros...$"

Route131_Text_RichardPostBattle:
	.string "Uf... Uf... Estoy agotado...\p"
	.string "Ir es fácil. Lo difícil es volver.\p"
	.string "¿Tendré energía suficiente para hacer el\n"
	.string "viaje de vuelta?$"

Route131_Text_HermanIntro:
	.string "El mar... El mar... El mar... El mar\n"
	.string "hasta donde alcanza la vista... ¡Estoy\l"
	.string "hasta las narices del mar!$"

Route131_Text_HermanDefeat:
	.string "¡Bleah!$"

Route131_Text_HermanPostBattle:
	.string "Estoy aburrido del mar, pero seguiré\n"
	.string "nadando. ¡Soy un nadador nato!\l"
	.string "¡Eso es lo que soy!$"

Route131_Text_SusieIntro:
	.string "¡Hola, cariño, espera! Deberíamos\n"
	.string "luchar, tú y yo.$"

Route131_Text_SusieDefeat:
	.string "¡Eres fuerte a pesar de tu apariencia!$"

Route131_Text_SusiePostBattle:
	.string "¿Has visto a un tipo por ahí que se\n"
	.string "queja de que está aburrido del mar?\p"
	.string "Es todo teatro. ¡Está locamente\n"
	.string "enamorado del mar!$"

Route131_Text_KaraIntro:
	.string "¿Por qué a los hombres les gustan tanto\n"
	.string "los bañadores?\p"
	.string "¡Todos me miran!$"

Route131_Text_KaraDefeat:
	.string "¡Estoy fuera de mi elemento!$"

Route131_Text_KaraPostBattle:
	.string "Quizá no sea mi bañador lo que hace que\n"
	.string "los hombres me miren. ¡Debe ser mi\l"
	.string "belleza!$"

Route131_Text_ReliIntro:
	.string "RELI: ¡Lucharemos juntos como hermanos\n"
	.string "para derrotarte!$"

Route131_Text_ReliDefeat:
	.string "RELI: No hemos podido ganar incluso\n"
	.string "trabajando juntos...$"

Route131_Text_ReliPostBattle:
	.string "RELI: La gente de Pacifídlog está junto\n"
	.string "al mar y los Pokémon desde que nacen.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: ¿No tienes dos Pokémon? Entonces\n"
	.string "no podemos disfrutar de un combate.$"

Route131_Text_IanIntro:
	.string "IAN: ¡Estoy haciendo lo mejor que puedo\n"
	.string "junto con mi hermana!$"

Route131_Text_IanDefeat:
	.string "IAN: Hice lo mejor que pude junto con\n"
	.string "mi hermana, pero aun así no pudimos\l"
	.string "ganar...$"

Route131_Text_IanPostBattle:
	.string "IAN: ¿Sabes que Pacifídlog es una ciudad\n"
	.string "flotante?\p"
	.string "Así que, dondequiera que haya mar, ¡eso\n"
	.string "es parte de Pacifídlog!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Si tienes dos Pokémon, ¡te\n"
	.string "enfrentaremos!$"

Route131_Text_TaliaIntro:
	.string "Si me vences, te daré una información\n"
	.string "muy valiosa.$"

Route131_Text_TaliaDefeat:
	.string "Oh?\n"
	.string "¿He perdido?$"

Route131_Text_TaliaPostBattle:
	.string "Hay un lugar extraño cerca de aquí.\n"
	.string "Hay una torre enorme. ¿Por qué no vas\l"
	.string "a echar un vistazo?$"

Route131_Text_KevinIntro:
	.string "La gente de Pacifídlog es pacífica.\p"
	.string "Nunca se enfadan.\n"
	.string "Yo tampoco me enfado.$"

Route131_Text_KevinDefeat:
	.string "¡Ups!$"

Route131_Text_KevinPostBattle:
	.string "Tch... Espera.\n"
	.string "No estoy enfadado. En serio.\p"
	.string "Pero, vaya, ¡eres fuerte!\n"
	.string "¡Ja, ja, ja!$"

Route132_Text_GilbertIntro:
	.string "De pequeño siempre me resfriaba, pero\n"
	.string "me volví totalmente sano desde que\l"
	.string "empecé a nadar.$"

Route132_Text_GilbertDefeat:
	.string "Anhelo más poder...$"

Route132_Text_GilbertPostBattle:
	.string "Los entrenadores viajan por campos y\n"
	.string "montañas, así que también deben estar en\l"
	.string "forma.$"

Route132_Text_DanaIntro:
	.string "Intento no nadar donde las corrientes\n"
	.string "son demasiado fuertes.$"

Route132_Text_DanaDefeat:
	.string "¡Oh, por favor, no!$"

Route132_Text_DanaPostBattle:
	.string "Si me arrastra la corriente, perderé\n"
	.string "todo sentido de orientación...$"

Route132_Text_RonaldIntro:
	.string "Nunca sabrás si ganarás o perderás\n"
	.string "hasta que lo intentes.$"

Route132_Text_RonaldDefeat:
	.string "¡Waaah!\n"
	.string "¡Me hundo en la derrota!$"

Route132_Text_RonaldPostBattle:
	.string "Nunca lucho cuando sé que voy a ganar.\n"
	.string "Me gusta luchar al filo de la victoria\l"
	.string "y la derrota.$"

Route132_Text_KiyoIntro:
	.string "Pienso en Pokémon las 24 horas del día.\n"
	.string "¿Cómo podrías vencerme?$"

Route132_Text_KiyoDefeat:
	.string "Pierdo.\n"
	.string "Acepto la derrota.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh...\n"
	.string "Eres un fanático de los Pokémon, ¿no?\p"
	.string "Debes pensar en Pokémon las 24 horas del\n"
	.string "día, ¿verdad?$"

Route132_Text_MakaylaIntro:
	.string "Siempre estoy con mi marido, pero puedo\n"
	.string "ganar incluso sin él.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, supongo que no era lo suficientemente\n"
	.string "buena.$"

Route132_Text_MakaylaPostBattle:
	.string "Ese joven de ahí parece mi marido cuando\n"
	.string "era joven. ¡Me está haciendo sonrojar!$"

Route132_Text_JonathanIntro:
	.string "Alguien me ha estado mirando\n"
	.string "intensamente. ¿Eras tú?$"

Route132_Text_JonathanDefeat:
	.string "¡Guau!\n"
	.string "¡Eso es bastante fuerte, sí señor!$"

Route132_Text_JonathanPostBattle:
	.string "No puedo quitarme la sensación de que\n"
	.string "alguien me está mirando.\p"
	.string "¡No puedo concentrarme!$"

Route132_Text_PaxtonIntro:
	.string "¿Dónde se habrá metido mi mujer? Siempre\n"
	.string "estoy con ella. Me pregunto si puedo\l"
	.string "ganar por mi cuenta.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, veo que no pude ganar por mi cuenta\n"
	.string "después de todo.$"

Route132_Text_PaxtonPostBattle:
	.string "Mi mujer debe estar buscándome. Será\n"
	.string "mejor que vaya a encontrarla de inmediato.$"

Route132_Text_DarcyIntro:
	.string "Me gustaba entrenar aquí sola. ¡Es\n"
	.string "horrible que toda esta gente haya venido!$"

Route132_Text_DarcyDefeat:
	.string "¡Vale! No me quejaré de que haya otra\n"
	.string "gente aquí.$"

Route132_Text_DarcyPostBattle:
	.string "Supongo que puedo formar equipo con ese\n"
	.string "anciano y desafiar a ese otro equipo.$"

Route133_Text_FranklinIntro:
	.string "¿También te ha traído la corriente hasta\n"
	.string "aquí? Esto debía estar escrito.\l"
	.string "¡Luchemos!$"

Route133_Text_FranklinDefeat:
	.string "¡Fuerte!\n"
	.string "¡Demasiado fuerte!$"

Route133_Text_FranklinPostBattle:
	.string "Es mi mala suerte que un entrenador tan\n"
	.string "duro como tú haya llegado aquí...\l"
	.string "Debo estar maldito...$"

Route133_Text_DebraIntro:
	.string "He llevado una vida de pena y\n"
	.string "miseria... He sido abandonada, y aquí\l"
	.string "es donde he acabado...$"

Route133_Text_DebraDefeat:
	.string "Otra derrota...$"

Route133_Text_DebraPostBattle:
	.string "Una vida a la deriva...\n"
	.string "Ya no la quiero más.$"

Route133_Text_LindaIntro:
	.string "¡Bienvenido!\n"
	.string "¡Te estaba esperando!$"

Route133_Text_LindaDefeat:
	.string "¡No! ¡Por favor!$"

Route133_Text_LindaPostBattle:
	.string "Un niño entrenador tan fuerte...\n"
	.string "¡Es tan molesto!$"

Route133_Text_WarrenIntro:
	.string "Quiero ganar como todo el mundo, pero no\n"
	.string "voy a criar Pokémon como todo el mundo.$"

Route133_Text_WarrenDefeat:
	.string "¡Maldita sea!\n"
	.string "¡Mi forma sigue siendo demasiado floja!$"

Route133_Text_WarrenPostBattle:
	.string "Es mucho más divertido hacer las cosas a\n"
	.string "tu manera que ser como todo el mundo.\l"
	.string "¡Es obvio!$"

Route133_Text_BeckIntro:
	.string "He venido hasta aquí con mis Pokémon\n"
	.string "pájaro.$"

Route133_Text_BeckDefeat:
	.string "Tú...\n"
	.string "¡Eres impresionantemente genial!$"

Route133_Text_BeckPostBattle:
	.string "Me gustaría volver a Ciudad Arborada,\n"
	.string "pero también me he encariñado con este\l"
	.string "lugar.$"

Route133_Text_MollieIntro:
	.string "Debo de haber luchado miles de veces.\n"
	.string "He perdido la cuenta.$"

Route133_Text_MollieDefeat:
	.string "Puede que haya perdido miles de veces,\n"
	.string "pero una derrota todavía duele.$"

Route133_Text_MolliePostBattle:
	.string "Sigue así, jovencito. Así podrás\n"
	.string "convertirte como mi marido y yo.$"

Route133_Text_ConorIntro:
	.string "Los jóvenes son demasiado felices\n"
	.string "dejándose llevar por la corriente. No\l"
	.string "tienen dirección.$"

Route133_Text_ConorDefeat:
	.string "Tienes un sentido de propósito firme.$"

Route133_Text_ConorPostBattle:
	.string "No dejes que otros te desvíen. No pierdas\n"
	.string "tu dirección a medida que envejeces.$"

Route134_Text_JackIntro:
	.string "Incluso los Pokémon que pueden nadar son\n"
	.string "arrastrados por las rápidas corrientes.$"

Route134_Text_JackDefeat:
	.string "¡Aiyeeeeh!$"

Route134_Text_JackPostBattle:
	.string "Creo que a los Pokémon les gustan las\n"
	.string "corrientes rápidas de esta zona.$"

Route134_Text_LaurelIntro:
	.string "Mis Luvdisc están buscando un combate\n"
	.string "divertido. ¿Te unes a nosotros?$"

Route134_Text_LaurelDefeat:
	.string "¡Ups!$"

Route134_Text_LaurelPostBattle:
	.string "Hay un coleccionista que busca las\n"
	.string "escamas de Luvdisc.$"

Route134_Text_AlexIntro:
	.string "¡Vale, vale! Ya he descansado bastante,\n"
	.string "chicos. ¡Es hora de un combate!$"

Route134_Text_AlexDefeat:
	.string "Agotado otra vez...$"

Route134_Text_AlexPostBattle:
	.string "Mis Pokémon pájaro se cansan rápidamente\n"
	.string "después de un vuelo largo...$"

Route134_Text_HitoshiIntro:
	.string "Eres un entrenador Pokémon. No hacen\n"
	.string "falta palabras. Luchamos ahora.$"

Route134_Text_HitoshiDefeat:
	.string "... ... ... ... ... ...\n"
	.string "... ... ... ... ... ...$"

Route134_Text_HitoshiPostBattle:
	.string "Fui yo quien te desafió, y aun así\n"
	.string "perdí. Me siento profundamente avergonzado...$"

Route134_Text_AaronIntro:
	.string "La marea salvaje de esta zona nos hace\n"
	.string "más fuertes que nunca.$"

Route134_Text_AaronDefeat:
	.string "Acepto mi derrota de buen grado.$"

Route134_Text_AaronPostBattle:
	.string "Volveremos para entrenar más en la\n"
	.string "Cascada Meteoro.\p"
	.string "Si quieres, deberías ir tú también.\n"
	.string "¡Definitivamente te hará más fuerte!$"

Route134_Text_KelvinIntro:
	.string "¡N-nuestra barca! ¡La corriente se la ha\n"
	.string "llevado!$"

Route134_Text_KelvinDefeat:
	.string "¡Awawawawah! ¡Por favor, para! ¡Por\n"
	.string "favor!$"

Route134_Text_KelvinPostBattle:
	.string "Si no podemos hacer SURF, ¿cómo vamos a\n"
	.string "volver a casa?\p"
	.string "En realidad, sé que un Pokémon debilitado\n"
	.string "todavía puede hacer SURF, pero se siente\l"
	.string "mal.$"

Route134_Text_MarleyIntro:
	.string "¿Pueden tus Pokémon esquivar nuestros\n"
	.string "ataques relámpago?$"

Route134_Text_MarleyDefeat:
	.string "¡Nunca supe que existía tal técnica!\n"
	.string "¡Nos has derrotado completamente!$"

Route134_Text_MarleyPostBattle:
	.string "No he perdido mi pasión por la velocidad.\n"
	.string "Lo intentaré más duro.$"

Route134_Text_ReynaIntro:
	.string "¡Mis Pokémon no pueden ser derrotados\n"
	.string "fácilmente!$"

Route134_Text_ReynaDefeat:
	.string "¡¿Estás de broma?!\n"
	.string "¡Explica cómo he perdido!$"

Route134_Text_ReynaPostBattle:
	.string "¡Ja, ja!\n"
	.string "¡Has ganado, de acuerdo!\p"
	.string "Volveré a entrenarme enfrentándome a\n"
	.string "entrenadores que encuentre por el camino.$"

Route134_Text_HudsonIntro:
	.string "Oye, ¿has visto a otro marinero por aquí?$"

Route134_Text_HudsonDefeat:
	.string "¡Ahora eso es algo!$"

Route134_Text_HudsonPostBattle:
	.string "Nuestra barca ha derivado hacia el mar.\p"
	.string "Mi compañero es un tipo tímido, así que\n"
	.string "estoy preocupado por él.$"
