VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Muy lejos, en lo profundo de Ciudad\n"
	.string "Colosalia, se encuentra la Liga Pokémon.\p"
	.string "Los entrenadores que se reúnen allí son\n"
	.string "todos aterradamente hábiles.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "En la Liga Pokémon, creo que las reglas\n"
	.string "dicen que tienes que combatir contra los\l"
	.string "Cuatro Élite seguidos.\p"
	.string "Si pierdes contra alguno de ellos, tienes\n"
	.string "que empezar tu desafío otra vez desde el\l"
	.string "primero.$"

