SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Un volcán submarino entró en erupción y\n"
	.string "se abrió camino desde las profundidades.\p"
	.string "Su cráter emergió del mar y se llenó\n"
	.string "de agua de lluvia.\p"
	.string "Así es como surgió la CIUDAD ARRECÍPOLIS.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "La cueva que une ARRECÍPOLIS con el\n"
	.string "mundo exterior…\p"
	.string "Parece como si la cueva se hubiera hecho\n"
	.string "para evitar que algo saliera.\p"
	.string "¿O es solo mi imaginación?$"

