OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "Cuando empieza un combate Pokémon, el\n"
	.string "que está a la izquierda de la lista sale\l"
	.string "el primero.\p"
	.string "Así que, cuando tengas más Pokémon en\n"
	.string "tu equipo, prueba a cambiar el orden de\l"
	.string "tus Pokémon.\p"
	.string "Podría darte una ventaja.$"

