PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "¡Viajar es maravilloso!\p"
	.string "¡Cuando era joven, recorrí los mares\n"
	.string "y las montañas!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Suspiro…\p"
	.string "Ojalá pudiera irme de aventuras\n"
	.string "con algunos Pokémon…\p"
	.string "Arrastrarme por hierba húmeda…\n"
	.string "Escalar montañas rocosas y escarpadas…\p"
	.string "Cruzar mares embravecidos…\n"
	.string "Vagar por cuevas oscuras…\p"
	.string "Y, a veces, incluso sentir un poco\n"
	.string "de nostalgia…\p"
	.string "¡Debe ser fabuloso viajar!$"

