FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Hablando de Pokédex, se me ha ocurrido\n"
	.string "algo.\p"
	.string "Conocí a un entrenador, Máximo, cuando\n"
	.string "estaba buscando piedras raras.\p"
	.string "Uf, vaya, tenía algunos Pokémon\n"
	.string "increíbles con él.\p"
	.string "No solo eran raros, ¡estaban entrenados\n"
	.string "a unos extremos aterradores!\p"
	.string "Puede que sea incluso más fuerte que el\n"
	.string "líder del Gimnasio de este pueblo…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "¿Qué es esa cosa que tienes ahí?\p"
	.string "… … … … … …\p"
	.string "Oh, ¿se llama Pokédex?\n"
	.string "¡Es realmente genial!$"

