SootopolisCity_Gym_B1F_MapScripts::
	.byte 0

SootopolisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

SootopolisCity_Gym_B1F_Text_AndreaIntro:
	.string "¡Te mostraré las técnicas sublimes que\n"
	.string "aprendí de nuestro LÍDER JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Perdóname, JUAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Fíjate en lo que ocurre si agotas\n"
	.string "todas las baldosas del suelo.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro:
	.string "Has venido desde muy lejos, pero no\n"
	.string "vas a ver a JUAN.\p"
	.string "¡Y menos si pierdes contra mí!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat:
	.string "¡Eres fuerte!\n"
	.string "¡Me ha engañado tu aspecto adorable!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "Puede que seas lo bastante fuerte como\n"
	.string "para que JUAN no te derrote de un\l"
	.string "solo golpe.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro:
	.string "Ver a JUAN dirigiendo un combate…\p"
	.string "La belleza misma de ello me impulsó a\n"
	.string "convertirme en ENTRENADORA.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat:
	.string "Has combatido con más belleza de la\n"
	.string "que yo podía mostrar…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "La elegancia que aportas al combate es\n"
	.string "fabulosa.\p"
	.string "Oh… Tengo tanta suerte de haber\n"
	.string "encontrado a los POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro:
	.string "Debería enseñarte lo duros que pueden\n"
	.string "ser los combates.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "Eres fuerte.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle:
	.string "Te contaré algo bueno.\p"
	.string "Si quieres llegar hasta JUAN, tienes\n"
	.string "que pisar cada baldosa del suelo una vez.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro:
	.string "El GIMNASIO POKéMON de mayor nivel\n"
	.string "de la región de HOENN…\p"
	.string "Ese es el GIMNASIO de ARRECÍPOLIS.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat:
	.string "¡Vaya nivel que tienes!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "En lugar de conformarse con estar en un\n"
	.string "GIMNASIO fuerte, me imagino que entrenar\l"
	.string "en otros lugares te hará más fuerte.\l"
	.string "Pero, sobre todo, parece más divertido.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro:
	.string "Entreno a mis POKéMON junto con\n"
	.string "JUAN.\p"
	.string "No creas que soy fácil de vencer.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat:
	.string "He sido derrotada…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "Creo que tienes potencial.\n"
	.string "¿Por qué no te quedas a entrenar\l"
	.string "con nosotros?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro:
	.string "Un desliz elegante sobre el hielo sin\n"
	.string "cruzar líneas…\p"
	.string "¡Un ENTRENADOR que lograra eso sería\n"
	.string "de una belleza elegante!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "¡Vaya, cómo se atreve!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "Esto es bastante obvio, pero lo fuerte\n"
	.string "que seas como ENTRENADOR no tiene nada\l"
	.string "que ver con lo joven o viejo que seas.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro:
	.string "Cuando estoy con mis POKéMON, el tiempo\n"
	.string "pasa volando antes de que puedas decir:\l"
	.string "“¡Ups!”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat:
	.string "¡Ups!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "Ojalá pudiera olvidar las causas\n"
	.string "perdidas tan rápido como digo “¡Ups!”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro:
	.string "Puedo combatir con POKéMON realmente\n"
	.string "raros si quieres.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "¡Oh, vaya! ¿Has podido ver bien\n"
	.string "a mis POKéMON?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "Vine a este GIMNASIO porque JUAN me\n"
	.string "elogió por mis adorables POKéMON.\p"
	.string "Oh, si tan solo hubiera conocido a JUAN\n"
	.string "hace años, cuando era más joven…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro:
	.string "Ji, ji…\n"
	.string "Ese aspecto adusto es tan encantador.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, cielos.\n"
	.string "Te lo he puesto demasiado fácil.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "Seguro que no puedes ni tocar a JUAN.\n"
	.string "Ji, ji…$"

