LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Los mayores misterios de este planeta\n"
	.string "están en el fondo del mar.\p"
	.string "Alguien dijo eso, pero no lo sé…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Hay una profunda fosa submarina entre\n"
	.string "CIUDAD ALGARROBO y CIUDAD ARRECÍPOLIS.\p"
	.string "Eso es lo que alguien me dijo, en\n"
	.string "cualquier caso.$"

